"""Aircraft Technical trial set: fuller KEY FACT cards, 2026-10-08.

The user asked for more informative cards on the 25 trial questions; the explanations stay as they are. Each card
leads with the answer and adds the working detail: how it works, what the pilot does, the common trap, a memory
hook. Facts follow the Aircraft General Knowledge manual (rate-one bank: IAS / 10 + 7).
"""
import json

from trial_aircraft_technical import TRIAL


def card(headline, subline, blocks, formula=None):
    d = {"kicker": "KEY FACT", "headline": headline, "subline": subline,
         "blocks": [{"label": a, "value": b} for a, b in blocks]}
    if formula:
        d["formula"] = formula
    return json.dumps(d, ensure_ascii=False)


CARDS = {
    2428: card("SEMI-CANTILEVER = WING BRACED BY STRUTS", "STRUTS RUN FROM THE LOWER FUSELAGE TO THE WING",
               [("You'll see it on", "Cessna 172, Piper Cub: a high wing with a lift strut"),
                ("Full cantilever", "No struts; the spar carries every load to the root (PA-28)"),
                ("Why struts", "A lighter spar and wing structure"),
                ("The cost", "Extra drag from the struts"),
                ("Exam trap", "\"Cantilever\" on its own means no external bracing")]),
    2429: card("THE LONGERON IS THE MAIN LENGTHWISE MEMBER", "IN A TRUSS FUSELAGE THE FRAMEWORK CARRIES ALL THE LOAD",
               [("Longerons", "Usually four, running from the firewall to the tail"),
                ("Bracing", "Verticals and diagonals form rigid triangles"),
                ("Covering", "Fabric or light skin: carries no load"),
                ("Not in a truss", "Formers and stringers (monocoque, semi-monocoque)"),
                ("Remember", "LONGeron = the LONG member")]),
    2432: card("AFT CG REDUCES LONGITUDINAL STABILITY", "SHORTER TAIL ARM, SO A WEAKER RESTORING MOMENT",
               [("Stability", "Less stable in pitch"),
                ("Elevator", "Lighter; easy to over-control"),
                ("Stall speed", "Slightly lower (less tail download)"),
                ("Behind the aft limit", "Stall and spin recovery may not be possible"),
                ("Forward CG", "More stable, heavier elevator, higher stall speed")]),
    2440: card("THE MAIN SPAR IS THE WING'S MOST IMPORTANT PART", "A ROOT-TO-TIP BEAM CARRYING MOST OF THE BENDING AND SHEAR",
               [("Main spar", "The primary load-carrying beam"),
                ("Ribs", "Give the aerofoil shape; pass the air loads to the spars"),
                ("Rear spar", "Carries the ailerons and flaps"),
                ("Skin and stringers", "Share the load in a stressed-skin wing"),
                ("Exam trap", "Longerons belong to the fuselage, not the wing")]),
    2450: card("TORQUE: THE REACTION OPPOSITE TO THE PROPELLER'S ROTATION", "NEWTON'S THIRD LAW: PROPELLER ONE WAY, AIRCRAFT THE OTHER",
               [("In the air", "Tries to roll the aircraft"),
                ("On the ground", "One main wheel pressed down harder: the aircraft swings"),
                ("Biggest when", "High power at low airspeed: the take-off run"),
                ("Not torque", "P-factor, slipstream, gyroscopic precession, centrifugal force")]),
    2452: card("CLOCKWISE PROPELLER: THE AEROPLANE YAWS LEFT", "HOLD IT STRAIGHT WITH RIGHT RUDDER ON THE TAKE-OFF RUN",
               [("Slipstream", "Spirals round and hits the left of the fin"),
                ("Torque reaction", "Presses the left wheel down harder"),
                ("P-factor", "The down-going right blade pulls harder at high angles"),
                ("Gyroscopic", "Little effect: a tricycle's tail stays down"),
                ("Pilot action", "Right rudder as the power comes in")]),
    2464: card("THE TAILPLANE GIVES PITCH STABILITY", "ITS FORCE ACTS UP OR DOWN, WHICHEVER BRINGS THE NOSE BACK",
               [("Nose pitches up", "Tail force up: the nose is pushed back down"),
                ("Nose pitches down", "Tail force down: the nose is pushed back up"),
                ("In normal cruise", "Usually a small download, balancing a nose-heavy CG"),
                ("Remember", "Tailplane: pitch · Fin: yaw · Dihedral: roll")]),
    2466: card("THE FOWLER FLAP INCREASES WING AREA", "IT RUNS BACK ON TRACKS, THEN DOWN",
               [("First stage", "Mostly more area: extra lift, little drag"),
                ("Fully down", "Area and camber: the biggest lift increase"),
                ("Plain flap", "Hinged trailing edge: camber only"),
                ("Split flap", "Lower surface only: lots of drag"),
                ("Slotted flap", "A slot re-energises the airflow over the flap")]),
    2469: card("BAFFLES STOP THE FUEL SURGING", "WALLS WITH HOLES INSIDE THE TANK SLOW THE FUEL DOWN",
               [("Fuel outlet", "Stays covered in turns and manoeuvres"),
                ("CG", "No sudden shifts"),
                ("Tank structure", "Not hammered by moving fuel"),
                ("Vent", "Keeps the tank at atmospheric pressure"),
                ("Drain and sump", "Where water is removed")]),
    2474: card("VALVE LEAD: THE INLET OPENS BEFORE TDC", "AT THE END OF THE EXHAUST STROKE",
               [("Why", "Fully open when induction starts, so more mixture gets in"),
                ("Valve lag", "The inlet closes late, after BDC"),
                ("Valve overlap", "Inlet and exhaust both open around TDC"),
                ("Remember", "Lead = opens early · Lag = closes late")]),
    2500: card("ROUGH RUNNING, THEN A SLOW LOSS OF POWER: CARB ICE", "ICE BUILDS GRADUALLY AT THE VENTURI AND THROTTLE BUTTERFLY",
               [("Why it forms", "Fuel evaporation and the venturi cool the air by up to 30°C"),
                ("Worst conditions", "Humid air and low power, even on warm days"),
                ("Fixed-pitch propeller", "A gradual drop in RPM"),
                ("Not carb ice", "Magneto: sudden drop · Empty tank: surging, then stopping"),
                ("Action", "Full carb heat at the first sign")]),
    2504: card("AVGAS 100LL IS DYED BLUE", "CHECK THE COLOUR EVERY TIME YOU TAKE A FUEL SAMPLE",
               [("100LL", "Blue (low lead)"),
                ("100", "Green"),
                ("80", "Red"),
                ("Jet A-1", "Clear to straw: never in a piston engine"),
                ("Water", "Clear blobs or a layer at the bottom of the cup")]),
    2525: card("COOLING FINS IMPROVE ENGINE COOLING", "THEY ADD SURFACE AREA FOR THE HEAT TO ESCAPE TO THE AIR",
               [("Fins", "More area losing heat to the air"),
                ("Baffles", "Force the air through the fins"),
                ("Cowl flaps", "Control how much air flows"),
                ("Watch", "Cylinder head and oil temperatures in long climbs"),
                ("Exam trap", "Fins do not increase the airflow")]),
    2530: card("THE SCAVENGE PUMP RETURNS OIL TO THE TANK", "IT KEEPS THE SUMP OF A DRY-SUMP ENGINE DRY",
               [("Oil stored", "In a separate tank, not the sump"),
                ("Pressure pump", "Tank to the engine"),
                ("Scavenge pump", "Sump back to the tank"),
                ("Bigger capacity", "The returning oil is hot and frothy"),
                ("Wet sump", "Oil kept in the sump; no scavenge pump")]),
    2549: card("MAIN BEARINGS GET HIGH-PRESSURE OIL", "FROM THE PUMP THROUGH GALLERIES AND CRANKSHAFT DRILLINGS",
               [("Pressure-fed", "Main and big-end bearings, camshaft"),
                ("Splash-fed", "Cylinder walls, pistons, small ends"),
                ("Why pressure", "The heaviest loads need a positive supply"),
                ("Low oil pressure", "The bearings are at risk: treat it as serious")]),
    2629: card("GREEN ARC: THE NORMAL OPERATING RANGE", "FROM VS1 (CLEAN STALL) TO VNO",
               [("Bottom of the green", "VS1: stall with flaps up at maximum weight"),
                ("Top of the green", "VNO: maximum structural cruising speed"),
                ("White arc", "Flap operating range: VSO to VFE"),
                ("Yellow arc", "Caution: smooth air only"),
                ("Red line", "VNE: never exceed")]),
    2673: card("LOAD FACTOR DEPENDS ONLY ON THE ANGLE OF BANK", "IN A LEVEL, COORDINATED TURN",
               [("30°", "1.15 g"), ("45°", "1.41 g"), ("60°", "2 g"),
                ("Stall speed", "Rises with √n: about 41% higher at 60°"),
                ("Not a factor", "Airspeed or rate of turn (they set the radius)")],
               formula="n = 1 / cos (BANK)"),
    2675: card("THE TURN COORDINATOR SHOWS RATE OF TURN", "RATE ONE = 3° PER SECOND, 360° IN 2 MINUTES",
               [("Canted gyro", "Tilted about 30°, so it also senses roll"),
                ("Rate-one bank", "Rule of thumb: IAS ÷ 10 + 7 degrees"),
                ("Does not show", "Bank angle: use the attitude indicator"),
                ("Balance ball", "Shows slip or skid")]),
    2701: card("DEVIATION COMES FROM THE AIRCRAFT'S OWN MAGNETISM", "IT CHANGES WITH HEADING",
               [("Sources", "Engine steel, radios, wiring, loose items near the compass"),
                ("Reduced by", "A compass swing and the compensating magnets"),
                ("What's left", "Shown on the deviation card"),
                ("Variation", "True vs magnetic north: depends on where you are"),
                ("Remember", "Deviation: the aircraft · Variation: the Earth")]),
    2707: card("ISA: +15°C AT SEA LEVEL, FALLING 1.98°C PER 1,000 FT", "UP TO THE TROPOPAUSE AT 36,090 FT, THEN -56.5°C",
               [("Pressure", "1013.25 hPa at sea level"),
                ("Density", "1.225 kg/m³ at sea level"),
                ("Above 36,090 ft", "Constant -56.5°C"),
                ("Quick check", "ISA temperature ≈ 15 − 2 × altitude in thousands of ft"),
                ("Not ISA", "3°C per 1,000 ft is the dry adiabatic rate")]),
    2726: card("MOST POWER IN COLD, DRY, HIGH-PRESSURE AIR", "DENSE AIR PUTS MORE OXYGEN IN EACH CYLINDER",
               [("Cold", "Denser than warm air"),
                ("High pressure", "More air in the same space"),
                ("Dry", "Water vapour is lighter than the air it replaces"),
                ("Worst case", "Hot, humid, high airfield: long take-off run, poor climb")]),
    2734: card("AN INVERTER CONVERTS DC TO AC", "FOR AC INSTRUMENTS AND AVIONICS IN A DC AIRCRAFT",
               [("Inverter", "DC to AC"),
                ("Rectifier", "AC to DC"),
                ("TRU", "Transformer-rectifier: AC to lower-voltage DC"),
                ("Thermistor", "A temperature-sensitive resistor, not a converter"),
                ("Remember", "The INverter turns DC INto AC")]),
    2740: card("VFE: MAXIMUM SPEED WITH FLAPS EXTENDED", "THE TOP OF THE WHITE ARC",
               [("VFE", "Flaps extended"),
                ("VLE", "Landing gear extended"),
                ("VNO", "Maximum structural cruising speed: top of the green"),
                ("VSO", "Stall in the landing configuration: bottom of the white"),
                ("Before selecting flap", "Check you are below VFE")]),
    2768: card("THE BALL SHOWS SLIP OR SKID", "THE NEEDLE SHOWS RATE AND DIRECTION OF TURN",
               [("Ball centred", "A coordinated turn"),
                ("Ball inside the turn", "Slipping: too much bank for the rate of turn"),
                ("Ball outside the turn", "Skidding: too much rudder"),
                ("The fix", "Step on the ball: rudder on the side the ball has moved to")]),
    2771: card("THE ASI IS CALIBRATED FOR ISA SEA-LEVEL DENSITY", "1.225 kg/m³: ONLY THERE DOES IAS EQUAL TAS",
               [("It measures", "Dynamic pressure, which depends on speed and density"),
                ("Higher or hotter", "Thinner air: the ASI reads below TAS"),
                ("Rule of thumb", "TAS ≈ IAS + 2% per 1,000 ft"),
                ("Stall speed", "Stays about the same in IAS")],
               formula="DYNAMIC PRESSURE = ½ × DENSITY × V²"),
}

assert set(CARDS) == set(TRIAL)
