"""Flight Planning trial set: fuller KEY FACT cards, 2026-10-09.

Thin cards (fewer than three points) get four or five, to the standard of atg_trial_cards.py: the reading or the
sum, the related numbers, the exam trap. Headlines stay; explanations are unchanged. Chart values are the ones the
explanations read from the SACAA-01 manual figures.
"""
import json


def card(headline, subline, blocks, formula=None):
    d = {"kicker": "KEY FACT", "headline": headline, "subline": subline,
         "blocks": [{"label": a, "value": b} for a, b in blocks]}
    if formula:
        d["formula"] = formula
    return json.dumps(d, ensure_ascii=False)


CARDS = {
    2240: card("HIGHER DENSITY ALTITUDE REDUCES CLIMB PERFORMANCE", "THINNER AIR: LESS POWER, THRUST AND LIFT",
               [("Caused by", "High elevation, high temperature, low pressure, high humidity"),
                ("Engine and propeller", "Less power and less thrust"),
                ("Wings", "Same IAS, but a higher TAS and groundspeed"),
                ("Runways", "Longer take-off and landing runs"),
                ("Rule of thumb", "About 120 ft of density altitude for each 1°C above ISA")],
               "Density altitude ≈ PA + 120 × (OAT − ISA temperature)"),
    2244: card("MAXIMUM RAMP WEIGHT = MTOW + TAXI FUEL", "THE TAXI FUEL IS BURNT BEFORE BRAKE RELEASE",
               [("Zero fuel weight", "Basic empty + crew, passengers and baggage"),
                ("Ramp weight", "Zero fuel + all the fuel on board: the heaviest"),
                ("Take-off weight", "Ramp − taxi fuel: must not exceed MTOW"),
                ("Landing weight", "Take-off − trip fuel: must not exceed MLW"),
                ("Exam trap", "Not landing weight + reserve: it is MTOW + taxi fuel")],
               "Ramp weight = take-off weight + taxi fuel"),
    2247: card("2,265 FT TO CLEAR 50 FT", "FIGURE 1-22, PA 4,000 FT, MIDWAY +10°C TO +20°C",
               [("Table", "2,185 ft at +10°C; 2,345 ft at +20°C"),
                ("+15°C", "(2,185 + 2,345) ÷ 2 = 2,265 ft"),
                ("Take-off distance", "Brake release to 50 ft above the runway"),
                ("Ground roll", "Brake release to lift-off only"),
                ("Notes on the table", "Headwind shortens it; tailwind (+10% per 2 kt) lengthens it")],
               "Midway value = (lower + upper) ÷ 2"),
    2250: card("GLIDE RANGE ABOUT 19 NM", "HEIGHT = 10,500 − 1,500 = 9,000 FT",
               [("Figure 1-16", "Height above the terrain in, glide range out"),
                ("Chart conditions", "Power off, flaps 0°, 75 KIAS, 2,500 lb, zero wind"),
                ("Rough check", "About 2.1 NM per 1,000 ft: 9 × 2.1 ≈ 19 NM"),
                ("Wind", "A headwind shortens the glide, a tailwind stretches it"),
                ("Exam trap", "Enter with the height above the terrain, not the cruising altitude")]),
    2254: card("VFE: MAXIMUM SPEED WITH FLAPS EXTENDED", "TOP OF THE WHITE ARC",
               [("White arc", "VS0 at the bottom, VFE at the top: the flap range"),
                ("Green arc", "VS1 to VNO: normal operation"),
                ("Yellow arc", "VNO to VNE: smooth air only"),
                ("Red line", "VNE: never exceed"),
                ("Above VFE", "Overstresses the flaps and their mountings")]),
    2255: card("RUNWAY 18 SLOPES 1.45% DOWN", "5,180 FT AT ITS START, 5,125 FT AT ITS END",
               [("Working", "55 ÷ 3,800 × 100 = 1.45%"),
                ("Direction", "Taking off on 18 you start high and run downhill"),
                ("Runway 36", "The same 1.45%, but uphill"),
                ("Downslope", "Shorter take-off, longer landing"),
                ("Upslope", "Longer take-off, shorter landing")],
               "Slope % = elevation difference ÷ runway length × 100 (same units)"),
    2264: card("MORE HEADWIND ON FINAL: OVERSHOOT", "AIRSPEED AND LIFT RISE, THE AIRCRAFT GOES ABOVE THE GLIDE PATH",
               [("Why", "Inertia keeps the groundspeed; the extra headwind adds airspeed"),
                ("Opposite", "Less headwind or more tailwind: undershoot"),
                ("Correct", "Reduce power smoothly; be ready for the headwind to die away"),
                ("Danger", "A headwind that dies near the ground: sink and undershoot"),
                ("Expect it", "Near thunderstorms, fronts, low-level inversions, hills")]),
    2265: card("42 USG AT SG 0.72 WEIGHS ABOUT 114 KG", "LITRES × SG = KILOGRAMS",
               [("Litres", "42 × 3.785 = 159 L"),
                ("Mass", "159 × 0.72 = 114.5 kg"),
                ("In pounds", "114.5 × 2.2 ≈ 252 lb"),
                ("Typical SG", "Avgas about 0.72, Jet A-1 about 0.80"),
                ("Gallons", "1 USG = 3.785 L; 1 imperial gallon = 4.546 L")],
               "kg = litres × SG"),
    2267: card("LDA 1,125 M", "RUNWAY − DISPLACEMENT; THE STOPWAY IS NOT INCLUDED",
               [("Working", "1,150 − 25 = 1,125 m"),
                ("TORA", "The full runway: 1,150 m"),
                ("ASDA", "TORA + stopway: 1,180 m"),
                ("TODA", "TORA + clearway (none given here)"),
                ("Exam trap", "The stopway counts only towards ASDA")],
               "LDA = runway length − displaced threshold"),
    2290: card("STALL SPEED 57 KIAS", "FIGURE 1-21: HALFWAY BETWEEN 2,400 AND 2,200 LB",
               [("Flaps 40°, 60° bank", "2,400 lb: 60 KIAS; 2,200 lb: 54 KIAS"),
                ("Working", "(60 + 54) ÷ 2 = 57 KIAS"),
                ("Bank", "60° = 2 G: stall speed × √2 = × 1.41"),
                ("Flap and weight", "More flap or less weight: a lower stall speed"),
                ("Table conditions", "Power off")]),
    2291: card("77 KIAS WITH FLAPS 40° IS 78 KCAS", "INTERPOLATE FIGURE 1-19",
               [("Flaps 40° row", "70 KIAS → 71 KCAS; 80 → 81"),
                ("Working", "71 + 0.7 × 10 = 78 KCAS"),
                ("IAS to CAS", "Corrects the instrument and position errors"),
                ("Here", "CAS is about 1 kt above IAS"),
                ("Next step", "CAS corrected for altitude and temperature gives TAS")],
               "CAS = lower + fraction of the way × difference"),
    2300: card("AQUAPLANING IS MORE LIKELY AT HIGH GROUNDSPEED", "THE TYRE CANNOT PUSH THE WATER AWAY IN TIME",
               [("Also", "Standing water, low tyre pressure, worn tread"),
                ("Example", "Tyre at 36 psi: 9 × √36 = 54 kt"),
                ("Types", "Dynamic (standing water), viscous (thin film), reverted rubber (locked wheel)"),
                ("Signs", "Braking and steering stop working"),
                ("Action", "Firm touchdown, gentle braking as speed falls")],
               "Aquaplaning speed ≈ 9 × √(tyre pressure, psi) kt"),
    2320: card("GROUND ROLL 1,500 FT", "FIGURE 1-22, THEN THE TAILWIND NOTE",
               [("3,500 ft, +20°C", "(1,190 + 1,310) ÷ 2 = 1,250 ft"),
                ("4 kt tailwind", "+20%: 1,250 × 1.2 = 1,500 ft"),
                ("Tailwind note", "Add 10% for each 2 kt"),
                ("Ground roll", "Brake release to lift-off (not to 50 ft)"),
                ("Lesson", "Even a light tailwind costs a lot of runway: take off into wind")],
               "Ground roll × (1 + 0.10 for each 2 kt of tailwind)"),
    2332: card("TOTAL FUEL 19.4 USG", "TAXI AND CLIMB + TRIP + RESERVE",
               [("Time", "107 ÷ 92 = 1.163 h (69.8 min)"),
                ("Trip", "1.163 × 7.2 = 8.4 USG"),
                ("Taxi, take-off, climb", "3 USG"),
                ("Reserve", "8 USG"),
                ("Total", "3 + 8.4 + 8 = 19.4 USG")],
               "Total fuel = taxi and climb + trip + reserve"),
    2337: card("TAS 121 KT", "FIGURE 1-23 AT 2,600 RPM, HALFWAY BETWEEN ROWS",
               [("6,000 ft / 8,000 ft", "123 / 119 KTAS"),
                ("7,000 ft", "(123 + 119) ÷ 2 = 121 KTAS"),
                ("Same row", "Also gives % power and fuel flow"),
                ("Trend", "At 2,600 RPM the TAS falls with height: less power")],
               "Midway value = (lower + upper) ÷ 2"),
    2342: card("VX: BEST ANGLE OF CLIMB", "MOST HEIGHT FOR THE DISTANCE: CLEARS OBSTACLES",
               [("VY", "Best rate: most height per minute"),
                ("Which is slower", "VX is lower than VY"),
                ("Use VX", "Short field, obstacle after the runway"),
                ("Use VY", "Normal climb to cruising level"),
                ("With height", "VX rises and VY falls; they meet at the absolute ceiling")]),
    2355: card("MOMENT = WEIGHT × ARM", "THE TURNING EFFECT ABOUT THE DATUM",
               [("Arm", "Distance from the datum: aft positive, forward negative"),
                ("Datum", "The manufacturer's reference point, such as the firewall"),
                ("Example", "100 lb at 40 in = 4,000 lb-in"),
                ("CG", "Total moment ÷ total weight"),
                ("Exam trap", "Multiply, never divide, to get a moment")],
               "CG = total moment ÷ total weight"),
    2363: card("TOUCH DOWN BEYOND THE HEAVY AIRCRAFT'S TOUCHDOWN POINT", "ITS WAKE ENDS WHERE IT TOUCHED DOWN",
               [("On the approach", "Stay above its flight path"),
                ("Landing after it took off", "Touch down before its rotation point"),
                ("Taking off after it", "Lift off before its rotation point and climb above its path"),
                ("Vortices", "Sink about 300–500 ft/min and level off 500–900 ft below its path"),
                ("Light crosswind", "About 5 kt can hold a vortex over the runway")]),
}

TRIAL = [2240, 2244, 2247, 2250, 2254, 2255, 2264, 2265, 2267, 2290, 2291, 2300, 2320, 2332, 2337, 2342, 2355, 2363]
assert set(CARDS) == set(TRIAL)
