"""KEY FACT cards for the Human Performance questions. Each headline states the answer to its own question; the
subline gives the reason and the blocks the contrast or rule worth remembering. Facts as in the JAA PPL Human
Performance manual (checked 2026-10-08, see data/question-audit/human-performance-audit-2026-10-08.md).
"""
import json


def card(headline, subline, blocks=(), kicker="KEY FACT"):
    d = {"kicker": kicker, "headline": headline, "subline": subline}
    if blocks:
        d["blocks"] = [{"label": a, "value": b} for a, b in blocks]
    return json.dumps(d, ensure_ascii=False)


G = ("Positive G", "Blood drains from the head: grey-out, then black-out, then G-LOC")
NEG_G = ("Negative G", "Blood forced into the head: red-out")
PP = ("Partial pressure", "Oxygen stays 21% of the air; its pressure falls with altitude")
CO2 = ("Breathing control", "Set by the carbon dioxide level in the blood")
HYPERV = ("Hyperventilation", "Too much CO₂ blown off: tingling, dizziness")
DCS = ("Decompression sickness", "Bends: joints · Creeps: skin · Chokes: lungs · Staggers: brain")
BEHAVIOUR = ("Behaviour types", "Skill: automatic · Rule: stored procedure · Knowledge: conscious reasoning")
JUDGE = ("Judgement", "Perceptual: experience and patterns · Cognitive: conscious reasoning")
MEMORY = ("Long-term memory", "Semantic: facts · Episodic: events · Procedural: skills")
ATTITUDES = ("Hazardous attitudes", "Anti-authority, impulsivity, invulnerability, macho, resignation")
STRESS = ("Stress", "Felt when the perceived demand exceeds the perceived ability to cope")
SLEEP = ("Sleep", "REM: mental rejuvenation · Slow-wave: physical rejuvenation")
CIRC = ("Body clock", "Free-runs at about 25 h, so delaying sleep (westward) is easier")
RODS = ("Rods", "Low-light and peripheral vision, none in the fovea")
CONES = ("Cones", "Colour and detail, packed in the fovea, poor in dim light")
RUNWAY = ("Approach illusions", "Looks too high → flies low: upslope, narrow, black hole · "
                                "Looks too low → flies high: downslope, wide")
EAR = ("Ear", "Outer: pinna, canal · Middle: eardrum, ossicles · Inner: cochlea, vestibular apparatus")
VEST = ("Vestibular apparatus", "Semicircular canals: angular acceleration · Otoliths: linear acceleration, gravity")
HEART = ("Heart", "Atria receive blood, ventricles pump it out; left ventricle to the body")
BLOOD = ("Blood", "Red cells: oxygen · White cells: infection · Platelets: clotting")
BP = ("Blood pressure", "Systolic: higher, heart contracting · Diastolic: lower, heart relaxing")
CO = ("Carbon monoxide", "Colourless, odourless, binds to haemoglobin far more readily than oxygen")

CARDS = {
    # ------------------------------------------------------------------ acceleration
    2049: card("NEGATIVE G CAUSES RED-OUT", "BLOOD IS FORCED UP INTO THE HEAD AND EYES", [G]),
    2110: card("SUSTAINED POSITIVE G: GREY-OUT, THEN BLACK-OUT", "BLOOD DRAINS AWAY FROM THE EYES AND BRAIN", [NEG_G]),
    2128: card("NEGATIVE G FORCES BLOOD INTO THE HEAD AND EYES", "THE RAISED PRESSURE IN THE EYES GIVES RED-OUT", [G]),
    2162: card("POSITIVE G DRAINS BLOOD FROM THE HEAD", "THE EYES FAIL FIRST: GREY-OUT, BLACK-OUT, THEN G-LOC",
               [("Help", "Ease the back pressure; tense the legs and stomach")]),
    2207: card("60° OF BANK GIVES 2 G", "LOAD FACTOR = 1 ÷ COS(BANK)",
               [("Working", "cos 60° = 0.5, so 1 ÷ 0.5 = 2"), ("Others", "30° ≈ 1.15 G · 45° ≈ 1.41 G · 75° ≈ 3.9 G")]),

    # ------------------------------------------------------------------ airmanship
    2180: card("THE PILOT-IN-COMMAND IS RESPONSIBLE", "ATC, INSTRUCTORS AND PASSENGERS ONLY ADVISE"),
    2181: card("A HIGHLY DEVELOPED SENSE OF RESPONSIBILITY", "KNOW YOUR LIMITS AND PUT SAFETY FIRST"),
    2229: card("ASK ATC TO STAND BY AND FINISH THE CHECKS", "THEN RECHECK THE LAST ITEMS",
               [("A clearance", "Is permission to go, not an order to skip checks")]),
    2231: card("SITTING TOO LOW HIDES THE UNDERSHOOT AREA", "THE NOSE AND PANEL BLOCK THE NEAR APPROACH",
               [("Fix", "Set the seat to the design eye position")]),
    2232: card("RESTART AT LEAST ONE ITEM BEFORE THE INTERRUPTION", "MEMORY OF WHERE YOU STOPPED IS UNRELIABLE"),
    2233: card("SHAPE AND MATERIAL ALONE ARE NOT ENOUGH", "CONTROLS NEED STANDARD LOCATION, MOVEMENT AND FEEL",
               [("Good design", "Easy to reach; different functions look and feel different")]),
    2234: card("TAKE TIME TO FIND THE CORRECT CHECKLIST", "NEVER MEMORY OR ANOTHER TYPE'S LIST"),
    2235: card("SITTING TOO HIGH: ALL THREE EFFECTS", "BETTER VIEW DOWN, WORSE INSTRUMENT VIEW, LESS VIEW UP",
               [("Fix", "Set the seat to the design eye position")]),
    2236: card("ANALOGUE SHOWS TREND AND RATE OF CHANGE", "DIGITAL SHOWS AN EXACT VALUE",
               [("Analogue", "Pointer position and movement read at a glance")]),
    2237: card("THE MAGNETIC COMPASS IS NOT IN THE T", "ASI LEFT, ATTITUDE CENTRE, ALTIMETER RIGHT, HEADING BELOW"),
    2238: card("CHECKING DILIGENTLY AND EFFICIENTLY IS NOT AN ERROR", "IT IS WHAT THE CHECKLIST IS FOR",
               [("Errors", "Responding without checking, missed items, working too slowly")]),
    2785: card("AWARENESS, GOOD DECISIONS, SELF-DISCIPLINE", "AND THE DRIVE TO KEEP IMPROVING",
               [("Not", "Just checklists, natural talent or aerobatic skill")]),
    2786: card("EXCESSIVE AUTHORITARIAN BEHAVIOUR", "IT STOPS OTHERS SPEAKING UP",
               [("Other barriers", "Impulsiveness, aggression, arrogance, resignation")]),
    2787: card("END WITH QUESTIONS AND ANSWERS", "TO CHECK THE BRIEFING WAS UNDERSTOOD",
               [("Keep it", "Short and relevant to the flight")]),
    2788: card("FUEL GRADE AND AMOUNT, FIRE SAFETY, FILLER CAPS", "THE PIC CHECKS ALL THREE WHEN REFUELLING"),
    2789: card("ABOUT 70–75% OF ACCIDENTS", "ARE PUT DOWN TO HUMAN ERROR (OFTEN QUOTED AS 73%)"),
    2790: card("CONTROLLED FLIGHT INTO TERRAIN", "A SERVICEABLE AIRCRAFT FLOWN INTO THE GROUND",
               [("Cause", "Lost awareness of where the terrain is")]),
    2791: card("LOSS OF DIRECTIONAL CONTROL", "THE MOST COMMON PILOT-INDUCED CAUSE",
               [("Then", "Poor judgement, airspeed, planning, ground clearance")]),
    2792: card("INTERMEDIATE AND FINAL APPROACH", "THE MOST ACCIDENT-PRONE PHASE",
               [("Then", "Landing, take-off, descent; cruise has few")]),
    2793: card("PATTER: AN INSTRUCTOR'S STANDARD TEACHING WORDS", "NOT RADIO PHRASEOLOGY"),

    # ------------------------------------------------------------------ atmosphere, respiration, hypoxia
    2040: card("LESS OXYGEN AVAILABLE AT ALTITUDE", "CARBON MONOXIDE THEN HAS A BIGGER EFFECT", [CO, PP]),
    2043: card("CYANOSIS IS A SIGN OF HYPOXIA", "BLUISH LIPS AND FINGERNAILS FROM POORLY OXYGENATED BLOOD"),
    2046: card("NITROGEN IS THE LARGEST PART", "78% NITROGEN, 21% OXYGEN, 1% OTHER GASES"),
    2053: card("REDUCED MENTAL PERFORMANCE AND JUDGEMENT", "OFTEN WITH EUPHORIA, SO IT GOES UNNOTICED",
               [("Defence", "Know the symptoms; use oxygen above 10,000 ft")]),
    2057: card("STAY LOW ENOUGH OR USE SUPPLEMENTARY OXYGEN", "KEEP THE OXYGEN PARTIAL PRESSURE ADEQUATE",
               [("Rule of thumb", "Below about 10,000 ft without oxygen")]),
    2058: card("CARBON DIOXIDE CAN BE STORED IN LARGER AMOUNTS", "THE BODY HAS ALMOST NO OXYGEN RESERVE", [CO2]),
    2060: card("THE BREATHING RATE INCREASES", "TO BLOW OFF THE EXTRA CARBON DIOXIDE", [CO2]),
    2061: card("THE PERCENTAGES STAY ABOUT CONSTANT", "78% NITROGEN, 21% OXYGEN AT ALL HEIGHTS FLOWN", [PP]),
    2067: card("BLUE OR BLUISH LIPS AND FINGERNAILS", "CYANOSIS: BLOOD SHORT OF OXYGEN"),
    2083: card("TOO LITTLE WORKING HAEMOGLOBIN", "THE BLOOD CANNOT CARRY ENOUGH OXYGEN",
               [("Causes", "Anaemia, blood loss, carbon monoxide"), ("Hypoxic hypoxia", "Low oxygen pressure in the air")]),
    2084: card("ALVEOLI: WHERE GASES CROSS INTO AND OUT OF THE BLOOD", "OXYGEN IN, CARBON DIOXIDE OUT",
               [("They are", "Tiny air sacs at the ends of the airways")]),
    2086: card("ABOUT 21% OXYGEN", "THE SAME SHARE AT EVERY ALTITUDE", [PP]),
    2093: card("PHYSICAL ACTIVITY SHORTENS TUC", "IT USES THE OXYGEN UP FASTER"),
    2098: card("TUC: TIME TO RECOGNISE HYPOXIA AND ACT", "BEFORE PERFORMANCE IS SERIOUSLY IMPAIRED",
               [("Shorter", "Higher up, after rapid decompression, with activity")]),
    2101: card("TOO LITTLE OXYGEN PRESSURE IN THE AIR BREATHED", "HYPOXIC HYPOXIA: THE ALTITUDE TYPE", [PP]),
    2117: card("OXYGEN PARTIAL PRESSURE DECREASES", "TOTAL PRESSURE FALLS; OXYGEN STAYS 21%"),
    2123: card("BREATHING FASTER OR DEEPER THAN NEEDED", "CARBON DIOXIDE IS BLOWN OFF TOO QUICKLY",
               [("Symptoms", "Tingling, dizziness, visual disturbance")]),
    2124: card("CARBON DIOXIDE BECOMES ABNORMALLY LOW", "MORE IS BREATHED OUT THAN THE BODY MAKES"),
    2135: card("ABOUT 78% NITROGEN", "21% OXYGEN, 1% OTHER GASES"),
    2137: card("LESS OXYGEN IN EACH BREATH", "THE AIR IS THINNER; OXYGEN IS STILL 21% OF IT"),
    2138: card("LESS OXYGEN CROSSES INTO THE BLOOD", "A SMALLER PRESSURE DIFFERENCE DRIVES IT"),
    2145: card("ABOUT 2 TO 3 MINUTES AT 25,000 FT", "RAPID DECOMPRESSION SHORTENS TUC",
               [("TUC falls", "With height, activity and rapid decompression")]),
    2146: card("ALCOHOL, SOME DRUGS AND SMOKING", "THEY REDUCE TOLERANCE TO ALTITUDE",
               [("Smokers", "Hypoxic about 4,000–5,000 ft lower")]),
    2147: card("TINGLING IN FINGERS, TOES OR AROUND THE LIPS", "A SIGN OF HYPERVENTILATION",
               [("Also", "Dizziness, visual disturbance, feeling unreal")]),
    2148: card("SLOW THE BREATHING; USE OXYGEN IF IT COULD BE HYPOXIA", "THE SYMPTOMS ARE HARD TO TELL APART"),
    2173: card("THE CARBON DIOXIDE LEVEL IN THE BLOOD", "SETS THE NORMAL BREATHING RATE, NOT OXYGEN"),
    2177: card("THE OXYGEN PRESSURE DIFFERENCE", "BETWEEN THE ALVEOLI AND THE BLOOD DRIVES DIFFUSION"),
    2178: card("MORE OXYGEN CROSSES INTO THE BLOOD", "A BIGGER PRESSURE DIFFERENCE DRIVES IT",
               [("Why oxygen works", "It raises the partial pressure in the lungs")]),
    2182: card("HALF THE SEA-LEVEL PRESSURE AT ABOUT 18,000 FT", "PRESSURE FALLS FASTEST LOW DOWN",
               [("Fractions", "8,000 ft: ¾ · 18,000 ft: ½ · 36,000 ft: ¼")]),
    2183: card("UP TO ABOUT 10,000 FT", "A HEALTHY PERSON NEEDS NO EXTRA OXYGEN BELOW THIS"),
    2184: card("78% NITROGEN, 21% OXYGEN, 1% OTHER", "MOSTLY ARGON, A LITTLE CARBON DIOXIDE"),
    2185: card("ABOUT ONE-QUARTER AT 36,000 FT", "PRESSURE FALLS FASTEST LOW DOWN",
               [("Fractions", "8,000 ft: ¾ · 18,000 ft: ½ · 36,000 ft: ¼")]),
    2186: card("A SMOKER IS HYPOXIC AT A LOWER ALTITUDE", "ABOUT 4,000–5,000 FT LOWER",
               [("Why", "Carbon monoxide from smoke ties up haemoglobin")]),
    2190: card("TOO LITTLE OXYGEN FOR THE BODY'S NEEDS", "WHATEVER THE CAUSE",
               [("At altitude", "Usually hypoxic hypoxia: low oxygen pressure")]),
    2800: card("THE TROPOSPHERE REACHES ABOUT 11 KM (36,000 FT)", "IT HOLDS NEARLY ALL THE WEATHER",
               [("Above it", "The stratosphere")]),

    # ------------------------------------------------------------------ blood and circulation
    2047: card("WHITE BLOOD CELLS FIGHT INFECTION", "THEY ARE THE BODY'S IMMUNE DEFENCE", [BLOOD]),
    2054: card("PERSISTENTLY HIGH BLOOD PRESSURE IS HYPERTENSION", "HYPO- MEANS LOW: HYPOTENSION",
               [("Risk", "Weakened vessels, stroke")]),
    2062: card("THE LOWER READING IS DIASTOLIC", "MEASURED WHILE THE HEART RELAXES", [BP]),
    2073: card("THE LEFT AND RIGHT VENTRICLES", "PUMP BLOOD OUT OF THE HEART", [HEART]),
    2078: card("A BRIEF DROP IN BLOOD FLOW TO THE BRAIN", "CONSCIOUSNESS RETURNS WHEN LYING FLAT"),
    2082: card("DIZZINESS OR FAINTING", "LOW BLOOD PRESSURE STARVES THE BRAIN, ESPECIALLY ON STANDING"),
    2087: card("PLATELETS FORM CLOTS", "THEY SEAL DAMAGED VESSELS", [BLOOD]),
    2097: card("PULSE RATE: HEARTBEATS PER MINUTE", "BLOOD PRESSURE IS THE FORCE, PULSE THE FREQUENCY"),
    2104: card("THE HIGHER READING IS SYSTOLIC", "MEASURED AS THE VENTRICLES CONTRACT", [BP]),
    2121: card("HAEMOGLOBIN CARRIES OXYGEN TO THE TISSUES", "PICKED UP IN THE LUNGS, RELEASED IN THE BODY",
               [("Too little", "Anaemia")]),
    2122: card("A BLUISH TINGE: CYANOSIS", "POORLY OXYGENATED BLOOD LOSES ITS RED COLOUR"),
    2136: card("THE FORCE OF BLOOD ON THE ARTERY WALLS", "WRITTEN AS SYSTOLIC OVER DIASTOLIC", [BP]),
    2139: card("WELL-OXYGENATED BLOOD IS BRIGHT RED", "POORLY OXYGENATED BLOOD LOOKS BLUISH"),
    2140: card("TOO LITTLE HAEMOGLOBIN IS ANAEMIA", "IT LIMITS HOW MUCH OXYGEN THE BLOOD CARRIES",
               [("Leads to", "Anaemic hypoxia")]),
    2142: card("MISSING MEALS OR NOT EATING REGULARLY", "THE BLOOD SUGAR RUNS LOW",
               [("Symptoms", "Weakness, shaking, sweating, poor concentration")]),
    2143: card("GIVE FAST-ACTING SUGAR AND WATCH THEM", "ONLY IF THE PERSON IS CONSCIOUS",
               [("Unconscious", "Nothing by mouth; get medical help")]),
    2174: card("THE LEFT VENTRICLE", "PUMPS OXYGEN-RICH BLOOD TO THE WHOLE BODY", [HEART]),
    2188: card("THE CIRCULATORY SYSTEM", "THE HEART AND BLOOD VESSELS",
               [("Respiratory system", "Does the gas exchange in the lungs")]),
    2189: card("RED BLOOD CELLS CARRY OXYGEN", "THEIR HAEMOGLOBIN BINDS IT IN THE LUNGS", [BLOOD]),

    # ------------------------------------------------------------------ carbon monoxide
    2111: card("HEADACHE AND NAUSEA", "OFTEN WITH DIZZINESS; EASY TO MISTAKE FOR TIREDNESS",
               [("Suspect", "When the cabin heater is on")]),
    2113: card("COLOURLESS, ODOURLESS, BINDS TO HAEMOGLOBIN", "NO WARNING, AND IT BLOCKS OXYGEN TRANSPORT",
               [("Effects", "Build up with repeated exposure")]),
    2126: card("CARBON MONOXIDE FROM THE EXHAUST OR HEATER", "A CRACKED HEAT EXCHANGER LEAKS IT INTO THE CABIN",
               [("Action", "Heat off, fresh air on, oxygen if fitted, land")]),
    2149: card("WEAKNESS OR LOSS OF MUSCLE POWER", "THE MUSCLES ARE SHORT OF OXYGEN",
               [("Action", "Heat off, fresh air on, oxygen if fitted, land")]),

    # ------------------------------------------------------------------ circadian rhythm
    2056: card("WESTWARD IS USUALLY EASIER", "DELAYING SLEEP IS EASIER THAN ADVANCING IT", [CIRC]),
    2105: card("EAST TO WEST IS EASIER", "THE DAY GETS LONGER AND SLEEP IS DELAYED", [CIRC]),
    2106: card("ABOUT 25 HOURS", "WITHOUT CLOCKS OR DAYLIGHT, THE BODY CLOCK RUNS LONG",
               [("So", "Westward travel (delaying sleep) is easier")]),
    2125: card("POOR MENTAL PERFORMANCE AND LOW ALERTNESS", "THE BODY CLOCK IS OUT OF STEP WITH LOCAL TIME",
               [("Also", "Poor sleep, slower reactions, weaker judgement")]),

    # ------------------------------------------------------------------ fitness and medical
    2090: card("AN ANGINA ATTACK", "MILD CHEST PAIN, BREATHLESSNESS, DIZZINESS, PALLOR",
               [("Severe pain and collapse", "Suspect a heart attack")]),
    2102: card("WAIT AT LEAST 72 HOURS AFTER GIVING BLOOD", "SOUTH AFRICAN GENERAL OPERATING RULES",
               [("Why", "Less blood volume and fewer red cells: risk of fainting")]),
    2141: card("SUSPECT A HEART ATTACK", "SEVERE CHEST PAIN AND COLLAPSE",
               [("Angina", "Milder, brought on by effort, eases with rest")]),
    2144: card("ANGINA: CHEST PAIN ON EFFORT, EASING WITH REST", "THE HEART MUSCLE IS BRIEFLY SHORT OF BLOOD"),
    2171: card("WAIT 24 HOURS AFTER SCUBA DIVING", "BEFORE FLYING ABOVE 8,000 FT",
               [("Why", "Nitrogen absorbed under water can bubble out: decompression sickness")]),
    2187: card("ABOUT ONE HOUR PER UNIT", "THE LIVER CLEARS ALCOHOL AT A FIXED RATE",
               [("Nothing speeds it", "Not coffee, exercise or a cold shower")]),
    2201: card("BMI = WEIGHT (KG) ÷ HEIGHT (M)²", "NO UNITS", [("Normal (JAA)", "20–25 men, 19–24 women")]),
    2202: card("IRON IS NEEDED TO MAKE HAEMOGLOBIN", "TOO LITTLE LEADS TO ANAEMIA",
               [("Principal minerals", "Calcium, phosphorus, iron")]),
    2203: card("GASTROENTERITIS: UNFIT TO FLY", "SUDDEN INCAPACITATION IS LIKELY"),
    2204: card("AN ELECTRICAL DISTURBANCE IN THE BRAIN", "A FIT CAN COME WITHOUT WARNING"),
    2205: card("A SIGNIFICANT COLD OR FLU: UNFIT TO FLY", "BLOCKED EARS AND SINUSES, DROWSY MEDICINES"),
    2206: card("BMI 22.5", "90 ÷ 2.0² = 90 ÷ 4 = 22.5", [("Formula", "Weight (kg) ÷ height (m)²")]),
    2208: card("GIVE A CLEAR, THOROUGH SAFETY BRIEFING", "IT REMOVES THE UNCERTAINTY BEHIND THE NERVES"),
    2209: card("HEART ATTACK, CIRCULATORY PROBLEMS, HYPERTENSION", "OBESITY STRAINS THE HEART AND CIRCULATION"),
    2802: card("TOO LITTLE BLOOD REACHING THE HEART MUSCLE", "NARROWED CORONARY ARTERIES",
               [("Heart attack", "Heart muscle dies from a blocked supply"), ("Stroke", "Blocked vessel in the brain")]),
    2809: card("BMI 23 IS NORMAL", "WITHIN THE NORMAL BAND FOR MEN AND WOMEN",
               [("Formula", "Weight (kg) ÷ height (m)²")]),

    # ------------------------------------------------------------------ hearing and balance
    2063: card("THE EUSTACHIAN TUBE EQUALISES MIDDLE-EAR PRESSURE", "WITH THE OUTSIDE AIR",
               [("Harder", "In the descent, or with a cold")]),
    2069: card("THE LEANS", "A SLOW, UNNOTICED ROLL, THEN A BRISK ROLL BACK TO LEVEL",
               [("Felt", "A turn the other way"), ("Cure", "Believe the instruments")]),
    2070: card("DAMAGE TO THE COCHLEA: PERMANENT HEARING LOSS", "ITS HAIR CELLS DO NOT GROW BACK"),
    2074: card("THE OSSICLES", "MALLEUS, INCUS AND STAPES CARRY VIBRATION TO THE INNER EAR"),
    2089: card("A FALSE FEELING OF PITCHING UP", "STRONG FORWARD ACCELERATION: SOMATOGRAVIC ILLUSION",
               [("Danger", "Pushing forward into the ground")]),
    2099: card("THE AUDITORY NERVE CARRIES HEARING SIGNALS", "FROM THE COCHLEA TO THE BRAIN"),
    2109: card("PRESBYCUSIS: HEARING LOSS WITH AGE", "HIGH NOTES GO FIRST"),
    2114: card("THE SEMICIRCULAR CANALS", "SENSE ANGULAR ACCELERATION IN PITCH, ROLL AND YAW", [VEST]),
    2118: card("LOOK AT AND TRUST THE INSTRUMENTS", "THE BALANCE ORGANS CANNOT SENSE A STEADY ATTITUDE"),
    2127: card("TINNITUS: RINGING OR BUZZING IN THE EARS", "WITH NO OUTSIDE SOUND"),
    2130: card("THE COCHLEA TURNS SOUND INTO NERVE SIGNALS", "ITS HAIR CELLS SENSE THE FLUID MOVING"),
    2131: card("VISION", "THE MOST IMPORTANT SENSE FOR ORIENTATION",
               [("Unreliable", "The balance organs and the 'seat of the pants'")]),
    2150: card("NOISE DAMAGES THE INNER EAR, OFTEN PERMANENTLY", "ABOVE ABOUT 90 dB",
               [("Conductive loss", "Outer or middle ear, often treatable")]),
    2151: card("CONDUCTIVE LOSS: OUTER OR MIDDLE EAR", "OFTEN TEMPORARY OR TREATABLE",
               [("Causes", "Wax, eardrum or ossicle damage")]),
    2152: card("OSSICLE DAMAGE: CONDUCTIVE HEARING LOSS", "THE SOUND PATH TO THE COCHLEA IS BROKEN"),
    2153: card("THE OTOLITH ORGANS", "SENSE LINEAR ACCELERATION AND HEAD TILT", [VEST]),
    2154: card("VERTIGO: A FALSE SENSE OF SPINNING", "YOU OR YOUR SURROUNDINGS SEEM TO ROTATE"),
    2172: card("A FALSE FEELING OF CLIMBING", "THE OTOLITHS MISREAD VERTICAL ACCELERATION AS PITCH",
               [("Cure", "Believe the instruments or the horizon")]),
    2175: card("SEMICIRCULAR CANALS AND OTOLITH ORGANS", "TOGETHER: THE VESTIBULAR APPARATUS", [VEST]),
    2198: card("OUTER, MIDDLE AND INNER EAR", "THE THREE SECTIONS OF THE EAR", [EAR]),
    2199: card("ABOUT 20 TO 20,000 Hz", "A HEALTHY YOUNG PERSON'S HEARING",
               [("Narrows", "With age and noise damage, high notes first")]),
    2200: card("ABOUT 90 dB", "CONTINUOUS NOISE ABOVE THIS DAMAGES HEARING",
               [("Protection", "Headset about −40 dB, earplugs about −20 dB")]),
    2806: card("DETECTS ANGULAR AND LINEAR ACCELERATION", "NOT A STEADY ATTITUDE OR SPEED", [VEST]),

    # ------------------------------------------------------------------ information processing
    2042: card("A MOTOR PROGRAMME: A PRACTISED SKILL", "RUN WITH LITTLE CONSCIOUS THOUGHT", [BEHAVIOUR]),
    2045: card("AN ACTION SLIP", "THE RIGHT DECISION, THE WRONG ACTION"),
    2055: card("CONSCIOUS REASONING FROM LONG-TERM MEMORY", "KNOWLEDGE-BASED: FOR UNFAMILIAR PROBLEMS", [BEHAVIOUR]),
    2079: card("SORTING INPUTS AND FOCUSING ON WHAT MATTERS", "SELECTIVE ATTENTION",
               [("Example", "Hearing your own call sign in busy radio traffic")]),
    2085: card("PERCEPTUAL JUDGEMENT", "BASED ON SKILL AND EXPERIENCE", [JUDGE]),
    2088: card("EPISODIC MEMORY", "PERSONAL EVENTS AND EXPERIENCES", [MEMORY]),
    2094: card("CHUNKING: GROUPING ITEMS INTO UNITS", "SO WORKING MEMORY HOLDS MORE",
               [("Working memory", "About 7 unrelated items")]),
    2095: card("IMPULSIVITY", "ACTING AT ONCE WITHOUT ASSESSING THE SITUATION", [ATTITUDES]),
    2100: card("RULES AND PROCEDURES FROM LONG-TERM MEMORY", "RULE-BASED BEHAVIOUR", [BEHAVIOUR]),
    2119: card("A CLOSED-LOOP SYSTEM", "FEEDBACK COMPARES THE RESULT WITH THE AIM",
               [("Open loop", "No feedback: a memorised action runs to the end")]),
    2133: card("ENVIRONMENTAL CAPTURE", "A HABIT RUNS THE TASK AND THE LAST STEP IS MISSED"),
    2165: card("A COMPLEX, CONSCIOUS THOUGHT PROCESS", "COGNITIVE JUDGEMENT", [JUDGE]),
    2166: card("FAVOURING EVIDENCE THAT FITS WHAT YOU BELIEVE", "AND IGNORING WHAT CONFLICTS",
               [("Danger", "Staying with a bad plan too long")]),
    2167: card("A PRACTISED ACTION WITH LITTLE CONSCIOUS ATTENTION", "SKILL-BASED BEHAVIOUR", [BEHAVIOUR]),
    2168: card("GENERAL KNOWLEDGE: WORDS, FACTS, NUMBERS", "SEMANTIC MEMORY", [MEMORY]),
    2169: card("ABOUT SEVEN ITEMS (7 ± 2)", "WORKING MEMORY'S LIMIT",
               [("So", "Write down long clearances; chunk related items")]),
    2170: card("ANTI-AUTHORITY", "'THE RULES DON'T APPLY TO ME'", [ATTITUDES]),
    2176: card("IT USES FEEDBACK", "THE RESULT IS COMPARED WITH THE AIM AND CORRECTED",
               [("Example", "Easing off the roll as the bank angle is reached")]),
    2179: card("EXPERIENCE AND FAMILIAR PATTERNS", "PERCEPTUAL JUDGEMENT", [JUDGE]),
    2210: card("INSTINCTIVE RESPONSES WITHOUT TRAINING", "UNCONDITIONED REFLEXES: THE FASTEST REACTIONS",
               [("Examples", "Blinking, pulling away from heat")]),
    2211: card("PERCEPTION GIVES SENSATIONS MEANING", "IT BUILDS THE MENTAL PICTURE YOU DECIDE ON"),
    2212: card("SEMANTIC, EPISODIC AND PROCEDURAL", "THE THREE FORMS OF LONG-TERM MEMORY", [MEMORY]),
    2219: card("AGGRESSIVE ASSERTIVENESS", "IT SUPPRESSES INPUT FROM OTHERS",
               [("Good leaders", "Plan ahead, stay aware, know their limits")]),
    2220: card("RESCHEDULE THE FLIGHT", "MARGINAL WEATHER AND A STRONG CROSSWIND WITH PASSENGERS",
               [("Weigh", "The risk, not the inconvenience")]),
    2221: card("MENTAL OVERLOAD DEGRADES PERFORMANCE", "ATTENTION NARROWS AND PROCEDURES ARE FORGOTTEN",
               [("Defence", "Shed and prioritise tasks early")]),
    2222: card("QUESTION IT AT ONCE, CLEARLY", "EVEN IF THE OTHER PILOT IS MORE EXPERIENCED"),
    2774: card("ABOUT ONCE IN 100 ACTIONS", "ON A SIMPLE, REPETITIVE TASK",
               [("Worse", "With stress, fatigue or low morale")]),
    2775: card("AN ERROR CHAIN: ONE ERROR LEADS TO THE NEXT", "BREAK IT AT THE FIRST LINK"),
    2776: card("OBSERVATION AND IMITATION", "WATCH THE DEMONSTRATION, THEN COPY IT"),
    2777: card("OVER-LEARNING: PRACTISING BEYOND THE MINIMUM", "BETTER RECALL, HOLDS UP UNDER STRESS"),
    2778: card("ABOUT 0.2 SECONDS", "ONE LIGHT, ONE BUTTON", [("More choices", "Longer reaction time")]),
    2779: card("FASTER BUT LESS ACCURATE", "HIGH AROUSAL", [("Performance", "Best at moderate arousal")]),
    2780: card("SOUNDS GRAB ATTENTION MORE", "BUT ARE ANSWERED IN ERROR MORE OFTEN"),
    2781: card("AN ERROR OF COMMISSION", "A PREPARED RESPONSE FIRED BY THE WRONG TRIGGER"),
    2782: card("PROBABILITY AND IMPACT", "HOW LIKELY, AND HOW BAD IF IT HAPPENS"),
    2783: card("DIAGNOSE THE PROBLEM AND DEFINE THE OBJECTIVE", "THE FIRST STEP OF A DECISION",
               [("Then", "Collect information, assess risk, compare options, act, review")]),
    2784: card("CHANGE THE ACTION", "DON'T PERSIST WITH A DECISION YOU KNOW IS WRONG"),

    # ------------------------------------------------------------------ motion sickness
    2080: card("CONFLICTING OR EXCESSIVE BALANCE-ORGAN SIGNALS", "THE EARS FEEL MOTION THE EYES DON'T SEE"),
    2092: card("PALE SKIN, NAUSEA AND SWEATING", "THE TYPICAL SIGNS OF MOTION SICKNESS"),
    2155: card("LOOK AT THE HORIZON; SUPPORT OR RECLINE THE HEAD", "THE EYES THEN AGREE WITH THE EARS",
               [("Avoid", "Reading, head movements, stuffy cabins")]),
    2807: card("A MISMATCH BETWEEN EYES AND BALANCE ORGANS", "MOTION SICKNESS"),
    2808: card("NAUSEA, HYPERVENTILATION, PALLOR, COLD SWEAT", "ITEMS i, iii, iv AND vi",
               [("Not", "Hypoxia or stomach cramp")]),

    # ------------------------------------------------------------------ pressure effects
    2048: card("THE CREEPS", "NITROGEN BUBBLES IN THE SKIN", [DCS]),
    2051: card("THE GAS EXPANDS", "BOYLE'S LAW: LOWER PRESSURE, BIGGER VOLUME",
               [("In the body", "Trapped gas in ears, sinuses and gut expands in the climb")]),
    2064: card("TOTAL PRESSURE = SUM OF THE PARTIAL PRESSURES", "DALTON'S LAW", [PP]),
    2068: card("IN THE DESCENT", "RISING OUTSIDE PRESSURE CANNOT REACH THE BLOCKED SINUS"),
    2107: card("THE BENDS", "NITROGEN BUBBLES IN THE JOINTS", [DCS]),
    2160: card("THE VALSALVA MANOEUVRE EQUALISES THE MIDDLE EAR", "PINCH THE NOSE AND BLOW GENTLY",
               [("Needed most", "In the descent")]),
    2161: card("THE CHOKES", "NITROGEN BUBBLES IN THE LUNGS", [DCS]),

    # ------------------------------------------------------------------ stress, fatigue, sleep
    2041: card("RESTFUL, NATURAL SLEEP", "THE CURE FOR ACUTE STRESS",
               [("Not", "Alcohol or sleeping tablets")]),
    2044: card("A WAY OF COPING THAT IGNORES THE CAUSE", "DENIAL, AVOIDANCE, BLAMING OTHERS",
               [("Better", "Deal with the stressor itself")]),
    2065: card("ANTICIPATING A STRESSFUL EVENT", "ACUTE INSOMNIA IS SHORT-TERM",
               [("Chronic insomnia", "Long-term stress")]),
    2066: card("ANXIETY CAN CAUSE HYPERVENTILATION", "FAST BREATHING BLOWS OFF CARBON DIOXIDE", [HYPERV]),
    2075: card("LONG-TERM STRESS", "CAUSES CHRONIC INSOMNIA", [("Acute insomnia", "A coming stressful event")]),
    2076: card("REM SLEEP: MENTAL REJUVENATION", "DREAMING AND MEMORY PROCESSING", [SLEEP]),
    2077: card("SHORT-TERM STRESS IS ACUTE STRESS", "IT SETTLES WHEN THE DEMAND PASSES",
               [("Chronic stress", "Long-term, unresolved")]),
    2081: card("CHRONIC FATIGUE BUILDS UP OVER A LONG TIME", "LONG RECOVERY, AND THE CAUSES MUST BE FIXED"),
    2096: card("RESTFUL, NATURAL SLEEP", "THE CURE FOR ACUTE FATIGUE",
               [("Stimulants", "Only mask it")]),
    2112: card("NOISE, VIBRATION, TEMPERATURE, HUMIDITY", "PHYSICAL STRESSORS IN THE COCKPIT",
               [("They add up", "Over a flight")]),
    2120: card("SLOW-WAVE SLEEP: PHYSICAL REJUVENATION", "DEEP, NON-REM SLEEP", [SLEEP]),
    2163: card("LONG-TERM STRESS IS CHRONIC STRESS", "IT NEEDS ITS CAUSE DEALT WITH"),
    2164: card("REGULAR, ADEQUATE NATURAL SLEEP", "CAFFEINE AND NAPS DON'T REPLACE IT"),
    2223: card("MODERATE AROUSAL: ALERT AND EFFECTIVE", "PERFORMANCE PEAKS IN THE MIDDLE",
               [("Too low", "Bored, slow"), ("Too high", "Narrowed attention, overload")]),
    2224: card("THE STRESS MAY BE LOWER", "CONFIDENCE AND FAMILIARITY HAVE GROWN", [STRESS]),
    2225: card("STRESSORS ACCUMULATE", "SMALL ONES ADD UP TO A BIG LOAD"),
    2226: card("BOTH VERY LOW AND VERY HIGH AROUSAL HURT PERFORMANCE", "IT PEAKS AT A MODERATE LEVEL"),
    2227: card("PEOPLE REACT DIFFERENTLY TO THE SAME STRESSOR", "EXPERIENCE, HEALTH AND PREPARATION DIFFER", [STRESS]),
    2228: card("PERCEIVED DEMAND VERSUS PERCEIVED ABILITY", "THAT GAP SETS THE STRESS FELT",
               [("So", "Training and preparation reduce stress")]),
    2230: card("A STRESSOR: ANY DEMAND THAT CAN CAUSE STRESS", "STRESS IS THE RESPONSE TO IT",
               [("Examples", "Noise, heat, time pressure, conflict")]),

    # ------------------------------------------------------------------ vision
    2050: card("ABOUT 30 MINUTES", "FOR FULL DARK ADAPTATION", [("Cones", "About 7 minutes"), ("Rods", "About 30 minutes")]),
    2052: card("THE IRIS CONTROLS THE LIGHT", "IT CHANGES THE SIZE OF THE PUPIL"),
    2059: card("A CONVEX LENS CORRECTS LONG SIGHT", "THE SHORT EYEBALL FOCUSES BEHIND THE RETINA",
               [("Short sight", "Concave lens")]),
    2071: card("A CONCAVE LENS CORRECTS SHORT SIGHT", "THE LONG EYEBALL FOCUSES IN FRONT OF THE RETINA",
               [("Long sight", "Convex lens")]),
    2072: card("A WIDE RUNWAY: A HIGHER APPROACH", "IT MAKES YOU FEEL TOO LOW", [RUNWAY]),
    2091: card("EMPTY-FIELD MYOPIA", "WITH NOTHING TO LOOK AT, THE EYES FOCUS 1–2 M AWAY",
               [("Danger", "Distant traffic stays out of focus")]),
    2103: card("THE FOVEA HAS ONLY CONES", "CONES WORK POORLY IN DIM LIGHT", [RODS]),
    2108: card("AN UPSLOPING RUNWAY: A LOWER APPROACH", "IT MAKES YOU FEEL TOO HIGH", [RUNWAY]),
    2115: card("RODS: PERIPHERAL AND LOW-LIGHT VISION", "NO COLOUR", [CONES]),
    2116: card("VISUAL ACUITY: SEEING FINE DETAIL", "SHARPEST AT THE FOVEA"),
    2129: card("ACCOMMODATION: THE LENS CHANGES SHAPE TO FOCUS", "DONE BY THE CILIARY MUSCLES",
               [("Weakens", "With age and fatigue")]),
    2132: card("AUTOKINESIS: A STILL LIGHT SEEMS TO MOVE", "WHEN STARED AT IN THE DARK",
               [("Cure", "Keep the eyes moving; use other references")]),
    2134: card("THE IRIS ENLARGES THE PUPIL IN DIM LIGHT", "MORE LIGHT REACHES THE RETINA"),
    2156: card("LOOK SLIGHTLY TO ONE SIDE AT NIGHT", "THE IMAGE FALLS ON THE RODS AROUND THE FOVEA", [RODS]),
    2157: card("LESS BLOOD REACHES THE RETINA", "POSITIVE G: PERIPHERAL VISION GOES FIRST", [G]),
    2158: card("A NARROW RUNWAY: A LOWER APPROACH", "IT MAKES YOU FEEL TOO HIGH", [RUNWAY]),
    2159: card("A DOWNSLOPING RUNWAY: A HIGHER APPROACH", "IT MAKES YOU FEEL TOO LOW", [RUNWAY]),
    2191: card("SMALL AT FIRST, THEN GROWING VERY FAST", "A HEAD-ON AIRCRAFT BARELY CHANGES SIZE UNTIL LATE",
               [("So", "Keep a constant, systematic lookout")]),
    2192: card("MORE BLUE AND ULTRAVIOLET LIGHT AT ALTITUDE", "LESS ATMOSPHERE FILTERS IT",
               [("Protection", "Good-quality sunglasses")]),
    2193: card("MYOPIA: A LONG EYEBALL, CONCAVE LENS", "DISTANT OBJECTS FOCUS IN FRONT OF THE RETINA",
               [("Hypermetropia", "Short eyeball, convex lens")]),
    2194: card("THE FOVEA GIVES THE SHARPEST VISION", "IT IS PACKED WITH CONES", [RODS]),
    2195: card("ASTIGMATISM: A MISSHAPEN CORNEA", "CORRECTED WITH CYLINDRICAL LENSES"),
    2196: card("ABOUT 32 SECONDS", "3 KM AT 180 KT CLOSING",
               [("Working", "3 ÷ 1.852 = 1.62 NM; 1.62 ÷ 180 × 3,600 = 32 s")]),
    2197: card("THE RETINA", "HOLDS THE RODS AND CONES", [CONES]),
    2213: card("A PERCEPTION THAT DOESN'T MATCH REALITY", "AN ILLUSION"),
    2214: card("A SLOPING CLOUD TOP AS A FALSE HORIZON", "LEVELLING ON IT LEAVES THE WINGS BANKED",
               [("Cure", "Cross-check the attitude indicator")]),
    2215: card("HAZE MAKES OBJECTS LOOK FARTHER AWAY", "LOW CONTRAST READS AS DISTANCE",
               [("Very clear air", "Things look closer")]),
    2216: card("A LOW APPROACH THAT LANDS SHORT", "THE BLACK HOLE EFFECT MAKES YOU FEEL TOO HIGH", [RUNWAY]),
    2217: card("A SMALL RUNWAY LOOKS FARTHER AWAY", "IT FILLS LESS OF THE VIEW", [("Large runway", "Looks nearer")]),
    2218: card("A LARGE RUNWAY LOOKS NEARER", "IT FILLS MORE OF THE VIEW", [("Small runway", "Looks farther away")]),
    2794: card("CLEAR AIR MAKES THINGS LOOK CLOSER", "AFTER FLYING IN HAZE, DISTANCES ARE UNDERJUDGED",
               [("Haze", "Makes things look farther away")]),
    2795: card("BLACK HOLE: ONLY RUNWAY LIGHTS, YOU FEEL TOO HIGH", "SO THE APPROACH IS FLOWN LOW AND SHORT", [RUNWAY]),
    2796: card("WHITE OUT: SNOW HIDES ALL TERRAIN FEATURES", "HEIGHT, DEPTH AND SLOPE CAN'T BE JUDGED"),
    2797: card("A NARROW RUNWAY: FEELS TOO HIGH, FLIES LOW", "USED TO A 150 FT (46 M) WIDE RUNWAY", [RUNWAY]),
    2798: card("VERTICAL SEPARATION IS HARD TO JUDGE BY EYE", "AN AIRCRAFT THAT LOOKS HIGHER MAY PASS BELOW",
               [("So", "Take avoiding action on any collision risk")]),
    2799: card("NO SURFACE FEATURES TO JUDGE HEIGHT BY", "SMOOTH WATER GIVES NO TEXTURE OR SHADOW"),
}
