"""Human Performance trial set: fuller KEY FACT cards, 2026-10-09.

The user asked for more meat on the thin trial cards, to the standard of the Aircraft Technical cards
(atg_trial_cards.py). Headlines and sublines stay; each card gets four or five points: how it works, the numbers,
the exam trap, what the pilot does. Explanations are unchanged.
"""
import json


def card(headline, subline, blocks, formula=None):
    d = {"kicker": "KEY FACT", "headline": headline, "subline": subline,
         "blocks": [{"label": a, "value": b} for a, b in blocks]}
    if formula:
        d["formula"] = formula
    return json.dumps(d, ensure_ascii=False)


CARDS = {
    2043: card("CYANOSIS IS A SIGN OF HYPOXIA", "BLUISH LIPS AND FINGERNAILS FROM POORLY OXYGENATED BLOOD",
               [("Other signs", "Faster breathing, tingling, blurred vision, slow thinking"),
                ("The danger", "Judgement goes first, often with a feeling of well-being"),
                ("Hard to see", "In a dim cockpit: don't wait for blue lips"),
                ("Action", "Oxygen on, or descend"),
                ("Exam trap", "Hyperventilation also tingles, but the lips don't turn blue")]),
    2046: card("NITROGEN IS THE LARGEST PART", "78% NITROGEN, 21% OXYGEN, 1% OTHER GASES",
               [("As you climb", "The 21% oxygen stays the same"),
                ("What falls", "The total pressure, so the oxygen partial pressure"),
                ("Hypoxia", "Comes from the lower partial pressure, not a smaller percentage"),
                ("Nitrogen", "Not used by the body, but dissolves in the tissues (decompression sickness)")]),
    2047: card("WHITE BLOOD CELLS FIGHT INFECTION", "THEY ARE THE BODY'S IMMUNE DEFENCE",
               [("Red cells", "Carry oxygen on haemoglobin"),
                ("White cells", "Attack bacteria and viruses"),
                ("Platelets", "Clot the blood"),
                ("Plasma", "The fluid that carries the cells, nutrients and waste"),
                ("Exam trap", "Clotting is the platelets' job, not the white cells'")]),
    2052: card("THE IRIS CONTROLS THE LIGHT", "IT CHANGES THE SIZE OF THE PUPIL",
               [("Pupil", "The opening in the iris: wide in dim light, small in bright"),
                ("Cornea", "The clear front window: does most of the focusing"),
                ("Lens", "Fine focus, changed by the ciliary muscles"),
                ("Retina", "Rods and cones turn light into nerve signals"),
                ("Optic nerve", "Carries the signals to the brain")]),
    2057: card("STAY LOW ENOUGH OR USE SUPPLEMENTARY OXYGEN", "KEEP THE OXYGEN PARTIAL PRESSURE ADEQUATE",
               [("Rule of thumb", "Below about 10,000 ft without oxygen"),
                ("Above that", "Supplementary oxygen restores the partial pressure"),
                ("Time of useful consciousness", "About 20–30 min at 18,000 ft, 3–5 min at 25,000 ft"),
                ("Smokers", "Carbon monoxide in the blood: hypoxic at lower altitudes"),
                ("Not a cure", "Breathing faster, or a paper bag (that is for hyperventilation)")]),
    2059: card("A CONVEX LENS CORRECTS LONG SIGHT", "THE SHORT EYEBALL FOCUSES BEHIND THE RETINA",
               [("Long sight", "Short eyeball: near objects blur"),
                ("Convex lens", "Thicker in the middle: bends the light in sooner"),
                ("Short sight", "Long eyeball, focuses in front: concave lens"),
                ("Presbyopia", "The lens stiffens with age: reading glasses (convex)"),
                ("Pilot", "If glasses are required, carry a spare pair")]),
    2063: card("THE EUSTACHIAN TUBE EQUALISES MIDDLE-EAR PRESSURE", "WITH THE OUTSIDE AIR",
               [("Route", "Middle ear to the back of the throat"),
                ("Climb", "Air escapes easily: rarely a problem"),
                ("Descent", "The tube resists opening: pain if the ear can't equalise"),
                ("Clear it", "Swallow, yawn, or Valsalva (pinch the nose, blow gently)"),
                ("With a cold", "Don't fly: risk of barotrauma, even a burst eardrum")]),
    2069: card("THE LEANS", "A SLOW, UNNOTICED ROLL, THEN A BRISK ROLL BACK TO LEVEL",
               [("Cause", "The roll was too slow for the semicircular canals to sense"),
                ("Felt", "Level while banked, then a turn the other way after levelling"),
                ("Typical reaction", "Leaning the body towards the original bank"),
                ("Danger", "In cloud it can lead into a spiral dive"),
                ("Cure", "Believe the attitude indicator")]),
    2070: card("DAMAGE TO THE COCHLEA: PERMANENT HEARING LOSS", "ITS HAIR CELLS DO NOT GROW BACK",
               [("Cochlea", "Inner ear: hair cells turn vibration into nerve signals"),
                ("Cause", "Long exposure to noise above about 90 dB"),
                ("Often treatable", "Wax, a burst eardrum or damaged ossicles (outer and middle ear)"),
                ("Protect", "Wear a headset or ear defenders"),
                ("Exam trap", "Pressure equalising is the Eustachian tube; balance is the vestibular system")]),
    2079: card("SORTING INPUTS AND FOCUSING ON WHAT MATTERS", "SELECTIVE ATTENTION",
               [("Why", "The brain decides on one thing at a time"),
                ("Example", "Hearing your own call sign in busy radio traffic"),
                ("Divided attention", "Switching rapidly between tasks, not doing them at once"),
                ("Risk", "Fixating on one thing and missing another, such as traffic"),
                ("Helps", "A set scan and clear priorities: aviate, navigate, communicate")]),
    2088: card("EPISODIC MEMORY", "PERSONAL EVENTS AND EXPERIENCES",
               [("Episodic", "Events: a particular flight, an incident"),
                ("Semantic", "Facts and meanings: V-speeds, rules"),
                ("Procedural", "Skills: flying the aircraft"),
                ("Reliability", "Episodic memory drifts: it is rebuilt each time, not replayed"),
                ("Short-term memory", "About 7 ± 2 items for 10–20 seconds")]),
    2112: card("NOISE, VIBRATION, TEMPERATURE, HUMIDITY", "PHYSICAL STRESSORS IN THE COCKPIT",
               [("Physical", "Noise, vibration, heat, cold, humidity"),
                ("Physiological", "Fatigue, hunger, illness, dehydration"),
                ("Psychological", "Workload, worries at home or about money"),
                ("They add up", "Over a flight: total stress is all the sources together"),
                ("Reduce them", "Headset, ventilation, water, rest")]),
    2119: card("A CLOSED-LOOP SYSTEM", "FEEDBACK COMPARES THE RESULT WITH THE AIM",
               [("Closed loop", "Act, see the result, correct, repeat"),
                ("Example", "Rolling into a bank: watch the horizon, ease off at the angle you want"),
                ("Open loop", "No feedback: a memorised action runs to the end"),
                ("Open-loop example", "A practised, quick skilled movement"),
                ("Exam trap", "Feedback means closed loop")]),
    2171: card("WAIT 24 HOURS AFTER SCUBA DIVING", "BEFORE FLYING ABOVE 8,000 FT",
               [("Why", "Nitrogen absorbed under water can bubble out: decompression sickness"),
                ("Pressure", "Every 10 m (33 ft) of sea water adds one atmosphere"),
                ("Up to 8,000 ft", "At least 12 hours after a dive without decompression stops"),
                ("Symptoms", "Joint pain (the bends), chest pain and coughing (the chokes), itching"),
                ("If it happens", "Oxygen, descend, land, get to a recompression chamber")]),
    2174: card("THE LEFT VENTRICLE", "PUMPS OXYGEN-RICH BLOOD TO THE WHOLE BODY",
               [("Right atrium", "Receives used blood from the body"),
                ("Right ventricle", "Pumps it to the lungs"),
                ("Left atrium", "Receives oxygen-rich blood from the lungs"),
                ("Left ventricle", "Pumps it out through the aorta: the thickest wall"),
                ("Remember", "Right side to the lungs, left side to the body")]),
    2178: card("MORE OXYGEN CROSSES INTO THE BLOOD", "A BIGGER PRESSURE DIFFERENCE DRIVES IT",
               [("Diffusion", "Oxygen moves from high to low partial pressure: lungs to blood"),
                ("In the alveoli", "About 100 mmHg at sea level, about 60 at 10,000 ft"),
                ("At altitude", "Lower pressure in the lungs, less oxygen transferred"),
                ("Why oxygen works", "It raises the partial pressure in the lungs"),
                ("Exam trap", "The 21% doesn't change with height; the pressure does")]),
    2196: card("ABOUT 32 SECONDS", "3 KM AT 180 KT CLOSING",
               [("Working", "3 ÷ 1.852 = 1.62 NM; 1.62 ÷ 180 × 3,600 = 32 s"),
                ("Reaction time", "About 12.5 s to see, recognise, decide and move"),
                ("Left to act", "About 20 s"),
                ("Collision course", "The other aircraft stays still in the windscreen, then suddenly grows"),
                ("Lookout", "Scan in sectors of about 10°, pausing on each")],
               "Time (s) = distance (NM) ÷ closing speed (kt) × 3,600"),
    2197: card("THE RETINA", "HOLDS THE RODS AND CONES",
               [("Cones", "Colour and detail, packed in the fovea, poor in dim light"),
                ("Rods", "Dim light and movement, no colour, towards the edge"),
                ("Fovea", "Sharpest vision, cones only: look straight at things by day"),
                ("Blind spot", "Where the optic nerve leaves: no rods or cones"),
                ("At night", "Look slightly off-centre so the rods see the object")]),
    2201: card("BMI = WEIGHT (KG) ÷ HEIGHT (M)²", "NO UNITS",
               [("Example", "80 kg, 1.80 m: 80 ÷ 3.24 ≈ 24.7"),
                ("Normal (JAA)", "20–25 men, 19–24 women"),
                ("Higher", "25–30 overweight, over 30 obese"),
                ("Limits", "A screening number only: it can't tell muscle from fat")],
               "BMI = kg ÷ m²"),
    2207: card("60° OF BANK GIVES 2 G", "LOAD FACTOR = 1 ÷ COS(BANK)",
               [("Working", "cos 60° = 0.5, so 1 ÷ 0.5 = 2"),
                ("Others", "30° ≈ 1.15 G · 45° ≈ 1.41 G · 75° ≈ 3.9 G"),
                ("In the seat", "You feel twice your weight"),
                ("Stall speed", "Rises with √n: at 2 G, × 1.41 (+41%)"),
                ("The body", "Grey-out from about 3 G, black-out about 4.5 G (relaxed)")]),
    2211: card("PERCEPTION GIVES SENSATIONS MEANING", "IT BUILDS THE MENTAL PICTURE YOU DECIDE ON",
               [("Sensation", "Eyes, ears, balance and touch pick up raw signals"),
                ("Perception", "Interprets them, using experience and expectation"),
                ("Decision", "Made on the mental picture, not the raw data"),
                ("Risk", "Expectation can make you see or hear what you expect"),
                ("The chain", "Sense → perceive → decide → act → feedback")]),
    2223: card("MODERATE AROUSAL: ALERT AND EFFECTIVE", "PERFORMANCE PEAKS IN THE MIDDLE",
               [("Too low", "Bored, slow to react: a long, routine cruise"),
                ("Moderate", "Alert and interested: best performance"),
                ("Too high", "Narrowed attention, overload: an emergency, bad weather"),
                ("The curve", "An upside-down U (Yerkes–Dodson)"),
                ("Complex tasks", "Peak at a lower arousal than simple ones")]),
    2224: card("THE STRESS MAY BE LOWER", "CONFIDENCE AND FAMILIARITY HAVE GROWN",
               [("Stress", "Felt when the perceived demand exceeds the perceived ability to cope"),
                ("Experience", "Raises the ability you see in yourself: same task, less stress"),
                ("Why training works", "A practised response is ready in memory"),
                ("Coping", "Fix the problem, rethink it, or calm the symptoms")]),
    2233: card("SHAPE AND MATERIAL ALONE ARE NOT ENOUGH", "CONTROLS NEED STANDARD LOCATION, MOVEMENT AND FEEL",
               [("Location", "Standard place; the important ones easiest to reach"),
                ("Movement", "Standard direction: gear lever up for gear up"),
                ("Shape", "Known by touch: a wheel-shaped gear knob, a flap-shaped flap lever"),
                ("Colour", "Throttle black, propeller blue, mixture red"),
                ("Why", "Stops the wrong control being grabbed under pressure or in the dark")]),
    2235: card("SITTING TOO HIGH: ALL THREE EFFECTS", "BETTER VIEW DOWN, WORSE INSTRUMENT VIEW, LESS VIEW UP",
               [("View down", "Better over the nose"),
                ("Instruments", "Seen at an angle; some hidden under the glareshield"),
                ("View up", "Cut off by the roof or the canopy frame"),
                ("Too low", "Poor view over the nose: worst on the approach"),
                ("Fix", "Set the seat to the design eye position (use the markers where fitted)")]),
}

TRIAL = [2043, 2046, 2047, 2052, 2057, 2059, 2063, 2069, 2070, 2079, 2088, 2112, 2119, 2171, 2174, 2178, 2196,
         2197, 2201, 2207, 2211, 2223, 2224, 2233, 2235]
assert set(CARDS) == set(TRIAL)
