"""Replacement distractors for Meteorology questions whose wrong options had been copied from other
questions (e.g. "Stratosphere" offered as a percentage), some of which made a second option correct.
Each entry: id -> (option_a, option_b, option_c, option_d). The correct answer text and letter are unchanged.
"""
M = {
    619: ("The pressure has decreased", "The pressure has increased", "The temperature has decreased", "The humidity has increased"),
    621: ("An increase in temperature will cause an increase in density", "A decrease in temperature will cause a decrease in density", "A change in temperature will have no effect on density", "An increase in temperature will cause a decrease in density"),
    622: ("Decreases with an increase in temperature", "Increases with an increase in temperature", "Is unaffected by temperature", "Is always 100% at night"),
    623: ("21%", "78%", "1%", "50%"),
    624: ("The increase of pressure with altitude", "The decrease of humidity with altitude", "Decrease in temperature with altitude", "The increase of air density with altitude"),
    625: ("The aircraft's flight level", "Pressure altitude", "Altitude above mean sea level", "The aircraft’s height above an aerodrome"),
    626: ("Zero", "Pressure altitude", "Altitude above mean sea level", "Aerodrome elevation"),
    627: ("MSL temperature is 15°C and lapse rate is 3°C/1000 ft", "MSL temperature is 15°C and lapse rate is 1.98°C/1000 ft up to 36 090 ft", "MSL pressure is 1000 hPa and MSL temperature is 10°C", "Temperature keeps falling at 1.98°C/1000 ft above 36 090 ft"),
    628: ("Produces most of the earth's weather", "Contains most of the atmosphere's water vapour", "Acts as a shield against ultraviolet rays", "Marks the boundary between the troposphere and the stratosphere"),
    629: ("An increase in pressure will cause a decrease in density", "A change in pressure will have no effect on density", "A decrease in pressure will cause an increase in density", "An increase in pressure will cause an increase in density"),
    630: ("21%", "78%", "1%", "50%"),
    632: ("Increase with an increase in humidity", "Increase with an increase in temperature", "Decrease with an increase in humidity", "Not be affected by humidity"),
    635: ("Pressure altitude", "The aircraft’s altitude above sea level", "The aircraft's height above the aerodrome", "The aircraft's flight level"),
    636: ("5 km / 16 400 ft", "18 km / 60 000 ft", "11 km / 36 090 ft", "32 km / 105 000 ft"),
    637: ("Is greatest at the poles", "Is the same at all latitudes", "Is greatest at the mid-latitudes", "Is greatest at the equator"),
    638: ("+15°C", "+10°C", "+5°C", "+20°C"),
    639: ("1°C / 1000 ft", "1.98°C / 1000 ft", "1.5°C / 1000 ft", "3°C / 1000 ft"),
    640: ("Humid air is denser than dry air", "Humidity has no effect on density", "Humid air is less dense", "Humid air is denser only at night"),
    641: ("The pressure has increased", "The temperature has increased", "The humidity has decreased", "The pressure has decreased"),
    642: ("Becomes saturated", "Reaches its highest temperature of the day", "Becomes completely dry", "Starts to rise"),
    643: ("Relative humidity falls to zero", "Air will become saturated at a constant pressure", "The pressure falls to 1013 hPa", "The air reaches its highest temperature of the day"),
    644: ("At night", "Only in winter", "During the day", "Only during thunderstorms"),
    646: ("3°C / 1000 ft", "1.98°C / 1000 ft", "1.5°C / 1000 ft", "5°C / 1000 ft"),
    647: ("Strong wind and overcast skies", "Terrestrial radiation with little or no wind on a clear night", "Rapid heating of the surface by the sun", "Unstable air rising from the surface"),
    648: ("Heat being added to the air from the ground", "The cooling of air by contact with a cold surface", "The cooling of air as it rises and expands", "The mixing of warm and cold air masses"),
    649: ("1013 grammes per cubic metre and constant with altitude", "1225 grammes per cubic metre and increases with altitude", "1.225 grammes per cubic metre", "1225 grammes per cubic metre and decreases with altitude"),
    652: ("Flows down a slope at night", "Blows from the sea during the day", "Flows up a slope during the day", "Blows from the land at night"),
    653: ("A land breeze", "A katabatic wind", "A berg wind", "A sea breeze"),
    654: ("+5°C", "+15°C", "-2°C", "+9°C"),
    655: ("The temperature falls with increase in height", "The temperature rises with increase in height", "The temperature stays constant with height", "The dew point falls with increase in height"),
    658: ("At night", "During the day", "Only in summer", "Only during frontal passage"),
    659: ("The pressure of the air", "The temperature of the air", "The wind speed", "The height of the cloud base"),
    660: ("+5°C", "-9°C", "+9°C", "+14°C"),
    661: ("Heating of the air by compression", "Radiation of heat from the earth at night", "Heating of the air by friction", "Heating of the earth's surface by the sun"),
    667: ("standing with their back to the wind in the Southern Hemisphere will have low pressure on their left", "standing with their back to the wind in the Southern Hemisphere will have low pressure on their right", "facing the wind in the Southern Hemisphere will have low pressure on their right", "standing with their back to the wind in the Southern Hemisphere will have high pressure on their right"),
    668: ("a wedge of high pressure", "an area of subsiding air", "a wedge of low pressure", "a line joining places of equal pressure"),
    670: ("the rotation of the earth", "differences in air pressure", "heating of the earth's surface", "friction with the earth's surface"),
    673: ("low layered cloud", "cloud with great vertical development", "middle-level rain cloud", "high thin cloud"),
    674: ("out of an area of high pressure and into an area of low pressure", "out of an area of low pressure and into an area of high pressure", "from cold air towards warm air only", "parallel to the isobars at the surface"),
    676: ("a temperature inversion", "A shallow environmental lapse rate", "a steep positive environmental lapse rate", "an isothermal layer"),
    686: ("cooling of the air mass from below", "subsidence of air from above", "warming of the air mass from below", "a temperature inversion developing"),
    694: ("Clear skies and smooth air", "Stratiform cloud, smooth air and poor visibility", "cumuliform clouds with rain showers", "Fog and drizzle with no vertical development"),
    697: ("the temperature is 15°C", "the dew point temperature is 15°", "the dew point temperature is 16°C", "the temperature and dew point are both 16°C"),
    703: ("smooth air is to be expected in the lee", "thunderstorms will form on the lee side", "mountain wave turbulence is to be expected", "a temperature inversion prevents any turbulence"),
    707: ("smooth air beneath the cloud", "improving visibility and calm winds", "considerable turbulence", "icing but no turbulence"),
    709: ("thunderstorms embedded in frontal clouds", "isolated air-mass thunderstorms seen in clear air", "thunderstorms in the dissipating stage", "thunderstorms visible from a distance in good visibility"),
    710: ("the altimeter will tend to under read", "the altimeter will tend to over read", "the altimeter reading will not be affected", "the aircraft will be higher than indicated"),
    711: ("a decrease in temperature with altitude", "good visibility and turbulence", "an increase in temperature with altitude", "strong convection"),
    714: ("clear skies throughout the flight", "initially drizzle from stratocumulus cloud becoming rain towards Cape Town", "thunderstorms along the whole route", "fog at Port Elizabeth clearing to clear skies at Cape Town"),
    716: ("115° (M)", "295° (T)", "050° (T)", "115° (T)"),
    718: ("to the right", "to the left", "towards the higher pressure", "upwards"),
    719: ("a wind that is changing in an anticlockwise direction", "a wind that is increasing in speed", "a wind that is changing in a clockwise direction", "a wind that is decreasing in speed"),
    720: ("a wind that is changing in a clockwise direction", "a wind that is increasing in speed", "a wind blowing from the sea", "a wind that is changing in an anticlockwise direction"),
    723: ("flying towards an area of high pressure", "flying parallel to the isobars with high pressure on the right", "flying towards an area of low pressure", "flying away from an area of low pressure"),
    726: ("widespread rising air and heavy rain", "air which is subsiding", "strong convergence at the surface", "thunderstorms and unstable air"),
    728: ("pressure gradient force", "surface heating", "centrifugal force", "coriolis force"),
    733: ("221/11", "196/12", "246/10", "221/22"),
    739: ("is generally stable", "warms as it rises", "is generally unstable", "sinks back to the surface immediately"),
    740: ("subsiding air and a high pressure system", "clear skies and stable air", "a temperature inversion at the surface", "rising air and a low pressure system with instability"),
    743: ("rising air and a low pressure system with instability", "thunderstorms and heavy showers", "Subsiding air and a high-pressure system with stable conditions", "widespread cloud and rain"),
    744: ("a katabatic wind", "an anabatic wind", "a sea breeze", "the föhn wind"),
    755: ("aerodrome elevation", "pressure altitude", "zero", "altitude above mean sea level"),
    1465: ("Strong wind, overcast sky and dry air", "Heavy rain and unstable air", "Light wind, clear sky and moist air", "Warm, dry air over a hot surface"),
    1473: ("Lapse rate", "Adiabatic cooling", "Inversion", "Insolation"),
    1476: ("Strong wind with overcast skies", "Terrestrial radiation on a clear night with light wind", "Strong daytime heating of the ground", "Unstable air with thunderstorms"),
    1479: ("The temperature to which air must be cooled to become saturated", "The temperature at which relative humidity is 50%", "The highest temperature reached during the day", "The temperature at which rain turns to snow"),
    1486: ("Liquid to gas", "Ice to water", "Ice directly to vapour", "Gas to liquid"),
    1487: ("Decrease", "Increase", "Remain the same", "Rise to 100%"),
    1493: ("Cold dry air moves over warm water", "Air cools by radiation on a clear, calm night", "Warm moist air moves over a colder surface", "Moist air is forced up a hillside"),
    1500: ("Low stratus cloud touching the ground", "Precipitation that evaporates before reaching the ground", "Streaks of lightning below a cumulonimbus", "Rain that freezes on contact with the ground"),
    1526: ("A stable air mass, light wind and clear skies", "Low humidity, a surface inversion and subsidence", "Cold air, high pressure and calm conditions", "Moisture, instability and lifting action"),
}
# Question 736 asks for "the temperature" but keys "ISA+7°C" (the chart shows +12°C at 5000 ft, 30S 15E).
Q736 = {
    "question": "With reference to the Winds and Temperatures chart on page 16 of the Meteorology Manual. The temperature at 5 000 ft at S30° E015°, expressed relative to ISA, is?",
    "options": ("ISA", "ISA+12°C", "ISA-7°C", "ISA+7°C"),
}
