"""KEY FACT cards for the Meteorology questions that have no explanation picture. The card shows on its own above
the explanation (exam-simulator.tsx, exam-results.tsx). Each headline states the answer to its own question.

usage: python3 scripts/question_audit/met_key_cards_nopic.py <before.json> <out.sql>
before.json: the rows as they are live (id, question, is_hidden, explanation_image_url, explanation_visual_template).
Writes the change record to data/content-fixes/met-key-cards-nopic-2026-10-07.json and the UPDATE to <out.sql>.
"""
import base64
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]


def card(headline, subline, blocks, kicker="KEY FACT"):
    return {"kicker": kicker, "headline": headline, "subline": subline,
            "blocks": [{"label": a, "value": b} for a, b in blocks]}


OKTAS = ("The scale", "FEW 1–2 · SCT 3–4 · BKN 5–7 · OVC 8 oktas")
CEILING = ("Ceiling", "The lowest BKN or OVC layer; FEW and SCT never count")
LOCAL = ("Time zone", "South African local time = UTC + 2")
STABLE = ("Stable air", "Layered (stratiform) cloud, smooth air, poor visibility, drizzle or steady rain")
UNSTABLE = ("Unstable air", "Heaped (cumuliform) cloud, turbulence, good visibility, showers")
ISA_LAPSE = ("ISA", "+15°C at sea level, falling about 2°C per 1,000 ft")
FOG_MIST = ("Fog", "Visibility below 1,000 m")

CARDS = {
    # Air Masses
    70: card("POLAR MARITIME AIR IS COLD, MOIST AND STABLE AT ITS SOURCE",
             "THE COLD SEA COOLS IT FROM BELOW, WHICH KEEPS IT STABLE",
             [("Polar", "Cold, from high latitudes"),
              ("Maritime", "Moist, from a long track over the sea"),
              ("Changes when", "It crosses a warmer surface: heated from below, it becomes unstable")]),
    681: card("A STABLE AIR MASS GIVES POOR SURFACE VISIBILITY",
              "NO VERTICAL MIXING, SO HAZE, SMOKE AND MOISTURE STAY NEAR THE GROUND",
              [STABLE, UNSTABLE]),
    686: card("WARMING FROM BELOW MAKES AN AIR MASS LESS STABLE",
              "THE BOTTOM LAYER BECOMES BUOYANT AND THE LAPSE RATE STEEPENS",
              [("Less stable", "Heated from below: sunny ground, a warmer sea"),
               ("More stable", "Cooled from below, subsidence, an inversion"),
               ("Result", "Cumulus, showers and turbulence")]),
    694: card("MOIST, UNSTABLE AIR GIVES CUMULIFORM CLOUD AND SHOWERS",
              "LIFTED AIR KEEPS RISING ON ITS OWN AND BUILDS CUMULUS",
              [UNSTABLE, ("Can grow into", "Towering cumulus and cumulonimbus"), STABLE]),
    695: card("STABLE AIR FORMS STRATIFORM (LAYERED) CLOUD",
              "CLOUD SPREADS SIDEWAYS INSTEAD OF BUILDING UPWARDS",
              [("Stratiform types", "Stratus, stratocumulus, altostratus, nimbostratus"),
               ("Unstable air instead", "Cumulus, towering cumulus, cumulonimbus")]),
    729: card("FORCING MOIST, UNSTABLE AIR UPWARDS BUILDS CLOUD WITH LARGE VERTICAL DEVELOPMENT",
              "ONCE LIFTED, IT KEEPS RISING ON ITS OWN",
              [("Cloud", "Cumulus growing into towering cumulus or cumulonimbus"),
               ("Expect", "Turbulence and heavy showers"),
               ("Stable air forced up", "A layer of stratiform cloud that stops when the lifting stops")]),
    1491: card("WARM AIR OVER A COLD SURFACE GIVES STRATIFORM CLOUD, SMOOTH AIR AND POOR VISIBILITY",
               "COOLED FROM BELOW, IT BECOMES MORE STABLE",
               [("Also likely", "Advection fog and drizzle"),
                ("Opposite case", "Cold air over a warm surface: cumulus, turbulence, good visibility")]),
    1501: card("COLD AIR OVER A WARM SURFACE GIVES CUMULIFORM CLOUD, TURBULENCE AND GOOD VISIBILITY",
               "HEATED FROM BELOW, IT BECOMES UNSTABLE",
               [("Also expect", "Showers"),
                ("Why visibility is good", "Rising air carries haze and smoke away from the surface"),
                ("Opposite case", "Warm air over a cold surface: layered cloud, smooth air, poor visibility")]),
    # Aircraft Performance
    68: card("CARBURETTOR ICE SHOWS AS ROUGH RUNNING AND FALLING RPM",
             "ON A CONSTANT-SPEED PROPELLER, MANIFOLD PRESSURE FALLS INSTEAD",
             [("Cause", "Ice narrows the venturi and upsets the fuel/air mixture"),
              ("Action", "Full carb heat at once"),
              ("Possible", "Even at warm temperatures when the air is humid")]),
    # Clouds & Precipitation
    62: card("VIRGA IS RAIN OR SNOW THAT EVAPORATES BEFORE IT REACHES THE GROUND",
             "YOU SEE GREY STREAKS HANGING BELOW THE CLOUD BASE",
             [("Why it matters", "The evaporation cools the air, which can cause strong downdraughts and turbulence below the cloud"),
              ("Don't confuse it with", "A shower: that rain reaches the ground"),
              ("Remember", "Virga is “rain that never lands”")]),
    650: card("ON FINAL, GROUND FOG LOOKS WORSE THAN IT DID FROM OVERHEAD",
              "YOU LOOK THROUGH MUCH MORE FOG ALONG A SHALLOW SLANT",
              [("Overhead", "You look down through only the fog's depth"),
               ("On approach", "The slant path crosses a long stretch of fog"),
               ("Remember", "Fog that looks thin from above can hide the runway on final")]),
    663: card("MIST HAS VISIBILITY OF 1,000 M OR MORE",
              "MIST AND FOG ARE THE SAME DROPLETS; ONLY THE VISIBILITY DIFFERS",
              [FOG_MIST, ("Mist", "Visibility 1,000 m or more"),
               ("Haze", "Dry particles such as dust or smoke, not water droplets")]),
    664: card("FOG IS REPORTED WHEN VISIBILITY IS BELOW 1,000 M",
              "AT 1,000 M OR MORE THE SAME OBSCURATION IS MIST",
              [FOG_MIST, ("Mist", "Visibility 1,000 m or more"),
               ("In a METAR", "FG = fog, BR = mist")]),
    709: card("THUNDERSTORMS EMBEDDED IN FRONTAL CLOUD ARE THE MOST HAZARDOUS",
              "THEY ARE HIDDEN INSIDE LAYERED CLOUD, SO YOU CAN'T SEE THEM TO AVOID THEM",
              [("Isolated storms", "Usually visible from a distance and can be flown around"),
               ("Hazards inside", "Severe turbulence, hail, lightning and icing"),
               ("Where", "Unstable air lifted at a front, often an occlusion")]),
    714: card("PE TO CAPE TOWN: DRIZZLE FROM STRATOCUMULUS AT FIRST, THEN RAIN NEAR CAPE TOWN",
              "READ A SIGNIFICANT WEATHER CHART ALONG THE WHOLE ROUTE, NOT AT ONE END",
              [("Near Port Elizabeth", "Shallow stratocumulus with drizzle"),
               ("Towards Cape Town", "Deeper cloud and rain"),
               ("Method", "Follow the route line through each weather area in turn")]),
    1463: card("STEAM FOG FORMS WHEN COLD AIR MOVES OVER WARM WATER",
               "THE WARM WATER EVAPORATES INTO THE COLD AIR, WHICH SATURATES AT ONCE",
               [("Looks like", "Wisps rising off a lake or the sea, like steam"),
                ("Advection fog is the opposite", "Warm, moist air moving over a cold surface"),
                ("Radiation fog", "Ground cooling on a clear, calm night")]),
    1482: card("ALTOCUMULUS CASTELLANUS SHOWS INSTABILITY IN THE MIDDLE TROPOSPHERE",
               "TURRETS ON A MIDDLE-LEVEL CLOUD LAYER MEAN CONVECTION AT THAT LEVEL",
               [("Looks like", "Small castle-like towers on a layer of altocumulus"),
                ("Warning", "Often seen in the morning before afternoon thunderstorms")]),
    1505: card("IN HEAVY FREEZING RAIN YOU CAN'T SHED, TURN BACK OR LEAVE THE AREA AT ONCE",
               "ICE CAN BUILD UP FASTER THAN ANY DE-ICING SYSTEM CAN REMOVE IT",
               [("Why", "Each minute in it adds more ice, weight and drag"),
                ("Most light aircraft", "Have no ice protection at all"),
                ("Freezing rain means", "A warmer layer above: rain falls from it into air below 0°C")]),
    1506: card("NIMBOSTRATUS CAN GIVE MODERATE TO SEVERE AIRFRAME ICING",
               "A DEEP, WIDE LAYER OF SUPERCOOLED WATER YOU MAY BE IN FOR A LONG TIME",
               [("Why", "Deep and widespread, so the exposure is long"),
                ("Cumulonimbus", "Also severe icing, plus turbulence and hail"),
                ("Icing needs", "Visible moisture and a temperature at or below 0°C")]),
    1520: card("A SQUALL LINE FORMS AHEAD OF AN ACTIVE COLD FRONT",
               "A BAND OF THUNDERSTORMS IN THE WARM SECTOR, SEPARATE FROM THE FRONT",
               [("Brings", "Severe turbulence, hail and sudden wind shifts"),
                ("Trap", "It arrives before the front itself")]),
    1522: card("A MICROBURST IS A CONCENTRATED DOWNDRAUGHT WITH DAMAGING SURFACE OUTFLOW",
               "IT HITS THE GROUND AND SPREADS OUT IN ALL DIRECTIONS",
               [("Flying through it", "Headwind (airspeed rises), then downdraught, then tailwind (airspeed falls)"),
                ("Size", "Damaging outflow up to about 4 km across"),
                ("Danger", "Take-off and final approach, close to the ground")]),
    1523: card("A GUST FRONT IS THE COLD OUTFLOW FROM A THUNDERSTORM",
               "THE STORM'S DOWNDRAUGHT SPREADS OUT AHEAD OF IT LIKE A MINI COLD FRONT",
               [("Brings", "Sudden wind shift, gusts, turbulence, low-level wind shear"),
                ("When", "It can arrive well before the storm's rain")]),
    1527: card("HOAR FROST IS WATER VAPOUR TURNING DIRECTLY INTO ICE ON A COLD SURFACE",
               "IT SKIPS THE LIQUID STAGE (DEPOSITION)",
               [("When", "Clear, cold nights, surfaces below 0°C"),
                ("Effect", "Even a thin, sandpaper-like layer can cut lift by up to 30% and raise drag by 40%"),
                ("Before flight", "Remove all of it")]),
    1529: card("A STORMSCOPE DETECTS ELECTRICAL DISCHARGES (LIGHTNING)",
               "IT PLOTS LIGHTNING STRIKES AS DOTS ON A COCKPIT DISPLAY",
               [("Shows", "Where lightning, and so convection, is happening"),
                ("Weather radar instead", "Shows precipitation and its intensity")]),
    1539: card("A MICROBURST'S DAMAGE AREA IS UP TO ABOUT 4 KM ACROSS",
               "SMALL ENOUGH TO CROSS IN SECONDS ON FINAL APPROACH",
               [("Sequence", "Headwind, downdraught, then tailwind"),
                ("Danger", "Changes come too fast to react close to the ground")]),
    # Fronts
    712: card("AFTER A COLD FRONT PASSES, PRESSURE BEGINS TO RISE",
              "PRESSURE IS LOWEST AS THE FRONT GOES THROUGH",
              [("Ahead of it", "Pressure falls"),
               ("Behind it", "Colder, denser air: pressure rises"),
               ("Also", "Temperature drops and the wind shifts")]),
    730: card("FRONTAL FOG FORMS AHEAD OF A WARM FRONT",
              "RAIN FROM THE WARM AIR ABOVE EVAPORATES INTO THE COLD AIR BELOW",
              [("How", "The extra moisture saturates the cold surface air"),
               ("Where", "In the rain area ahead of the warm front")]),
    1464: card("A COLD FRONT NORMALLY MOVES FASTEST",
               "DENSE COLD AIR PUSHES UNDER THE WARM AIR",
               [("Warm front", "Slower: warm air only slides gently up over the cold air"),
                ("Result", "The cold front catches the warm front and forms an occlusion")]),
    # Humidity
    38: card("TEMPERATURE AND DEW POINT CLOSING TOGETHER MEANS LOW CLOUD OR FOG",
             "THE AIR IS CLOSE TO SATURATION",
             [("Small spread", "High relative humidity"),
              ("Watch", "A spread closing in the evening, as the air cools overnight")]),
    697: card("FAGG METAR 16/15: THE DEW POINT IS 15°C",
              "TEMPERATURE FIRST, DEW POINT SECOND",
              [("Temperature", "16°C"),
               ("Dew point", "15°C"),
               ("A 1°C spread", "Air close to saturation")]),
    1462: card("A SUPERCOOLED DROPLET IS LIQUID WATER BELOW 0°C",
               "IT STAYS LIQUID UNTIL SOMETHING DISTURBS IT",
               [("On impact", "It freezes on the aircraft"),
                ("Why it matters", "The main cause of airframe icing"),
                ("Found in", "Cloud from 0°C down to about −40°C")]),
    # Meteorological Reports
    79: card("A METAR IS THE ACTUAL WEATHER AT AN AERODROME",
             "WHAT WAS OBSERVED AT A STATED TIME, NOT A FORECAST",
             [("Contains", "Wind, visibility, weather, cloud, temperature/dew point, QNH"),
              ("TAF instead", "A forecast for an aerodrome")]),
    80: card("A TAF IS AN AERODROME FORECAST",
             "WHAT TO EXPECT AT ONE AERODROME OVER A SET PERIOD",
             [("Covers", "Up to 30 hours"),
              ("Contains", "Wind, visibility, weather and cloud"),
              ("METAR instead", "The actual weather now")]),
    81: card("CAVOK NEEDS 10 KM VISIBILITY, NO SIGNIFICANT WEATHER AND NO SIGNIFICANT CLOUD",
             "ALL CONDITIONS MUST BE MET AT ONCE",
             [("Visibility", "10 km or more"),
              ("Cloud", "None below 5,000 ft (or the minimum sector altitude if higher), and no CB or TCU"),
              ("Weather", "Nothing significant to aviation")]),
    82: card("FEW MEANS 1 TO 2 OKTAS",
             "1 OR 2 EIGHTHS OF THE SKY COVERED",
             [OKTAS, CEILING]),
    83: card("SCT MEANS 3 TO 4 OKTAS",
             "SCATTERED: 3 OR 4 EIGHTHS OF THE SKY COVERED",
             [OKTAS, CEILING]),
    84: card("BKN MEANS 5 TO 7 OKTAS",
             "BROKEN: 5 TO 7 EIGHTHS OF THE SKY COVERED",
             [OKTAS, CEILING]),
    85: card("OVC MEANS 8 OKTAS",
             "OVERCAST: THE WHOLE SKY COVERED",
             [OKTAS, CEILING, ("Height", "The figures after it give the base in hundreds of feet: OVC008 = 800 ft")]),
    86: card("ATIS GIVES SURFACE WIND, QNH, VISIBILITY AND THE RUNWAY IN USE",
             "A RECORDED BROADCAST OF THE CURRENT AERODROME INFORMATION",
             [("Also", "Weather, cloud, temperature and dew point"),
              ("Why", "Keeps the frequency free for live calls"),
              ("On first contact", "Report the ATIS letter you have received")]),
    679: card("FAJS: THE WIND VARIED BETWEEN 350° AND 070°",
              "350V070 MEANS VARYING CLOCKWISE FROM 350° TO 070°",
              [("V", "Separates the two extremes of direction"),
               ("Direction", "Clockwise from the first figure to the second, here through north")]),
    690: card("FADN 1800–2000 LOCAL: WIND 140/12 KT",
              "CONVERT TO UTC FIRST: 1600–1800Z, THE BECMG 1618 PERIOD",
              [LOCAL, ("14012KT", "From 140° true at 12 kt")]),
    692: card("A PARKED AIRCRAFT AFTER A CLEAR WINTER NIGHT WILL HAVE HOAR FROST",
              "THE SKIN COOLS BELOW 0°C AND VAPOUR TURNS STRAIGHT TO ICE",
              [("Why clear nights", "No cloud, so surfaces lose heat fastest"),
               ("Before flight", "Remove it all: even a thin layer cuts lift")]),
    700: card("FAPE 1300–1500 LOCAL: 3 TO 4 OKTAS AT 1,500 FT",
              "CONVERT TO UTC FIRST: 1100–1300Z, THE BECMG 1113 PERIOD",
              [LOCAL, ("SCT015", "3–4 oktas, base 1,500 ft above the aerodrome")]),
    713: card("STATION 2: PRESSURE FELL, THEN STEADY",
              "THE TENDENCY SYMBOL IS A PICTURE OF THE BAROGRAPH TRACE",
              [("Sloping down, then flat", "Falling, then steady"),
               ("Period", "The last 3 hours")]),
    715: card("STATION 5: PRESSURE FELL 3 HPA",
              "THE CHANGE IS PLOTTED IN TENTHS OF A HECTOPASCAL",
              [("30", "= 3.0 hPa"),
               ("Rise or fall", "Read from the tendency symbol next to it"),
               ("Period", "The last 3 hours")]),
    717: card("STATION 6: MODERATE INTERMITTENT DRIZZLE",
              "PRESENT WEATHER IS PLOTTED TO THE LEFT OF THE STATION CIRCLE",
              [("Don't confuse it with", "Cloud-type and pressure-tendency symbols")]),
    721: card("STATION 4: THICK ALTOSTRATUS OR NIMBOSTRATUS",
              "READ THE MIDDLE-CLOUD SYMBOL ON THE STATION MODEL",
              [("These clouds", "Extensive layers with possible continuous rain")]),
    724: card("STATION 14: VISIBILITY 200 M IN HAZE",
              "READ THE VISIBILITY CODE AND THE WEATHER SYMBOL TOGETHER",
              [("Code 02", "0.2 km = 200 m"),
               ("Symbol", "Haze")]),
    731: card("FAGM: TEMPERATURE 16°C, DEW POINT 15°C, ON THE 20TH AT 0730Z",
              "THE DATE/TIME GROUP IS DAY, THEN TIME IN UTC",
              [("16/15", "Temperature, then dew point (not maximum and minimum)"),
               ("0730Z", "0930 South African time")]),
    732: card("FAGG: LIGHT RAIN, TEMPORARILY HEAVY RAIN 1200–2000 LOCAL",
              "TEMPO 1018 IS 1000–1800 UTC",
              [("−RA / +RA", "Light rain / heavy rain"),
               LOCAL]),
    738: card("FAUP CAVOK: NO OPERATIONALLY SIGNIFICANT CLOUD BELOW 5,000 FT",
              "CAVOK ALSO MEANS 10 KM VISIBILITY AND NO SIGNIFICANT WEATHER",
              [("Cloud", "None below 5,000 ft (or the minimum sector altitude if higher), and no CB or TCU"),
               ("Visibility", "10 km or more")]),
    1504: card("A HYGROMETER MEASURES HUMIDITY",
               "A PSYCHROMETER (WET AND DRY BULB) IS ONE TYPE",
               [("Anemometer", "Wind speed"),
                ("Barometer", "Pressure"),
                ("Radiosonde", "Temperature and humidity aloft")]),
    1511: card("A GUST IS REPORTED WHEN IT IS AT LEAST 10 KT ABOVE THE MEAN WIND",
               "22015G28KT: 220° AT 15 KT, GUSTING 28 KT",
               [("Below 10 kt above the mean", "Only the mean speed is given"),
                ("G", "Marks the gust figure")]),
    1530: card("SURFACE WIND IS MEASURED ON A MAST ABOUT 10 M ABOVE THE GROUND",
               "A STANDARD HEIGHT SO REPORTS FROM DIFFERENT AERODROMES COMPARE",
               [("Why not lower", "Buildings and the ground slow and disturb the wind")]),
    1532: card("AN ANEMOMETER MEASURES WIND SPEED",
               "SPINNING CUPS OR A PROPELLER TURN FASTER IN STRONGER WIND",
               [("Wind direction", "A wind vane"),
                ("Hygrometer", "Humidity"),
                ("Ceilometer", "Cloud base")]),
    1542: card("RADIOSONDES MEASURE TEMPERATURE AND HUMIDITY ALOFT",
               "AN INSTRUMENT PACK CARRIED UP BY A WEATHER BALLOON",
               [("Measures", "Pressure, temperature and humidity as it climbs"),
                ("Wind", "Worked out by tracking the balloon's drift")]),
    # Pressure
    1492: card("COLD, LOW-PRESSURE CONDITIONS PUT YOU LOWER THAN THE ALTIMETER SHOWS",
               "BOTH MAKE THE ALTIMETER OVER-READ",
               [("Low pressure", "Flying from high to low pressure, the altimeter over-reads"),
                ("Cold air", "Pressure levels are closer together, so you are lower"),
                ("Remember", "From high to low, or hot to cold, look out below")]),
    1496: card("PRESSURE ALTITUDE EQUALS DENSITY ALTITUDE AT STANDARD TEMPERATURE",
               "DENSITY ALTITUDE IS PRESSURE ALTITUDE CORRECTED FOR TEMPERATURE",
               [("Warmer than ISA", "Density altitude is higher"),
                ("Colder than ISA", "Density altitude is lower"),
                ISA_LAPSE]),
    1515: card("A STATIONARY WINTER HIGH OVER LAND OFTEN GIVES FOG AND LOW STRATUS",
               "SINKING AIR FORMS AN INVERSION; CLEAR, CALM NIGHTS COOL THE GROUND",
               [("Trapped", "Moisture and haze stay under the inversion"),
                ("Clears", "When the sun heats the ground enough to burn it off")]),
    1534: card("A THERMAL DEPRESSION FORMS OVER LAND IN SUMMER",
               "STRONG HEATING MAKES THE AIR RISE, LOWERING SURFACE PRESSURE",
               [("Also called", "A heat low"),
                ("South Africa", "Over the interior in summer, drawing moist air in from the coast")]),
    # South African Weather
    682: card("AHEAD OF A COLD FRONT, THE SOUTH-WESTERN CAPE GETS NORTH-WESTERLY WINDS",
              "AIR CIRCULATES AROUND THE APPROACHING LOW",
              [("As the front passes", "The wind shifts sharply to south-westerly"),
               ("Behind it", "Colder air, and pressure rises")]),
    741: card("POLAR MARITIME AIR OVER SOUTH AFRICA IN SUMMER BECOMES UNSTABLE",
              "THE HOT GROUND HEATS ITS LOWER LAYERS",
              [("Why", "Heating from below steepens the lapse rate"),
               ("Result", "Cumulus and showers")]),
    751: card("IN THE SOUTHERN HEMISPHERE, THE WIND BACKS AS A WARM FRONT PASSES",
              "BACKING = TURNING ANTICLOCKWISE",
              [("Northern Hemisphere", "The wind veers (turns clockwise)"),
               ("Why", "Rotation around lows and highs is reversed south of the equator")]),
    753: card("AFTER A WARM FRONT, PRESSURE KEEPS FALLING MORE SLOWLY, THEN STARTS TO RISE",
              "PRESSURE ONLY RISES STEADILY ONCE THE COLD FRONT HAS PASSED",
              [("Ahead of the warm front", "Pressure falls"),
               ("In the warm sector", "Falls more slowly"),
               ("Behind the cold front", "Pressure rises")]),
    1502: card("TROPICAL REVOLVING STORMS NEAR SOUTHERN AFRICA FORM EAST OF MADAGASCAR",
               "THEY NEED A WARM SEA: THE SOUTH-WEST INDIAN OCEAN",
               [("Not in the Atlantic", "The cold Benguela Current keeps it too cool"),
                ("Track", "Can move into the Mozambique Channel")]),
    1516: card("TROPICAL REVOLVING STORMS NEED A SEA OF ABOUT +27°C",
               "THE USUAL THRESHOLD IS 26.5°C",
               [("Also need", "Low wind shear and enough distance from the equator to spin"),
                ("Near Southern Africa", "The south-west Indian Ocean")]),
    # Stability & Lapse Rates
    52: card("UNSTABLE AIR GIVES GOOD VISIBILITY",
             "RISING AIR CARRIES HAZE AND SMOKE AWAY FROM THE SURFACE",
             [UNSTABLE, STABLE]),
    55: card("STABLE AIR GIVES POOR VISIBILITY AND STRATIFORM CLOUD",
             "NO VERTICAL MIXING, SO HAZE STAYS LOW AND CLOUD SPREADS IN LAYERS",
             [STABLE, UNSTABLE]),
    # Temperature
    35: card("FL085 AT ISA +7°C: OAT ABOUT +5°C",
             "WORK OUT ISA FOR THE LEVEL, THEN ADD THE DEVIATION",
             [ISA_LAPSE,
              ("ISA at 8,500 ft", "15 − (8.5 × 2) ≈ −2°C"),
              ("Add +7", "−2 + 7 = +5°C")]),
    660: card("FL095 WITH OAT +5°C IS ISA +9°C",
              "DEVIATION = ACTUAL TEMPERATURE − ISA TEMPERATURE",
              [ISA_LAPSE,
               ("ISA at 9,500 ft", "15 − (9.5 × 2) ≈ −4°C"),
               ("Deviation", "+5 − (−4) = +9°C")]),
    662: card("NIGHT COOLING IS GREATEST UNDER CLEAR SKIES OVER ROCK OR DESERT",
              "NO CLOUD TO TRAP THE HEAT, AND DRY GROUND STORES LITTLE OF IT",
              [("Cloud cover", "Acts like a blanket and slows the cooling"),
               ("Water", "Changes temperature very little between day and night"),
               ("Result", "A surface inversion by morning")]),
    716: card("NATAL NORTH COAST AT 5,000 FT: WIND FROM 115° TRUE",
              "WIND DIRECTIONS ON THESE CHARTS ARE ALWAYS IN DEGREES TRUE",
              [("Chart entry", "115/5, temperature +21°C"),
               ("Degrees magnetic", "Used for the surface wind given by ATC and ATIS")]),
    733: card("4,000 FT AT S25° E015°: W/V 221/11",
              "INTERPOLATE HALFWAY BETWEEN THE 3,000 FT AND 5,000 FT ROWS",
              [("3,000 ft", "246/10"),
               ("5,000 ft", "196/12"),
               ("Halfway", "221° at 11 kt")]),
    736: card("5,000 FT AT S30° E015°: ISA +7°C",
              "COMPARE THE CHART TEMPERATURE WITH ISA FOR THAT HEIGHT",
              [("Chart", "+12°C"),
               ("ISA at 5,000 ft", "15 − (5 × 2) = +5°C"),
               ("Deviation", "+12 − 5 = +7°C")]),
    # Wind
    47: card("A KATABATIC WIND FLOWS DOWNHILL, USUALLY AT NIGHT",
             "AIR ON THE SLOPE COOLS, BECOMES DENSER AND DRAINS DOWNHILL",
             [("Anabatic", "The daytime opposite: warm air flowing up the slope"),
              ("Strength", "Usually light, but can be strong down long, snow-covered slopes")]),
    66: card("THE CORIOLIS FORCE IS CAUSED BY THE EARTH'S ROTATION",
             "IT DEFLECTS MOVING AIR; IT DOESN'T START THE MOVEMENT",
             [("Southern Hemisphere", "Deflects to the left"),
              ("Starts the wind", "The pressure gradient force"),
              ("Strength", "Zero at the equator, greatest at the poles")]),
    671: card("A SOUTHERN HEMISPHERE HIGH: ANTICLOCKWISE, OUTWARDS AND DOWNWARDS",
              "SINKING AIR WARMS, SO HIGHS BRING SETTLED WEATHER",
              [("High", "Anticlockwise, flowing out at the surface, air sinking"),
               ("Low", "Clockwise, flowing in at the surface, air rising"),
               ("Northern Hemisphere", "The directions are reversed")]),
    675: card("A SOUTHERN HEMISPHERE LOW: CLOCKWISE AROUND THE LOWEST PRESSURE",
              "FRICTION TURNS THE SURFACE WIND IN ACROSS THE ISOBARS TOWARDS THE CENTRE",
              [("Low", "Clockwise, flowing in at the surface, air rising"),
               ("High", "Anticlockwise, flowing out at the surface, air sinking"),
               ("Northern Hemisphere", "The directions are reversed")]),
    720: card("BACKING MEANS THE WIND DIRECTION CHANGES ANTICLOCKWISE",
              "FOR EXAMPLE NORTH, THROUGH NORTH-WEST, TO WEST",
              [("Veering", "The opposite: a clockwise change, e.g. north to east"),
               ("Speed", "Backing and veering are about direction only")]),
    1507: card("CONVECTIVE TURBULENCE DEPENDS MAINLY ON SOLAR HEATING OF THE SURFACE",
               "HEATED GROUND MAKES THERMALS, WITH SINKING AIR BETWEEN THEM",
               [("Strongest", "Hot, sunny afternoons"),
                ("Weakest", "At night or under overcast skies")]),
    1519: card("LOW-LEVEL WIND SHEAR IS A SUDDEN CHANGE IN WIND NEAR THE GROUND",
               "SPEED OR DIRECTION CHANGES OVER A SHORT DISTANCE",
               [("Danger", "Airspeed changes suddenly at take-off and landing, with little height to recover"),
                ("Causes", "Thunderstorms, fronts, inversions, terrain")]),
    1538: card("A STRONG LOW-LEVEL INVERSION CAN CAUSE VERTICAL WIND SHEAR",
               "THE AIR ABOVE AND BELOW DOESN'T MIX",
               [("Below", "Calm or light surface wind"),
                ("Above", "Can be much stronger or from a different direction"),
                ("Watch", "Climbing or descending through the inversion")]),
}


def main():
    before = {r["id"]: r for r in json.loads(Path(sys.argv[1]).read_text())}
    assert set(before) == set(CARDS), set(CARDS) ^ set(before)
    rows = []
    for q in sorted(CARDS):
        assert not before[q]["explanation_image_url"] and not before[q]["is_hidden"], q
        rows.append({"id": q, "question": before[q]["question"], "is_hidden": before[q]["is_hidden"],
                     "why": "no picture; card added so the explanation is not text alone",
                     "before": {"explanation_visual_template": before[q]["explanation_visual_template"]},
                     "after": {"explanation_visual_template": json.dumps(CARDS[q], ensure_ascii=False)}})
    record = {"date": "2026-10-07", "subject": "meteorology",
              "change": "Added KEY FACT cards to the Meteorology questions without a picture.",
              "rows": rows}
    (REPO / "data/content-fixes/met-key-cards-nopic-2026-10-07.json").write_text(
        json.dumps(record, indent=1, ensure_ascii=False) + "\n")
    payload = json.dumps([{"id": r["id"], "t": r["after"]["explanation_visual_template"]} for r in rows],
                         ensure_ascii=False)
    Path(sys.argv[2]).write_text(
        "update questions q set explanation_visual_template = r.t from jsonb_to_recordset(convert_from(decode('"
        + base64.b64encode(payload.encode()).decode()
        + "','base64'),'UTF8')::jsonb) as r(id bigint, t text) where q.id = r.id and q.subject = 'meteorology'"
        + " and coalesce(q.explanation_image_url, '') = '' returning q.id;")
    print(len(rows), "cards")


if __name__ == "__main__":
    main()
