"""KEY FACT panels for ATG explanation images (explanation_visual_template).

Each entry: id -> (headline, subline, [(label, value), ...], formula or None).
Run this file to print the aggregate hash the database should match.
The card renders kicker "KEY FACT", the headline and subline in capitals, the blocks and an optional formula bar.
"""
KF = {
    # Undercarriage
    2418: ("NOSE-WHEEL SHIMMY IS CONTROLLED BY A SHIMMY DAMPER",
           "IT RESISTS RAPID SIDE-TO-SIDE OSCILLATION BUT STILL ALLOWS NORMAL STEERING",
           [("Shimmy", "Rapid side-to-side oscillation of the nose wheel"),
            ("Damper", "Small hydraulic piston and cylinder, or friction unit, between strut and fork"),
            ("Not the cause", "Worn torque links cause shimmy; they do not control it")], None),
    2420: ("12.00 IS THE SECTION WIDTH",
           "TYRE SIZE READS FROM THE OUTSIDE IN: DIAMETER x WIDTH - RIM",
           [("28", "Outside diameter (in)"), ("12.00", "Section width (in)"), ("10", "Bead (rim) diameter (in)")],
           "28 x 12.00 - 10 = DIAMETER x WIDTH - RIM"),
    2421: ("SEMI-MONOCOQUE: THE SKIN CARRIES SOME OF THE LOAD",
           "FORMERS AND STRINGERS GIVE SHAPE; THE STRESSED SKIN SHARES THE LOAD",
           [("Truss", "Framework carries all the load; covering carries none"),
            ("Monocoque", "Skin carries all the load"),
            ("Semi-monocoque", "Frame and skin share the load")], None),
    2424: ("TORSION IS A TWISTING LOAD",
           "E.G. A WING TWISTED BY AILERON LOADS OR CP MOVEMENT",
           [("Tension", "Stretching"), ("Compression", "Squashing"), ("Shear", "Layers sliding"),
            ("Bending", "Tension and compression together"), ("Torsion", "Twisting")], None),
    2425: ("SPLIT FLAP: ONLY THE LOWER SURFACE DEFLECTS",
           "THE UPPER SURFACE STAYS IN PLACE",
           [("Lift", "Moderate increase"), ("Drag", "Large increase: steeper approach"),
            ("Compare", "Plain hinges the whole trailing edge; slotted opens a gap; Fowler slides aft")], None),
    2427: ("AN ADJUSTABLE TRIM TAB KEEPS ITS SET ANGLE",
           "ONLY THE TRIM WHEEL MOVES IT, NOT THE CONTROL COLUMN",
           [("Elevator moved", "Tab moves with it as a fixed part of the surface"),
            ("New angle", "Only when the pilot re-trims"),
            ("Moves automatically", "That is a balance or anti-balance tab")], None),
    2428: ("SEMI-CANTILEVER: WING BRACED BY STRUTS",
           "STRUTS RUN FROM THE LOWER FUSELAGE TO THE WING",
           [("Cantilever", "Supported at the root only, all loads carried by the spars"),
            ("Semi-cantilever", "External struts share the load"),
            ("Trade-off", "Lighter spar, more drag")], None),
    2429: ("THE LONGERON IS THE MAIN LENGTHWISE MEMBER",
           "IN A TRUSS FUSELAGE THE BRACED FRAMEWORK CARRIES THE LOADS",
           [("Longerons", "Main longitudinal members, usually four"),
            ("Bracing", "Verticals and diagonals form rigid triangles"),
            ("Covering", "Carries no load")], None),
    2430: ("AILERONS AND FLAPS HINGE ON THE REAR SPAR",
           "THE REAR (AUXILIARY) SPAR RUNS ALONG THE BACK OF THE WING",
           [("Main spar", "Carries most of the bending load"),
            ("Rear spar", "Hinge points for the trailing-edge surfaces"),
            ("Leading edge", "Slats or de-icing boots")], None),
    2431: ("UNDER-INFLATION WEARS THE SHOULDERS",
           "THE TREAD CENTRE LIFTS AND THE OUTER EDGES CARRY THE LOAD",
           [("Under-inflated", "Wear on both shoulders; sidewalls flex and overheat"),
            ("Over-inflated", "Wear in the centre of the tread"),
            ("One side only", "Points to wheel alignment")], None),
    2432: ("AFT CG REDUCES LONGITUDINAL STABILITY",
           "THE TAILPLANE'S MOMENT ARM IS SHORTER, SO THE RESTORING MOMENT IS WEAKER",
           [("Stability", "Reduced"), ("Elevator feel", "Lighter; easy to over-control"),
            ("Stall speed", "Slightly lower (less tail download)")], None),
    2435: ("HELICAL TWIST: BLADE ANGLE REDUCES TOWARDS THE TIP",
           "EVERY SECTION MEETS THE AIR AT ABOUT THE SAME ANGLE OF ATTACK",
           [("Why", "Sections further out travel faster"),
            ("Result", "Even thrust along the blade"),
            ("Blade angle", "Chord line to plane of rotation")], None),
    2436: ("STALL WARNING SOUNDS JUST BEFORE THE STALL",
           "TYPICALLY 5 TO 10 KT ABOVE THE STALLING SPEED",
           [("Sensor", "Leading-edge vane or reed"),
            ("Trigger", "Stagnation point moves down and aft as angle of attack rises"),
            ("Purpose", "Time to lower the nose")], None),
    2437: ("CREEP CAN TEAR THE VALVE FROM THE INNER TUBE",
           "THE TUBE TURNS WITH THE TYRE AND DRAGS THE VALVE SIDEWAYS",
           [("Creep", "Tyre slowly rotating on the wheel rim"),
            ("Cause", "Heavy braking and landing loads, worse when under-inflated"),
            ("Risk", "Sudden deflation or blow-out")], None),
    2438: ("TYRE CREEP COMES FROM HEAVY BRAKING ON LANDING",
           "LARGE FORCES BETWEEN TYRE AND RIM TURN THE TYRE ON THE WHEEL",
           [("Also", "Wheel spin-up at touchdown"),
            ("Worse when", "Under-inflated: the beads grip the rim less"),
            ("Check", "Creep marks across tyre and rim")], None),
    2439: ("MORE ANGLE OF ATTACK: CP MOVES FORWARD",
           "UP TO THE STALL; BEYOND IT THE CP MOVES AFT AGAIN",
           [("AoA increased", "CP forward"), ("AoA reduced", "CP aft"),
            ("At the stall", "CP moves aft: the nose drops")], None),
    2440: ("THE MAIN SPAR IS THE WING'S KEY STRUCTURE",
           "ROOT-TO-TIP BEAM CARRYING MOST OF THE BENDING AND SHEAR",
           [("Main spar", "Primary load-carrying beam"), ("Ribs", "Shape; pass air loads to the spars"),
            ("Rear spar", "Carries the trailing-edge controls")], None),
    2441: ("TORQUE LINKS STOP THE PISTON ROTATING",
           "THE STRUT CAN STILL COMPRESS, BUT THE WHEEL STAYS ALIGNED",
           [("Joins", "Upper link on the cylinder, lower link on the piston"),
            ("Result", "Steering inputs reach the wheel"),
            ("Worn links", "Cause nose-wheel shimmy")], None),
    2442: ("10 IS THE BEAD (RIM) DIAMETER",
           "THE DIAMETER OF THE WHEEL RIM THE BEADS SEAT ON",
           [("28", "Outside diameter (in)"), ("12.00", "Section width (in)"), ("10", "Bead (rim) diameter (in)")],
           "28 x 12.00 - 10 = DIAMETER x WIDTH - RIM"),
    2443: ("SLOTTED FLAP: A GAP BETWEEN WING AND FLAP",
           "HIGH-ENERGY AIR FLOWS THROUGH THE SLOT AND OVER THE FLAP",
           [("Effect", "Flow stays attached at large deflections"),
            ("Lift", "More than a plain or split flap"),
            ("Fowler", "Also slides aft to add wing area")], None),
    2444: ("TAXI SHIMMY: WORN OR FAILED TORQUE LINKS",
           "PLAY IN THE LINKS LETS THE WHEEL TWIST BACK AND FORTH",
           [("Also check", "Shimmy damper, wheel bearings, tyre pressures"),
            ("Brakes", "Binding brakes pull to one side, not shimmy"),
            ("Action", "Have the links and damper inspected")], None),
    2445: ("UNDER-EXTENSION: LOW AIR PRESSURE",
           "TOO LITTLE GAS TO HOLD THE LEG AT ITS NORMAL EXTENSION",
           [("Gas charge", "Air or nitrogen: the spring"), ("Result", "Leg sits low; less travel for landing"),
            ("Fix", "Recharge to the specified pressure")], None),
    2446: ("FOWLER FLAP: SLIDES AFT, THEN DOWN",
           "IT ADDS WING AREA AS WELL AS CAMBER",
           [("Aft movement", "Increases wing area"), ("Down movement", "Increases camber"),
            ("Lift", "Largest increase of the common flap types")], None),
    2448: ("OLEO: FLUID BELOW, COMPRESSED GAS ABOVE",
           "THE GAS IS THE SPRING; THE FLUID THROUGH AN ORIFICE DAMPS",
           [("Upper chamber", "Air or nitrogen absorbs the landing energy"),
            ("Lower chamber", "Hydraulic fluid through an orifice stops rebound"),
            ("Result", "Cushioned touchdown without bouncing")], None),
    2449: ("CG TOO FAR AFT: HARD TO CONTROL IN PITCH",
           "SHORT TAIL MOMENT ARM: LITTLE PITCH STABILITY",
           [("Elevator", "Light; easy to over-control"),
            ("Stall recovery", "May lack nose-down authority"),
            ("Spin recovery", "May be impossible")], None),
    2451: ("PLAIN FLAP: THE REAR OF THE WING HINGES DOWN",
           "MORE CAMBER GIVES MORE LIFT AND MORE DRAG",
           [("Slot", "None"), ("Aft movement", "None"), ("Effectiveness", "Least of the common types")], None),
    2453: ("OVER-EXTENSION: HIGH AIR PRESSURE",
           "TOO MUCH GAS MAKES THE SPRING TOO STIFF",
           [("Result", "Leg stands high; harder ride and landing"),
            ("Low pressure", "Causes under-extension instead"),
            ("Fix", "Release to the specified pressure")], None),
    2454: ("TRUSS FUSELAGE: THE LONGERON IS THE MAIN MEMBER",
           "BRACED INTO A RIGID FRAMEWORK OF TRIANGLES",
           [("Longerons", "Principal lengthwise members, usually four"),
            ("Covering", "Carries no load"),
            ("Formers and stringers", "Belong to (semi-)monocoque designs")], None),
    2455: ("CREEP MARKS OUT OF LINE: RISK OF A BLOW-OUT",
           "THE INFLATION VALVE MAY BE TORN FROM THE TUBE ON LANDING",
           [("Marks", "Painted across tyre and rim"),
            ("Moved apart", "Tyre has rotated on the rim"),
            ("Action", "Engineer inspection before flight")], None),
    2456: ("SEMI-MONOCOQUE: FRAME AND SKIN SHARE THE LOAD",
           "FORMERS AND STRINGERS GIVE SHAPE AND RIGIDITY",
           [("Formers", "Frames that give the cross-section"),
            ("Stringers", "Lengthwise stiffeners"),
            ("Stressed skin", "Carries part of the load")], None),
    2457: ("MONOCOQUE: THE SKIN CARRIES ALL THE LOADS",
           "'SINGLE SHELL': LIGHT FORMERS ONLY HOLD THE SHAPE",
           [("Advantage", "Light and roomy"),
            ("Weakness", "Any dent weakens the whole structure"),
            ("Most aircraft", "Use semi-monocoque instead")], None),
    2458: ("THE MAIN SPAR IS THE PRIMARY LOAD CARRIER",
           "EVEN IN A STRESSED-SKIN WING",
           [("Main spar", "Takes most of the bending"),
            ("Skin and spars", "Form a box that resists twisting"),
            ("Stringers", "Stiffen the skin against buckling")], None),
    2459: ("28 IS THE OUTSIDE DIAMETER",
           "THE TYRE'S OVERALL DIAMETER IN INCHES",
           [("28", "Outside diameter (in)"), ("12.00", "Section width (in)"), ("10", "Bead (rim) diameter (in)")],
           "28 x 12.00 - 10 = DIAMETER x WIDTH - RIM"),
    2460: ("OVER-INFLATION WEARS THE TREAD CENTRE",
           "THE CROWN BULGES, SO ONLY THE CENTRE TOUCHES THE GROUND",
           [("Over-inflated", "Centre wear; less shock absorption"),
            ("Under-inflated", "Shoulder wear"),
            ("One side only", "Points to wheel alignment")], None),
    2461: ("RIBS GIVE BOTH SHAPE AND STRENGTH",
           "CUT TO THE AEROFOIL SECTION, THEY PASS AIR LOADS TO THE SPARS",
           [("Ribs", "Chordwise: shape and strength"), ("Stringers", "Spanwise: stiffen the skin"),
            ("Main spar", "Carries the bending")], None),
    2464: ("THE TAILPLANE PUSHES UP OR DOWN AS REQUIRED",
           "IT GIVES LONGITUDINAL (PITCH) STABILITY",
           [("Force", "Up or down, depending on CG and flight condition"),
            ("Directional stability", "Comes from the fin"),
            ("Lateral stability", "Mainly from wing dihedral")], None),
    2466: ("THE FOWLER FLAP INCREASES WING AREA",
           "IT RUNS AFT ON TRACKS BEFORE IT MOVES DOWN",
           [("Early travel", "Mostly area: lift with little drag"),
            ("Full travel", "Area and camber: the largest lift increase"),
            ("Others", "Plain, split, slotted add no significant area")], None),
    # Fuel system and carburettor
    2468: ("FLOAT AND NEEDLE VALVE CONTROL THE FUEL IN",
           "THE FLOAT RISES AND SEATS THE NEEDLE WHEN THE CHAMBER IS FULL",
           [("Fuel used", "Float drops, needle opens"),
            ("Result", "Constant level for accurate metering"),
            ("Throttle butterfly", "Controls the mixture leaving the carburettor")], None),
    2469: ("BAFFLES STOP THE FUEL SURGING",
           "INTERNAL WALLS WITH HOLES DIVIDE THE TANK",
           [("Outlet", "Stays covered in manoeuvres"), ("CG", "No sudden shifts"),
            ("Vents / drains", "Pressure and water, not surge")], None),
    2470: ("FULL RICH: MORE FUEL TO THE INLET MANIFOLD",
           "THE MIXTURE CONTROL METERS FUEL ONLY; THE THROTTLE CONTROLS AIR",
           [("Needle", "Withdrawn: fuel passage fully open"),
            ("Ratio", "Fuel-to-air ratio rises"),
            ("Used for", "Take-off, climb and landing")], None),
    2472: ("LEAN: LESS FUEL TO THE DIFFUSER",
           "THE AIRFLOW, SET BY THE THROTTLE, IS UNCHANGED",
           [("Needle", "Moves in, restricting fuel from the float chamber"),
            ("Ratio", "Fuel-to-air ratio falls"),
            ("Why", "Restore the correct mixture as air density falls")], None),
    2474: ("VALVE LEAD: INLET OPENS BEFORE TDC",
           "AT THE END OF THE EXHAUST STROKE",
           [("Lead", "Valve opens early"), ("Lag", "Valve closes late (inlet after BDC)"),
            ("Overlap", "Both valves open around TDC")], None),
    2475: ("TAKE-OFF: SMALL (FINE) BLADE ANGLE",
           "PROPELLER LEVER FULLY FORWARD: MAXIMUM RPM",
           [("Fine pitch", "Like first gear: full power at low speed"),
            ("Coarse pitch", "Like top gear: efficient cruise"),
            ("Feathered", "No thrust")], None),
    2478: ("CARB HEAT RICHENS THE MIXTURE",
           "WARM AIR IS LESS DENSE, BUT THE FUEL METERED IS ABOUT THE SAME",
           [("Air mass", "Reduced"), ("Mixture", "Richer"), ("Power", "Falls: RPM drops")], None),
    2479: ("LEANING REDUCES THE FUEL-TO-AIR RATIO",
           "LESS FUEL FOR THE SAME AIRFLOW",
           [("When", "Cruise, especially at altitude"), ("Benefit", "Correct mixture, less fuel, cleaner plugs"),
            ("Over-leaning", "Rough running, high CHT, detonation")], None),
    2480: ("RICH: MORE FUEL TO THE DIFFUSER",
           "THE NEEDLE IS WITHDRAWN, OPENING THE FUEL PASSAGE",
           [("Airflow", "Unchanged (set by the throttle)"), ("Ratio", "Fuel-to-air ratio rises"),
            ("High power", "Extra fuel helps cool the cylinders")], None),
    2482: ("THE PRIMER SPRAYS FUEL NEAR THE INLET VALVES",
           "IT BYPASSES THE CARBURETTOR FOR A COLD START",
           [("Why", "Slow cranking gives little carburettor suction"),
            ("Where", "Induction system close to the inlet valves"),
            ("Accelerator pump", "Is the one that squirts into the venturi")], None),
    2483: ("VENTS KEEP THE TANK AT ATMOSPHERIC PRESSURE",
           "AIR REPLACES THE FUEL AS IT IS USED",
           [("Blocked vent", "Vacuum forms; fuel flow can stop"),
            ("Also", "Lets the tank breathe with temperature"),
            ("Surge", "Stopped by baffles, not vents")], None),
    2484: ("MORE POWER: MIXTURE, PROP, THROTTLE",
           "RICHEN, INCREASE RPM, THEN INCREASE MANIFOLD PRESSURE",
           [("Why", "High MP at low RPM overloads the engine"),
            ("Reducing power", "Throttle, prop, mixture"),
            ("Memory aid", "Rich - revs - throttle up")], None),
    2485: ("CARB HEAT: HOT AIR FROM AROUND THE EXHAUST",
           "A FLAP SHUTS THE COLD INTAKE AND OPENS THE HEATER MUFF",
           [("Purpose", "Prevent or melt carburettor ice"),
            ("Filter", "Hot air is unfiltered: limit use on the ground"),
            ("Mixture", "Becomes richer")], None),
}

KF.update({
    2488: ("THE FUEL OUTLET SITS ABOVE THE SUMP",
           "WATER AND SEDIMENT SETTLE BELOW IT INSTEAD OF REACHING THE ENGINE",
           [("Water", "Heavier than fuel: sinks to the sump"),
            ("Drain", "Sump drain valve at the lowest point"),
            ("Pre-flight", "Take a sample and check for water")], None),
    2490: ("FULL LEAN (IDLE CUT-OFF) SHUTS OFF THE FUEL",
           "FUEL ENTERING THE INLET MANIFOLD FALLS TO ALMOST NOTHING",
           [("Used for", "Stopping the engine"),
            ("Why", "Cylinders run dry: no charge left to fire"),
            ("Throttle", "Not moved by the mixture control")], None),
    2492: ("CARB ICE: ROUGH RUNNING AND FALLING RPM",
           "ICE RESTRICTS THE AIRFLOW AND UPSETS THE MIXTURE",
           [("Fixed-pitch prop", "Gradual RPM drop, then roughness"),
            ("Constant-speed prop", "Manifold pressure falls instead"),
            ("Carb heat applied", "Brief extra roughness, then RPM recovers")], None),
    2495: ("RICH MIXTURE: FUEL-TO-AIR RATIO INCREASED",
           "MORE FUEL THAN NEEDED FOR COMPLETE COMBUSTION",
           [("Chemically correct", "About 1:15 by weight"),
            ("Rich", "Runs cooler: used for take-off"),
            ("Too rich", "Wastes fuel, loses power, fouls plugs")], None),
    2497: ("FIXED PITCH: COARSE = BETTER CRUISE",
           "A FIXED-PITCH PROPELLER IS LIKE A CAR STUCK IN ONE GEAR",
           [("Coarse (cruise prop)", "Efficient at speed; less RPM for take-off"),
            ("Fine (climb prop)", "Full RPM at low speed; over-speeds in cruise"),
            ("Choice", "A compromise for the role")], None),
    2499: ("OPEN AND CLOSE THE THROTTLE SMOOTHLY",
           "ABRUPT CHANGES STRESS THE CRANKSHAFT AND PROPELLER",
           [("Sudden opening", "Torque shock and possible hesitation"),
            ("Smooth movement", "Predictable power, less wear"),
            ("Before more power", "Mixture rich, not lean")], None),
    2500: ("ROUGH, THEN A SLOW LOSS OF POWER: CARB ICE",
           "ICE BUILDS GRADUALLY AROUND THE VENTURI AND BUTTERFLY",
           [("Magneto failure", "Immediate drop and roughness"),
            ("Fuel starvation", "Surging, then stopping"),
            ("Action", "Full carb heat at the first signs")], None),
    2501: ("PRIMER: FUEL STRAIGHT TO THE INLET VALVES",
           "A COLD, SLOWLY CRANKED ENGINE DRAWS LITTLE FUEL THROUGH THE CARB",
           [("Primer", "Hand pump delivering a measured amount"),
            ("Where", "Induction system near the inlet valves"),
            ("Does not", "Heat fuel or fill the float chamber")], None),
    2502: ("FUEL PRESSURE IS MEASURED AT THE CARB INLET",
           "IT SHOWS THE PUMPS ARE DELIVERING ENOUGH PRESSURE",
           [("Falling reading", "Pump failure, blockage or empty tank"),
            ("In the tank", "Only atmospheric pressure"),
            ("After the carb", "Fuel is already mixed with air")], None),
    2504: ("AVGAS 100LL IS BLUE",
           "FUEL IS DYED SO ITS GRADE CAN BE SEEN IN A SAMPLE",
           [("100LL", "Blue"), ("100", "Green"), ("80", "Red"), ("Jet A-1", "Clear / straw: never in a piston engine")],
           None),
    2507: ("WARM FUEL ABSORBS MORE WATER",
           "AS IT COOLS, THE WATER COMES OUT AS FREE DROPLETS",
           [("Where it goes", "Settles in the sump; can freeze"),
            ("When", "Overnight or at altitude"),
            ("Action", "Drain the tanks before flight")], None),
    2509: ("LEANING RAISES THE AIR-TO-FUEL RATIO",
           "LESS FUEL FOR THE SAME AIRFLOW",
           [("Air-to-fuel ratio", "Increases"), ("Fuel-to-air ratio", "Decreases"),
            ("Read the question", "Check which way round the ratio is stated")], None),
    2510: ("FULL TANKS OVERNIGHT: LESS CONDENSATION",
           "LITTLE AIR SPACE MEANS LITTLE MOISTURE TO CONDENSE",
           [("Part-full tank", "Moist air condenses on cold walls"),
            ("Water", "Sinks to the sump"),
            ("Still", "Drain and check before the next flight")], None),
    2511: ("RAPID THROTTLE OPENING: THE ACCELERATOR PUMP",
           "IT SQUIRTS EXTRA FUEL SO THE MIXTURE DOES NOT GO LEAN",
           [("Problem", "Air speeds up faster than the heavier fuel"),
            ("Pump", "Linked to the throttle"),
            ("Result", "No hesitation or cut when power is applied")], None),
    2514: ("FIXED PITCH IN A DIVE: RPM INCREASES",
           "MORE SPEED, SMALLER BLADE ANGLE OF ATTACK, LESS TORQUE ABSORBED",
           [("Helix angle", "Increases with forward speed"),
            ("Engine", "Speeds up at the same throttle"),
            ("Steep dive", "Reduce throttle to avoid an overspeed")], None),
    2515: ("WITH AN MP GAUGE: MANIFOLD PRESSURE FALLS",
           "THE GOVERNOR HOLDS RPM, SO RPM GIVES NO WARNING",
           [("First sign", "Gradual, unexplained MP drop"),
            ("Carb heat on", "MP drops a little more"),
            ("Ice melting", "MP then recovers")], None),
    2516: ("THE ACCELERATOR PUMP DISCHARGES FUEL INTO THE VENTURI",
           "AN EXTRA SQUIRT BRIDGES THE MOMENTARY LEAN MIXTURE",
           [("Linked to", "The throttle"), ("Prevents", "Hesitation or a flat spot"),
            ("Priming", "Done by the separate primer")], None),
    # Lubrication, cooling and engine
    2518: ("HIGH OIL TEMP + LOW OIL PRESSURE = LOW OIL",
           "LESS OIL CARRIES THE SAME HEAT AND THE PUMP DRAWS AIR",
           [("Temperature", "Rising"), ("Pressure", "Falling"),
            ("Action", "Land as soon as possible")], None),
    2520: ("GEAR PUMP PLUS SPLASH LUBRICATION",
           "PRESSURE OIL FOR THE BEARINGS; OIL MIST FOR THE REST",
           [("Pressure fed", "Main and big-end bearings, camshaft, accessories"),
            ("Splash", "Cylinder walls, pistons, small ends, gears"),
            ("Oil in fuel", "Only some two-strokes")], None),
    2523: ("PHOSPHATE ESTER IS PURPLE",
           "PURPLE AND PHOSPHATE BOTH START WITH P",
           [("Mineral", "Red"), ("Vegetable", "Blue"), ("Phosphate ester", "Purple (synthetic, fire-resistant)")],
           None),
    2525: ("COOLING FINS IMPROVE ENGINE COOLING",
           "THEY GREATLY INCREASE THE AREA LOSING HEAT TO THE AIR",
           [("Fins", "More surface area"), ("Baffles", "Direct air through the fins"),
            ("Cowl flaps", "Control how much air flows")], None),
    2528: ("NORMAL RUNNING: LIGHT GREY OR TAN DEPOSIT",
           "THE PLUG'S FIRING END IS A WINDOW INTO THE CYLINDER",
           [("Light grey / tan", "Correct mixture and temperature"),
            ("Dry black soot", "Too rich"), ("Wet black oil", "Oil being burnt")], None),
    2529: ("OIL PRESSURE IS MEASURED BEFORE THE BEARINGS",
           "ON THE PUMP'S OUTLET SIDE, AS OIL ENTERS THE GALLERIES",
           [("Shows", "Pressure available to feed the bearings"),
            ("Pump inlet / breather", "Near atmospheric: useless reading"),
            ("Low reading", "Pump failure, low oil or thin hot oil")], None),
    2530: ("THE SCAVENGE PUMP RETURNS OIL TO THE TANK",
           "IT KEEPS THE SUMP OF A DRY-SUMP ENGINE DRY",
           [("Oil stored", "In a separate tank"),
            ("Pressure pump", "Tank to engine"),
            ("Scavenge pump", "Sump to tank; larger capacity")], None),
    2531: ("OIL IS COOLED BEFORE IT REACHES THE ENGINE",
           "PUMP, THEN COOLER, THEN BEARINGS",
           [("Why", "Correct viscosity; can absorb more heat"),
            ("Cold oil", "Bypass valve skips the cooler"),
            ("Protects", "The delicate cooler matrix")], None),
    2533: ("RAM AIR THROUGH THE OIL COOLER",
           "COLD OUTSIDE AIR CARRIES THE HEAT FROM THE COOLER'S MATRIX",
           [("Cooler", "A small radiator that spreads oil into thin films"),
            ("High-power engines", "Shutters control the airflow"),
            ("Not by", "Fuel or the cabin heater")], None),
    2534: ("OIL TEMPERATURE IS READ AFTER THE COOLER",
           "THE TEMPERATURE OF THE OIL ACTUALLY FED TO THE ENGINE",
           [("Why", "Viscosity at the bearings is what matters"),
            ("Before the cooler", "Would show hot oil leaving the engine"),
            ("Watch for", "High temperature with low pressure")], None),
    2537: ("VEGETABLE-BASED FLUID IS BLUE",
           "THE COLOUR IDENTIFIES THE TYPE; IT IS NOT A LICENCE TO MIX",
           [("Mineral", "Red"), ("Vegetable", "Blue"), ("Phosphate ester", "Purple")], None),
    2538: ("MINERAL-BASED FLUID IS RED",
           "A PETROLEUM PRODUCT USED IN MOST LIGHT-AIRCRAFT BRAKES",
           [("Mineral", "Red"), ("Vegetable", "Blue"), ("Phosphate ester", "Purple")], None),
    2542: ("ENGINE OIL PUMPS ARE GEAR PUMPS",
           "MESHING GEARS CARRY OIL ROUND THE OUTSIDE FROM INLET TO OUTLET",
           [("Type", "Positive displacement: fixed volume per revolution"),
            ("Pressure", "Enough to force oil through the bearings"),
            ("Limited by", "The pressure relief valve")], None),
    2543: ("WET SUMP: OIL IS STORED IN THE ENGINE SUMP",
           "A PRESSURE PUMP DISTRIBUTES IT; IT DRAINS BACK BY GRAVITY",
           [("Used in", "Most light non-aerobatic aircraft"),
            ("Dry sump", "Separate tank and a scavenge pump"),
            ("Weakness", "Oil moves about in aerobatics")], None),
    2545: ("NEVER MIX HYDRAULIC FLUID TYPES",
           "EACH NEEDS ITS OWN SEALS; MIXING ATTACKS THEM",
           [("Effect", "Seals swell or harden; sludge blocks valves"),
            ("Wrong top-up", "Whole system must be drained and flushed"),
            ("Always", "Use the fluid specified for the aircraft")], None),
    2549: ("MAIN BEARINGS GET HIGH-PRESSURE OIL",
           "THROUGH GALLERIES AND CRANKSHAFT DRILLINGS TO THE BIG ENDS",
           [("Pressure fed", "Main and big-end bearings"),
            ("Splash", "Cylinder walls, pistons, small ends"),
            ("Why", "Heaviest loads need a positive supply")], None),
    2552: ("THE RELIEF VALVE KEEPS OIL PRESSURE CONSTANT",
           "IT RETURNS SURPLUS OIL TO THE PUMP INLET",
           [("Without it", "Pressure would rise with RPM"),
            ("Opens", "At a set spring pressure"),
            ("Protects", "Cooler and filters from bursting")], None),
    2553: ("COWL FLAPS CONTROL THE COOLING AIRFLOW",
           "TO KEEP CYLINDER AND OIL TEMPERATURES IN LIMITS",
           [("Open", "Ground running and climb: low speed, high power"),
            ("Closed", "Cruise and descent: less drag, no over-cooling"),
            ("Baffles", "Only direct the air")], None),
    2554: ("IGNITION TIMING IS FIXED",
           "EACH MAGNETO FIRES AT THE SAME CRANK ANGLE AT ANY RPM",
           [("Typical", "20 to 25 degrees BTDC"),
            ("Higher RPM", "Sparks come more often, not earlier"),
            ("Only retard", "Impulse coupling during starting")], None),
    2556: ("IGNITION: 20 TO 25 DEGREES BEFORE TDC",
           "ON THE COMPRESSION STROKE, SO PRESSURE PEAKS JUST AFTER TDC",
           [("Why early", "The mixture takes time to burn"),
            ("At or after TDC", "Power wasted, engine overheats"),
            ("Result", "Most useful work on the power stroke")], None),
    2557: ("DRY BLACK SOOT: MIXTURE TOO RICH",
           "THE FUEL HAS NOT BURNT COMPLETELY",
           [("Common cause", "Long ground running at full rich"),
            ("Prevention", "Lean on the ground"),
            ("Wet oily deposit", "Oil being burnt instead")], None),
    2559: ("PASCAL'S LAW: PRESSURE IS TRANSMITTED",
           "PRESSURE ON A CONFINED FLUID ACTS EQUALLY IN ALL DIRECTIONS",
           [("Fluid", "Practically incompressible"),
            ("Small piston", "Creates pressure"), ("Large piston", "Gives a larger force")],
           "FORCE = PRESSURE x AREA"),
    2560: ("VALVE OVERLAP: BOTH VALVES OPEN AROUND TDC",
           "END OF EXHAUST, START OF INDUCTION",
           [("Inlet", "Opened early (lead)"), ("Exhaust", "Not yet closed (lag)"),
            ("Benefit", "Exhaust flow helps draw in the fresh charge")], None),
    2564: ("BAFFLES DIRECT AIR OVER THE CYLINDERS",
           "THEY FORCE COOLING AIR CLOSELY THROUGH THE FINS",
           [("Result", "Every cylinder cooled evenly"),
            ("Fixed", "Plates and seals, not adjustable"),
            ("Amount of air", "Controlled by the cowl flaps")], None),
    # Electrics and pressure instruments
    2566: ("PITOT PRESSURE GOES INTO THE ASI CAPSULE",
           "STATIC PRESSURE FILLS THE CASE AROUND IT",
           [("Capsule", "Expands with pitot minus static"),
            ("Difference", "Dynamic pressure: shown as airspeed"),
            ("Calibrated leak", "Belongs to the VSI")], "PITOT - STATIC = DYNAMIC PRESSURE"),
    2573: ("ALTERNATOR DIODES CONVERT AC TO DC",
           "THE RECTIFIER FEEDS DC TO THE BUS AND BATTERY",
           [("Stator", "Produces AC"), ("Diodes", "One-way: also block reverse current"),
            ("Voltage", "Controlled by the regulator")], None),
    2577: ("LEFT-ZERO AMMETER: ALTERNATOR OUTPUT ONLY",
           "A LOADMETER: IT CANNOT SHOW A DISCHARGE",
           [("Connected", "In the alternator output lead"),
            ("Reads", "Current supplied to loads and battery"),
            ("Charge / discharge", "Needs a centre-zero ammeter")], None),
    2579: ("CENTRE-ZERO: RIGHT OF CENTRE IS CHARGING",
           "LEFT OF CENTRE MEANS THE BATTERY IS DISCHARGING",
           [("Right (+)", "Current into the battery"),
            ("Left (-)", "Battery discharging"),
            ("Steady discharge in flight", "Alternator has probably failed")], None),
    2580: ("ALTERNATORS STILL CHARGE AT LOW RPM",
           "EVEN AT IDLE OR WHILE TAXIING",
           [("DC generator", "Little output until RPM is fairly high"),
            ("Alternator", "Useful output at idle; lighter"),
            ("But", "Needs battery power to energise its field")], None),
    2582: ("AN AMMETER MEASURES CURRENT",
           "IN AMPERES",
           [("Ammeter", "Current (A)"), ("Voltmeter", "Voltage (V)"), ("Ohmmeter", "Resistance")], None),
    2584: ("PITOT PRESSURE: A TUBE IN THE AIRFLOW",
           "FORWARD-FACING, CLEAR OF DISTURBED AIR",
           [("Pitot tube", "Total pressure (static + dynamic)"),
            ("Static port", "Flush on the fuselage side"),
            ("Pre-flight", "Remove the pitot cover")], None),
    2585: ("THE STATOR REMAINS STATIONARY",
           "THE ROTOR (FIELD) SPINS INSIDE IT",
           [("Stator", "Fixed output windings"), ("Rotor", "Electromagnet fed through slip rings"),
            ("Benefit", "Heavy output current needs no brushes")], None),
    2586: ("TOP UP A LEAD-ACID BATTERY WITH DISTILLED WATER",
           "CHARGING LOSES WATER, NOT ACID",
           [("Distilled", "Tap-water minerals contaminate the plates"),
            ("Never add acid", "Electrolyte would be too strong"),
            ("Hydrogen", "Explosive: keep the battery ventilated")], None),
})

KF.update({
    2589: ("ALTERNATOR: MORE OUTPUT AT LOW RPM",
           "IT CHARGES EVEN AT IDLE; A DC GENERATOR NEEDS HIGHER RPM",
           [("Alternator", "Useful output at low RPM; lighter"),
            ("DC generator", "Little output until RPM is fairly high"),
            ("Both", "Need a voltage regulator")], None),
    2590: ("A CAPACITOR STORES ELECTRICAL CHARGE",
           "TWO PLATES SEPARATED BY AN INSULATOR (DIELECTRIC)",
           [("In a magneto", "Condenser prevents arcing at the points"),
            ("Elsewhere", "Smooths voltage, suppresses interference"),
            ("Not", "Limiting current (resistor) or AC to DC (diodes)")], None),
    2593: ("ONLY THE ASI USES PITOT PRESSURE",
           "IT COMPARES PITOT WITH STATIC TO FIND DYNAMIC PRESSURE",
           [("ASI", "Pitot and static"), ("Altimeter, VSI", "Static only"),
            ("Pitot blocked", "Only the ASI is affected")], None),
    2596: ("THE TRANSFORMER STEPS UP THE VOLTAGE AT THE PLUG",
           "LOW VOLTAGE TRAVELS ALONG THE LEADS; HIGH VOLTAGE ONLY AT THE PLUG",
           [("Magneto", "Produces a low voltage"),
            ("Transformer", "Mounted close to each plug"),
            ("Benefit", "Less flash-over and leakage at altitude")], None),
    2597: ("THE RECTIFIER CONVERTS AC TO DC",
           "A SET OF DIODES BUILT INTO THE ALTERNATOR",
           [("Stator", "Generates AC"), ("Diodes", "Pass current one way only"),
            ("Bonus", "Battery cannot discharge back into the alternator")], None),
    2601: ("STATIC PRESSURE: A PORT IN UNDISTURBED AIR",
           "A FLUSH HOLE, USUALLY ONE ON EACH SIDE OF THE FUSELAGE",
           [("Senses", "True ambient pressure, unaffected by speed"),
            ("Alternate source", "The cockpit"),
            ("Keep clear", "No polish, tape or insects")], None),
    2603: ("ASI: STATIC TO THE CASE, PITOT TO THE CAPSULE",
           "STATIC CANCELS OUT, LEAVING DYNAMIC PRESSURE",
           [("Capsule", "Pitot (total) pressure"), ("Case", "Static pressure"),
            ("Capsule expands with", "Dynamic pressure: airspeed")], "PITOT - STATIC = DYNAMIC PRESSURE"),
    2604: ("RESISTORS VARY THE VOLTAGE",
           "A RESISTOR OPPOSES CURRENT AND DROPS VOLTAGE ACROSS IT",
           [("Fixed", "Sets voltage or current in part of a circuit"),
            ("Variable (rheostat)", "E.g. dimming panel lights"),
            ("More resistance", "Less current")], "V = I x R"),
    2605: ("THE PITOT TUBE FACES DIRECTLY INTO THE AIRFLOW",
           "AIR ENTERING IT IS BROUGHT TO REST: TOTAL PRESSURE",
           [("Mounted", "Clear of fuselage and propeller, often under a wing"),
            ("Pitot heat", "Keeps it free of ice"),
            ("Flush mounting", "Is for a static vent")], None),
    2606: ("ASI: STATIC PRESSURE GOES TO THE CASE",
           "PITOT PRESSURE GOES INSIDE THE CAPSULE",
           [("Case", "Static"), ("Capsule", "Pitot"), ("Measured", "The difference: dynamic pressure")],
           "PITOT - STATIC = DYNAMIC PRESSURE"),
    2607: ("AN INVERTER CONVERTS DC TO AC",
           "FOR INSTRUMENTS AND AVIONICS THAT NEED AC",
           [("Inverter", "DC to AC"), ("Rectifier", "AC to DC"), ("Transformer", "AC voltage up or down")], None),
    2609: ("ELECTROLYTE: SULPHURIC ACID AND PURE WATER",
           "DILUTE SULPHURIC ACID IN A LEAD-ACID BATTERY",
           [("Discharging", "Acid combines with the plates; electrolyte weakens"),
            ("State of charge", "Shown by specific gravity"),
            ("Ni-Cad", "Uses potassium hydroxide: never mix servicing")], None),
    2610: ("A RECTIFIER CONVERTS ALTERNATOR AC TO DC",
           "DIODES, USUALLY BUILT INTO THE ALTERNATOR",
           [("Rectifier", "AC to DC (alternator)"), ("Commutator", "Does it mechanically (DC generator)"),
            ("Inverter", "DC to AC")], None),
    2611: ("A VOLTMETER SHOWS SYSTEM VOLTAGE",
           "BUS OR BATTERY VOLTAGE",
           [("Charging", "About 14 V (12 V system), 28 V (24 V system)"),
            ("Low reading", "Alternator failure"),
            ("High reading", "Faulty regulator")], None),
    2612: ("24 V LEAD-ACID BATTERY: TWELVE CELLS",
           "EACH CELL GIVES ABOUT 2 V, CONNECTED IN SERIES",
           [("12 V", "Six cells"), ("24 V", "Twelve cells"),
            ("Cell size", "Sets capacity (Ah), not voltage")], "CELLS = VOLTS / 2"),
    2614: ("THE ALTERNATOR SUPPLIES THE LOADS AND CHARGES THE BATTERY",
           "THE MAIN SOURCE OF ELECTRICAL POWER IN FLIGHT",
           [("Battery", "Starting and reserve if the alternator fails"),
            ("Ignition", "From the independent magnetos"),
            ("DC to AC", "An inverter's job")], None),
    2615: ("THE ASI MEASURES PITOT MINUS STATIC",
           "THE DIFFERENCE IS DYNAMIC PRESSURE",
           [("Pitot", "Static + dynamic"), ("Depends on", "Airspeed and air density"),
            ("Vacuum", "Drives the gyros, not the ASI")], "DYNAMIC PRESSURE = 1/2 x RHO x V SQUARED"),
    2616: ("THE IVSI REMOVES THE TIME LAG",
           "AN ACCELEROMETER CHANGES CAPSULE PRESSURE AT ONCE",
           [("Conventional VSI", "Lags a few seconds"),
            ("IVSI", "Almost instant indication"),
            ("Still present", "Position and manoeuvre-induced errors")], None),
    2617: ("PITOT AND STATIC BOTH BLOCKED: ALL THREE AFFECTED",
           "ALTIMETER, VSI AND ASI",
           [("Altimeter", "Freezes"), ("VSI", "Reads zero"), ("ASI", "Reading freezes")], None),
    2619: ("THE VACUUM PUMP REDUCES PRESSURE IN THE GYRO CASE",
           "CABIN AIR RUSHES IN THROUGH A JET AND SPINS THE ROTOR",
           [("Driven by", "The engine"), ("Air in", "Filtered cabin air"),
            ("Not part of", "The pitot-static system")], None),
    2620: ("PITOT BLOCKED: ASI STUCK IN LEVEL FLIGHT",
           "TRAPPED CAPSULE PRESSURE: THE READING IGNORES POWER CHANGES",
           [("Level flight", "Constant reading"), ("Climb", "Over-reads"), ("Descent", "Under-reads")], None),
    2621: ("ASI TO ZERO: PITOT BLOCKED AND A LEAK",
           "THE TRAPPED PRESSURE LEAKS AWAY UNTIL IT EQUALS STATIC",
           [("Pitot blocked only", "Reading freezes"),
            ("Pitot blocked + leak", "Reading falls to zero"),
            ("Static blocked", "Errors as altitude changes")], None),
    2623: ("CLIMB: STATIC PRESSURE FALLS, CAPSULE EXPANDS",
           "THE LINKAGE SHOWS A HIGHER ALTITUDE",
           [("Capsule", "Sealed, partial vacuum"), ("Case", "Static pressure"),
            ("Descent", "Rising pressure compresses the capsule")], None),
    2624: ("HIGHER ALTITUDE: THE CAPSULE EXPANDS",
           "LESS STATIC PRESSURE SQUEEZES THE SEALED CAPSULE",
           [("Expands", "Higher reading"), ("Contracts", "Lower reading"),
            ("Capsule", "Partly evacuated, held open by a spring")], None),
    2625: ("STATIC BLOCKED: ALTIMETER FREEZES",
           "IT SHOWS THE ALTITUDE WHERE THE BLOCKAGE OCCURRED",
           [("Altimeter", "Frozen"), ("VSI", "Returns to zero"),
            ("Fix", "Select the alternate static source")], None),
    2627: ("PITOT BLOCKED IN LEVEL FLIGHT: ASI CONSTANT",
           "BOTH CAPSULE AND CASE PRESSURES STAY THE SAME",
           [("Level flight", "Constant, whatever the speed"), ("Climb", "Over-reads"),
            ("Falls to zero", "Only if the trapped pressure leaks away")], None),
    2628: ("ALTIMETER: VACUUM CAPSULE, STATIC IN THE CASE",
           "THE CAPSULE EXPANDS OR CONTRACTS AS STATIC PRESSURE CHANGES",
           [("Capsule", "Sealed with a partial vacuum, held open by a spring"),
            ("Case", "Airtight, fed with static pressure"),
            ("Linkage", "Drives the pointers")], None),
    2629: ("GREEN ARC: NORMAL OPERATING RANGE",
           "FROM VS1 TO VNO",
           [("Green", "VS1 (clean stall) to VNO"), ("White", "Flap operating range"),
            ("Yellow", "Caution: smooth air only"), ("Red line", "VNE")], None),
    2630: ("GYRO SUCTION: 3 TO 5 INCHES OF MERCURY",
           "BELOW ATMOSPHERIC, SHOWN ON THE SUCTION GAUGE",
           [("Too low", "Rotors slow: sluggish, erratic gyros"),
            ("Too high", "Rotors over-speed and wear"),
            ("Check", "During the run-up")], None),
    2631: ("ONLY STATIC VENT BLOCKED: VSI READS ZERO",
           "THE DIFFERENCE LEAKS AWAY THROUGH THE CALIBRATED LEAK",
           [("VSI", "Settles at zero"), ("Altimeter", "Frozen"),
            ("Clue", "Both stuck during a climb or descent")], None),
    2632: ("PRECESSION: THE FORCE ACTS 90 DEGREES LATER",
           "IN THE DIRECTION OF ROTATION",
           [("Rule", "Carry the push 90 degrees round with the spin"),
            ("Turn indicator", "Uses precession to measure rate of turn"),
            ("Attitude indicator", "Port vanes use it to stay erect")], None),
    2633: ("3 inHg SUCTION: GYROS WORK NORMALLY",
           "IT IS WITHIN THE NORMAL 3 TO 5 inHg RANGE",
           [("Below range", "Sluggish or erratic"), ("Above range", "Over-speed"),
            ("Limits", "Always per the POH")], None),
    2635: ("STATIC BLOCKED IN A DESCENT: ASI OVER-READS",
           "THE CASE KEEPS THE LOWER PRESSURE FROM HIGHER UP",
           [("Descent", "Over-reads"), ("Climb", "Under-reads: stall risk"),
            ("Level", "Correct while altitude is unchanged")], None),
    2638: ("STATIC BLOCKED IN LEVEL FLIGHT: ASI CONSTANT",
           "THE TRAPPED CASE PRESSURE STILL MATCHES THE REAL STATIC",
           [("Level, constant speed", "Reading constant and correct"),
            ("Climb", "Under-reads"), ("Descent", "Over-reads")], None),
    2640: ("STATIC BLOCKAGE AFFECTS THE ALTIMETER, ASI AND VSI",
           "ALL THREE USE STATIC PRESSURE",
           [("Altimeter", "Freezes"), ("VSI", "Reads zero"),
            ("ASI", "Wrong once altitude changes"), ("Gyros", "Unaffected")], None),
    2641: ("STATIC BLOCKED, SAME LEVEL: ASI STILL CORRECT",
           "THE TRAPPED STATIC PRESSURE STILL EQUALS THE REAL ONE",
           [("Speed changes", "Still shown correctly"),
            ("Climb", "Under-reads"), ("Descent", "Over-reads")], None),
    2645: ("AFTER A RAPID DESCENT THE ALTIMETER OVER-READS",
           "FRICTION AND LAG: IT BRIEFLY SHOWS TOO HIGH",
           [("In the descent", "Indicates slightly high"),
            ("On levelling", "Takes a moment to catch up"),
            ("Danger", "Actually lower than indicated near terrain")], None),
    2646: ("THE VACUUM PUMP SUCKS AIR FROM THE GYRO CASE",
           "INCOMING AIR STRIKES BUCKETS IN THE ROTOR AND SPINS IT",
           [("Air in", "Cabin air through a filter and nozzle"),
            ("Air out", "Drawn away to the pump"),
            ("Driven by", "The engine, not the alternator")], None),
    2647: ("YELLOW ARC: CAUTION RANGE",
           "FROM VNO TO VNE: SMOOTH AIR ONLY",
           [("Yellow", "VNO to VNE"), ("Green", "Normal operating range"),
            ("White", "Flap operating range"), ("Red line", "VNE")], None),
    2648: ("PITOT BLOCKED AND ASI AT ZERO: A LEAK",
           "THE TRAPPED PITOT PRESSURE ESCAPES UNTIL IT EQUALS STATIC",
           [("Blocked, no leak", "Reading freezes"),
            ("Blocked with leak", "Reading falls to zero"),
            ("Static blockage", "Does not zero the ASI in level flight")], None),
    2649: ("FULL-FLAP STALL SPEED: BOTTOM OF THE WHITE ARC",
           "VSO: LANDING CONFIGURATION AT MAXIMUM WEIGHT",
           [("White arc bottom", "VSO (full flap)"), ("White arc top", "VFE"),
            ("Green arc bottom", "VS1 (clean)")], None),
    2651: ("PRESSURE ALTITUDE = 5000 FT",
           "QNH ABOVE 1013: PRESSURE ALTITUDE IS BELOW THE INDICATED ALTITUDE",
           [("QNH - 1013", "1023 - 1013 = 10 hPa"), ("Correction", "10 x 30 = 300 ft"),
            ("Pressure altitude", "5300 - 300 = 5000 ft")], "PA = INDICATED - (QNH - 1013) x 30"),
    2652: ("QNH = 1003 hPa",
           "PRESSURE ALTITUDE ABOVE ELEVATION: QNH IS BELOW 1013",
           [("Difference", "2800 - 2500 = 300 ft"), ("In hPa", "300 / 30 = 10 hPa"),
            ("QNH", "1013 - 10 = 1003 hPa")], "PA = ELEVATION + (1013 - QNH) x 30"),
    2653: ("AIRFIELD ELEVATION = 2500 FT",
           "QNH ABOVE 1013: ELEVATION IS ABOVE THE PRESSURE ALTITUDE",
           [("QNH - 1013", "1023 - 1013 = 10 hPa"), ("Correction", "10 x 30 = 300 ft"),
            ("Elevation", "2200 + 300 = 2500 ft")], "ELEVATION = PA + (QNH - 1013) x 30"),
})

KF.update({
    2654: ("PITOT BLOCKED IN A CLIMB: ASI OVER-READS",
           "TRAPPED CAPSULE PRESSURE, FALLING STATIC IN THE CASE",
           [("Climb", "Over-reads: shows speed rising"), ("Descent", "Under-reads"),
            ("Danger", "Following it can lead towards a stall")], None),
    2655: ("RAPID CLIMB: ALTIMETER READS LOW",
           "THE MECHANISM LAGS BEHIND THE REAL ALTITUDE",
           [("Rapid climb", "Indicates lower than actual"), ("Rapid descent", "Indicates higher than actual"),
            ("Levelled off", "The lag disappears")], None),
    2663: ("MORE MASS AND MORE SPEED: MORE RIGIDITY",
           "RIGIDITY DEPENDS ON THE ROTOR'S ANGULAR MOMENTUM",
           [("Mass", "Best concentrated at the rim"), ("Speed", "High RPM"),
            ("Low suction", "Slower rotor, less rigidity")], "RIGIDITY = MOMENT OF INERTIA x ANGULAR SPEED"),
    2664: ("A RELIEF VALVE BEFORE THE PUMP PREVENTS OVER-SPEED",
           "IT ADMITS AMBIENT AIR WHEN SUCTION EXCEEDS ITS SETTING",
           [("Also called", "Vacuum regulator"), ("Located", "Just before (upstream of) the pump"),
            ("After the pump", "Outlet side: could not limit suction")], None),
    2665: ("DESCENDING: THE CAPSULE CONTRACTS",
           "RISING STATIC PRESSURE SQUEEZES IT: LOWER READING",
           [("Contracts", "Lower reading"), ("Expands", "Higher reading"),
            ("Capsule", "Sealed, partly evacuated")], None),
    2667: ("VACUUM SYSTEM PRESSURE IS BELOW ATMOSPHERIC",
           "THE SUCTION GAUGE SHOWS HOW FAR BELOW, IN inHg",
           [("Normal", "About 3 to 5 inHg below atmospheric"),
            ("Why", "Draws air through the instruments to spin the rotors"),
            ("Zero suction", "Gyros slow down and stop")], None),
    2668: ("2 inHg SUCTION: GYROS ERRATIC",
           "BELOW THE NORMAL 3 TO 5 inHg RANGE",
           [("Rotors", "Cannot reach full speed"), ("Effect", "Sluggish, wandering, erratic"),
            ("Causes", "Failing pump, leak or blocked filter")], None),
    2671: ("THE ATTITUDE GYRO STAYS VERTICAL TO THE EARTH",
           "THE AIRCRAFT PITCHES AND ROLLS AROUND IT",
           [("Horizon bar", "Linked to the gyro: stays level"),
            ("Miniature aircraft", "Fixed to the case: moves with the aircraft"),
            ("Principle", "Rigidity")], None),
    2673: ("LOAD FACTOR DEPENDS ONLY ON BANK ANGLE",
           "IN A LEVEL, COORDINATED TURN",
           [("30 degrees", "1.15 g"), ("45 degrees", "1.41 g"), ("60 degrees", "2 g")],
           "n = 1 / cos(BANK)"),
    2674: ("DEVIATION VARIES WITH HEADING",
           "CAUSED BY THE AIRCRAFT'S OWN MAGNETIC FIELDS",
           [("Sources", "Steel parts, engine, radios, wiring"),
            ("Measured", "By a compass swing"),
            ("Recorded", "On the deviation card for each heading")], None),
    2675: ("THE TURN COORDINATOR SHOWS RATE OF TURN",
           "RATE ONE = 3 DEGREES PER SECOND (2 MINUTES FOR 360)",
           [("Canted gyro", "Also senses rate of roll"),
            ("Does not show", "Bank angle"),
            ("Balance ball", "Shows coordination")], None),
    2679: ("TAXI LEFT: NEEDLE LEFT, BALL RIGHT",
           "THE BALL SWINGS TO THE OUTSIDE OF THE TURN",
           [("Needle", "Shows the direction of turn"), ("Ball", "Outside of the turn"),
            ("Faulty if", "Needle still or reversed, or ball sticks")], None),
    2680: ("RESET THE DI EVERY 10 TO 15 MINUTES",
           "TO THE MAGNETIC COMPASS, IN STEADY STRAIGHT AND LEVEL FLIGHT",
           [("Why", "Real and apparent wander make it drift"),
            ("When", "Unaccelerated, wings level"),
            ("Not in a turn", "Compass errors would be copied across")], None),
    2687: ("THE VERTICAL-AXIS GYRO STAYS FIXED IN SPACE",
           "THE AIRCRAFT PITCHES AND ROLLS ABOUT IT",
           [("Gyro", "Erected to the earth's vertical"),
            ("Horizon bar", "Stays level with the real horizon"),
            ("Miniature aircraft", "Moves with the case")], None),
    2691: ("BALL TO THE INSIDE: SLIPPING TURN",
           "TOO MUCH BANK FOR THE RATE OF TURN",
           [("Slip", "Ball inside the turn"), ("Skid", "Ball outside the turn"),
            ("Correction", "Step on the ball: rudder into the turn or less bank")], None),
    2692: ("SUPPLEMENTS: OPTIONAL EQUIPMENT",
           "EQUIPMENT AND MODIFICATIONS NOT FITTED TO THE STANDARD AIRCRAFT",
           [("Examples", "GPS, autopilot, long-range tanks, floats"),
            ("Contains", "Their limitations and procedures"),
            ("Where they differ", "Supplements take precedence")], None),
    2693: ("BALL TO THE OUTSIDE: SKIDDING TURN",
           "RATE OF TURN TOO GREAT FOR THE BANK",
           [("Usual cause", "Too much rudder into the turn"),
            ("Correction", "Ease off the rudder or increase bank"),
            ("Danger", "Near the stall it can lead to a spin")], None),
    2695: ("ARTIFICIAL HORIZON: GYRO FIXED, AIRCRAFT MOVES",
           "A VERTICAL-AXIS GYRO HELD BY RIGIDITY",
           [("Attitude indicator", "Vertical spin axis"),
            ("Direction indicator", "Horizontal spin axis"),
            ("Turn indicator", "Spring-restrained rate gyro")], None),
    2700: ("DI CHECK: LEFT DECREASES, RIGHT INCREASES",
           "HEADINGS INCREASE CLOCKWISE, LIKE THE COMPASS CARD",
           [("Left turn", "Heading decreases"), ("Right turn", "Heading increases"),
            ("No change / wrong way", "Unserviceable")], None),
    2705: ("BALL CENTRED: COORDINATED TURN",
           "BANK AND RATE OF TURN ARE MATCHED",
           [("Resultant force", "Straight down through the seat"),
            ("Achieved by", "Rudder together with aileron"),
            ("Slip / skid", "Ball inside / outside")], None),
    2710: ("TAXI CHECK: NEEDLE WITH THE TURN, BALL OUTSIDE",
           "LIKE A PASSENGER PUSHED OUTWARDS IN A CAR",
           [("Needle / aircraft", "Same direction as the turn"),
            ("Ball", "Outside of the turn"),
            ("Faulty if", "Needle still, or ball moves inwards")], None),
    2719: ("TAXI RIGHT: NEEDLE RIGHT, BALL LEFT",
           "THE BALL SWINGS TO THE OUTSIDE OF THE TURN",
           [("Needle", "Direction of the turn"), ("Ball", "Sideways force: outside"),
            ("Check", "Turn gently each way")], None),
    2722: ("VNO: MAXIMUM SPEED FOR NORMAL OPERATION",
           "THE MAXIMUM STRUCTURAL CRUISING SPEED: TOP OF THE GREEN ARC",
           [("VNO", "Top of green arc"), ("VNE", "Red line"), ("VFE", "Top of white arc"),
            ("VA", "Manoeuvring speed")], None),
    2724: ("VSO: STALL SPEED IN THE LANDING CONFIGURATION",
           "BOTTOM OF THE WHITE ARC",
           [("VSO", "Full flap, gear down"), ("VS1", "Clean: bottom of green arc"),
            ("VFE", "Top of white arc")], None),
    2725: ("THE CSD DRIVES THE GENERATOR AT CONSTANT SPEED",
           "SO THE AC FREQUENCY STAYS CONSTANT",
           [("Engine speed", "Varies through the flight"),
            ("CSD", "Varies its drive ratio automatically"),
            ("Frequency", "Usually 400 Hz")], None),
    2729: ("OVER-LEANING: ROUGH, LESS POWER, COOLER",
           "PAST BEST ECONOMY THE MIXTURE BURNS SLOWLY AND UNEVENLY",
           [("Engine", "Runs rough; may stop"), ("Power", "Falls"),
            ("EGT / CHT", "Generally fall on the lean side of peak")], None),
    2730: ("OTTO CYCLE: TWO ADIABATIC, TWO CONSTANT-VOLUME",
           "THE ENCLOSED AREA IS THE USEFUL WORK PER CYCLE",
           [("Adiabatic", "Compression and expansion (power)"),
            ("Constant volume", "Heat added at TDC; rejected at BDC"),
            ("Area on P-V diagram", "Useful work")], None),
    2731: ("RIGHT TURN, BALL RIGHT: A SLIP",
           "REDUCE BANK OR INCREASE THE RATE OF TURN",
           [("Ball inside", "Slipping: too much bank"),
            ("Fix", "Right rudder (step on the ball) or less bank"),
            ("Worse", "More bank or less rate of turn")], None),
    2732: ("RIGIDITY: MOMENT OF INERTIA x ANGULAR SPEED",
           "DOUBLE EITHER AND RIGIDITY DOUBLES",
           [("Moment of inertia", "Mass and its distance from the axis"),
            ("Angular speed", "Rotor RPM"),
            ("Slow rotor", "Sluggish instruments")], "RIGIDITY = I x OMEGA"),
    2733: ("DYNAMIC PRESSURE: DENSITY AND SPEED SQUARED",
           "DOUBLE THE SPEED: FOUR TIMES THE DYNAMIC PRESSURE",
           [("rho", "Air density"), ("V", "Airspeed"), ("ASI", "Measures dynamic pressure")],
           "q = 1/2 x RHO x V SQUARED"),
    2734: ("AN INVERTER CONVERTS DC TO AC",
           "FOR AC INSTRUMENTS AND AVIONICS IN A DC AIRCRAFT",
           [("Inverter", "DC to AC"), ("Rectifier", "AC to DC"),
            ("TRU", "Transformer-rectifier: AC to lower-voltage DC")], None),
    2735: ("THE ARTIFICIAL HORIZON IS A GYRO INSTRUMENT",
           "A VERTICAL-AXIS GYRO GIVES THE PITCH AND BANK REFERENCE",
           [("Gyro instruments", "Attitude, direction, turn"),
            ("Pitot-static", "ASI, altimeter, VSI"),
            ("Light aircraft", "Usually vacuum-driven")], None),
    2737: ("MORE POWER: RPM FIRST, THEN MANIFOLD PRESSURE",
           "HIGH MP AT LOW RPM OVERLOADS THE ENGINE",
           [("Increasing", "Prop lever forward, then throttle"),
            ("Reducing", "Throttle back, then prop lever"),
            ("Risk otherwise", "Overstress and detonation")], None),
    2739: ("THE CAUTION RANGE IS YELLOW",
           "BETWEEN VNO AND VNE: SMOOTH AIR ONLY",
           [("Yellow", "Caution: VNO to VNE"), ("Green", "Normal operating"),
            ("White", "Flap operating"), ("Red line", "VNE")], None),
    2740: ("VFE: MAXIMUM SPEED WITH FLAPS EXTENDED",
           "TOP OF THE WHITE ARC",
           [("VFE", "Flaps extended"), ("VLE", "Landing gear extended"),
            ("VNO", "Maximum structural cruising speed")], None),
    2741: ("WASTEGATE STUCK CLOSED: OVERBOOST RISK",
           "ALL THE EXHAUST DRIVES THE TURBINE",
           [("Descent, full throttle", "MP can exceed its limit"),
            ("Risk", "Detonation and engine damage"),
            ("Action", "Watch MP; reduce throttle")], None),
    2742: ("POWER = TORQUE x ANGULAR SPEED",
           "SAME TORQUE AT HIGHER RPM GIVES MORE POWER",
           [("Torque", "Turning moment of the crankshaft"),
            ("Angular speed", "Radians per second, from RPM"),
            ("Force x distance", "Is work, not power")], "P = T x OMEGA"),
    2743: ("A TRIM TAB REMOVES SUSTAINED CONTROL FORCES",
           "ITS AIR LOAD HOLDS THE SURFACE WHERE IT IS NEEDED",
           [("Pilot", "No longer holds steady pressure"),
            ("Does not", "Increase control travel or limiting speeds"),
            ("Technique", "Fly the attitude first, then trim")], None),
    2744: ("THE FUEL STRAINER IS UPSTREAM OF THE NEEDLE VALVE",
           "IT CATCHES DIRT BEFORE IT REACHES THE NEEDLE AND JETS",
           [("Dirt on the seat", "Needle cannot close: flooding"),
            ("Jets", "Protected from blockage"),
            ("After the valve", "Too late to protect it")], None),
    2745: ("VS1: STALL SPEED IN A SPECIFIED (CLEAN) CONFIGURATION",
           "BOTTOM OF THE GREEN ARC",
           [("VS1", "Normally clean, flaps up"), ("VSO", "Landing configuration: bottom of white arc"),
            ("VX", "Best angle of climb")], None),
    2746: ("THE BALL SHOWS THE APPARENT VERTICAL",
           "WHERE GRAVITY AND SIDEWAYS FORCE COMBINE",
           [("Centred", "Coordinated"), ("Moved", "Slip or skid"),
            ("Does not show", "Bank angle, rate of turn or pitch")], None),
    2747: ("CLIMBING: THE MIXTURE BECOMES TOO RICH",
           "AIR DENSITY FALLS, BUT ABOUT THE SAME FUEL IS SUPPLIED",
           [("Carburettor", "Meters by air volume, not mass"),
            ("Less dense air", "Less oxygen per volume"),
            ("Action", "Lean in the climb and cruise")], None),
    2748: ("QFE: HEIGHT ABOVE THE AIRFIELD",
           "THE ALTIMETER READS ZERO ON THE AIRFIELD DATUM",
           [("QFE", "Height above the airfield"), ("QNH", "Altitude above mean sea level"),
            ("1013.25 hPa", "Pressure altitude / flight levels")], None),
    2750: ("THE VENT SYSTEM KEEPS THE TANK AT ATMOSPHERIC",
           "OUTSIDE AIR REPLACES THE FUEL AS IT IS USED",
           [("Without it", "Vacuum forms; fuel flow stops"),
            ("Also", "Lets the tank breathe with temperature"),
            ("Drains", "Remove water and sediment")], None),
    2754: ("SET THE ALTIMETER BEFORE EVERY FLIGHT",
           "AND UPDATE IT WHENEVER A NEW SETTING IS NEEDED EN ROUTE",
           [("Update when", "QNH changes, new region, transition, ATC"),
            ("Old setting", "Can put you hundreds of feet low"),
            ("Memory aid", "High to low, look out below")], None),
    2757: ("TUBELESS TYRE: STATEMENTS 1, 3 AND 4",
           "THE BEADS SEAL DIRECTLY AGAINST AN AIRTIGHT RIM",
           [("1. Airtight rim", "True"), ("2. Inner tube needed", "False"),
            ("3. No tube friction", "True"), ("4. Rim damage leaks", "True")], None),
    2759: ("T-TAIL: TAILPLANE CLEAR OF THE WING WAKE",
           "CLEANER, MORE CONSISTENT AIRFLOW IN NORMAL FLIGHT",
           [("Also", "Out of the propeller slipstream"),
            ("Bonus", "Acts as an end plate for the fin"),
            ("Watch", "Deep stall at very high angles of attack")], None),
    2762: ("MASS BALANCE PREVENTS FLUTTER",
           "CORRECT MASS DISTRIBUTION WITHIN THE CONTROL SURFACE",
           [("Mass balance", "Weight ahead of the hinge line"),
            ("Also", "No play in hinges and cables"),
            ("Tabs", "Reduce effort; do not prevent flutter")], None),
    2763: ("ROLL LEFT: THE NOSE FIRST YAWS RIGHT",
           "ADVERSE YAW, OPPOSITE THE DIRECTION OF ROLL",
           [("Down-going aileron", "More lift, more induced drag"),
            ("Result", "That wing is held back"),
            ("Correction", "Rudder with aileron; Frise or differential ailerons")], None),
    2764: ("FRISE AILERON: THE RAISED NOSE ADDS DRAG",
           "IT BALANCES THE DOWN-GOING AILERON'S EXTRA DRAG",
           [("Hinge", "Behind the aileron's leading edge"),
            ("Raised aileron", "Nose projects below the wing"),
            ("Differential ailerons", "Up-going aileron moves further")], None),
    2765: ("DI TAXI CHECK: LEFT DECREASES, RIGHT INCREASES",
           "HEADINGS INCREASE CLOCKWISE",
           [("Left turn", "Heading decreases"), ("Right turn", "Heading increases"),
            ("Constant or reversed", "Unserviceable")], None),
    2766: ("TORQUE LINKS KEEP THE NOSE WHEEL ALIGNED",
           "THEY STOP THE INNER AND OUTER STRUT MEMBERS ROTATING",
           [("Also called", "Scissor links"),
            ("Vertical movement", "Unrestricted"),
            ("Landing impact", "Absorbed by the oleo")], None),
    2768: ("THE BALL SHOWS SLIP OR SKID",
           "THE NEEDLE SHOWS RATE AND DIRECTION OF TURN",
           [("Ball centred", "Coordinated"), ("Ball inside", "Slipping"),
            ("Ball outside", "Skidding")], None),
    2771: ("THE ASI IS CALIBRATED FOR ISA SEA-LEVEL DENSITY",
           "1.225 kg/m3: ONLY THERE DOES IAS EQUAL TAS",
           [("Higher or warmer", "Lower density: ASI reads below TAS"),
            ("TAS", "Worked out from CAS, altitude and temperature"),
            ("Stall speeds", "Stay much the same in IAS")], None),
    2772: ("WET BLACK OILY PLUG: OIL IS BURNING",
           "OIL IS REACHING THE COMBUSTION CHAMBER",
           [("Common cause", "Worn rings or valve guides"),
            ("Found on", "Mostly the lower plugs"),
            ("Dry black soot", "Rich mixture instead")], None),
    2773: ("NO OIL PRESSURE IN TIME: SHUT DOWN AT ONCE",
           "THE ENGINE MAY BE RUNNING WITHOUT LUBRICATION",
           [("Normal", "Pressure within about 30 s (longer when very cold)"),
            ("Damage", "Can occur within a minute"),
            ("Investigate", "Low oil, failed pump or faulty gauge")], None),
})


def template(qid):
    """The explanation_visual_template JSON stored for a question."""
    import json
    headline, subline, blocks, formula = KF[qid]
    t = {"kicker": "KEY FACT", "headline": headline, "subline": subline,
         "blocks": [{"label": label, "value": value} for label, value in blocks]}
    if formula:
        t["formula"] = formula
    return json.dumps(t, ensure_ascii=False)


if __name__ == "__main__":
    # Print the aggregate hash the database should match.
    import hashlib
    agg = ",".join(f"{qid}:{template(qid)}" for qid in sorted(KF))
    print("expected aggregate:", hashlib.md5(agg.encode()).hexdigest())
    print("check with: select md5(string_agg(id::text || ':' || explanation_visual_template, ',' order by id)) "
          "from questions where subject = 'aircraft-technical-and-general' and explanation_visual_template is not null;")
