"use client"

import type { ReactNode } from "react"
import type { Question } from "../types"

type Concept =
  | "wing-polar" | "axes-controls" | "control-effects" | "stability" | "dihedral"
  | "directional-stability" | "longitudinal-dihedral" | "cg-stability" | "cg-cp"
  | "aerofoil" | "angle-of-attack" | "incidence-washout" | "boundary-layer" | "bernoulli"
  | "newton-laws" | "dynamic-pressure" | "lift-pressure" | "centre-pressure" | "aspect-ratio"
  | "lift-speed" | "drag-curves" | "skin-friction" | "induced-drag" | "four-forces"
  | "climb-forces" | "descent-power" | "flap-effects" | "fowler-flap" | "slat"
  | "glide-flap" | "glide-wind" | "adverse-yaw" | "trim-tab" | "balance-tab"
  | "anti-balance-tab" | "mass-balance" | "horn-balance" | "flutter" | "bank-load-factor"
  | "turn-forces" | "slip-skid" | "stall-speed-load" | "critical-aoa" | "stall-warning"
  | "stall-progression" | "spin" | "spin-recovery" | "airspeed-chain" | "v-speeds"
  | "va" | "vx-vy" | "isa" | "humidity-density" | "pressure-temp-density"
  | "propeller-effects" | "weight-cg"

type Spec = { concept: Concept; title: string; note: string }

const C = {
  navy: "#06111f",
  gold: "#f4b400",
  blue: "#1f4e79",
  grey: "#64748b",
  light: "#d7e0ea",
  pale: "#f8fafc",
  red: "#b91c1c",
  green: "#166534",
}

function txt(q: Question) {
  return `${q.question} ${q.correctAnswer}`.toLowerCase()
}
function has(q: Question, ...terms: string[]) {
  const t = txt(q)
  return terms.some(term => t.includes(term.toLowerCase()))
}

function getSpec(q: Question): Spec {
  const topic = q.topic ?? ""
  if (has(q, "wing polar", "polar diagram")) return { concept: "wing-polar", title: "READING A WING POLAR", note: "Read the supplied polar carefully: CLmax marks the critical angle of attack, while minimum drag and best L/D are separate operating points." }

  if (topic === "Aerofoils & Lift") {
    if (has(q, "boundary layer", "transition point", "laminar", "turbulent")) return { concept: "boundary-layer", title: "BOUNDARY LAYER & TRANSITION", note: "The boundary layer begins at the surface, may transition from laminar to turbulent flow, and can separate under an adverse pressure gradient." }
    if (has(q, "centre of pressure", "center of pressure")) return { concept: "centre-pressure", title: "CENTRE OF PRESSURE", note: "The centre of pressure is the point through which the resultant aerodynamic force is treated as acting." }
    if (has(q, "angle of attack", "relative airflow", "relative air flow")) return { concept: "angle-of-attack", title: "ANGLE OF ATTACK", note: "Angle of attack is the acute angle between the chord line and the relative airflow." }
    if (has(q, "chord line", "camber", "aerofoil", "airfoil", "leading edge", "trailing edge")) return { concept: "aerofoil", title: "AEROFOIL GEOMETRY", note: "The chord line joins the leading and trailing edges. Upper and lower camber describe the aerofoil shape around that reference." }
    if (has(q, "doubled", "four times", "v squared", "v²", "airspeed")) return { concept: "lift-speed", title: "LIFT & AIRSPEED", note: "With density, area and lift coefficient unchanged, lift varies with the square of true airspeed: L ∝ V²." }
    return { concept: "lift-pressure", title: "LIFT & PRESSURE DISTRIBUTION", note: "Lift acts perpendicular to the relative airflow and results from the pressure distribution around the aerofoil." }
  }

  if (topic === "Basic Aerodynamics") {
    if (has(q, "newton")) return { concept: "newton-laws", title: "NEWTON'S LAWS", note: "First law: inertia/equilibrium. Second law: force produces acceleration. Third law: action and reaction are equal and opposite." }
    if (has(q, "venturi", "bernoulli", "continuity", "cross-sectional area")) return { concept: "bernoulli", title: "VENTURI: CONTINUITY & BERNOULLI", note: "In a narrowing subsonic passage, velocity increases while static pressure decreases; mass flow remains constant." }
    if (has(q, "dynamic pressure", "total pressure", "static pressure", "stagnation")) return { concept: "dynamic-pressure", title: "STATIC, DYNAMIC & TOTAL PRESSURE", note: "Dynamic pressure q = ½ρV² and total pressure equals static pressure plus dynamic pressure." }
    if (has(q, "relative airflow")) return { concept: "angle-of-attack", title: "RELATIVE AIRFLOW", note: "Relative airflow is parallel and opposite to the aircraft's direction of movement through the air mass." }
    if (has(q, "torque", "asymmetric blade", "p-factor", "right rudder")) return { concept: "propeller-effects", title: "PROPELLER ASYMMETRIC EFFECTS", note: "Torque reaction and asymmetric blade effect can create roll and yaw, especially at high power and high angle of attack." }
    if (has(q, "laminar", "boundary layer")) return { concept: "boundary-layer", title: "LAMINAR & TURBULENT FLOW", note: "Laminar flow is orderly; a real boundary layer can contain both laminar and turbulent regions." }
    return { concept: "dynamic-pressure", title: "AIRFLOW ENERGY & PRESSURE", note: "Aerodynamic forces depend on air density, speed and pressure relationships." }
  }

  if (topic === "Drag") {
    if (has(q, "skin friction", "dust", "viscosity")) return { concept: "skin-friction", title: "SKIN-FRICTION DRAG", note: "Viscosity slows the airflow immediately adjacent to the surface. Roughness and wetted area increase skin-friction drag." }
    if (has(q, "washout", "wingtip", "pressure difference", "induced drag")) return { concept: "induced-drag", title: "INDUCED DRAG & WINGTIP FLOW", note: "The pressure difference across a lifting wing drives spanwise flow and wingtip vortices, producing induced drag." }
    if (has(q, "aspect ratio", "low aspect", "high aspect", "planform")) return { concept: "aspect-ratio", title: "ASPECT RATIO & INDUCED DRAG", note: "Higher aspect ratio generally reduces induced drag for a given lift." }
    return { concept: "drag-curves", title: "INDUCED, PARASITE & TOTAL DRAG", note: "Induced drag dominates at low speed; parasite drag dominates at high speed. Their sum gives the total-drag curve." }
  }

  if (topic === "Wing Design") {
    if (has(q, "aspect ratio")) return { concept: "aspect-ratio", title: "WING ASPECT RATIO", note: "Aspect ratio compares span with mean chord; higher aspect ratio generally reduces induced drag." }
    return { concept: "incidence-washout", title: "INCIDENCE, WASHOUT & ANHEDRAL", note: "Angle of incidence is measured to the aircraft reference line. Washout reduces incidence toward the tip; anhedral slopes the wings downward." }
  }

  if (topic === "Aileron Drag") return { concept: "adverse-yaw", title: "ADVERSE AILERON YAW", note: "The down-going aileron creates more lift and induced drag, tending to yaw the aircraft opposite the intended roll." }

  if (topic === "Flight Controls & Axes") {
    if (has(q, "primary and further", "followed by spiral", "further effects")) return { concept: "control-effects", title: "PRIMARY & FURTHER CONTROL EFFECTS", note: "A control first produces its primary rotation; aerodynamic coupling can then create secondary motion and a spiral tendency if uncorrected." }
    return { concept: "axes-controls", title: "AIRCRAFT AXES & PRIMARY CONTROLS", note: "Roll—longitudinal axis—ailerons. Pitch—lateral axis—elevator. Yaw—vertical axis—rudder." }
  }

  if (topic === "Four Forces") {
    if (has(q, "centre of gravity", "center of gravity", "centre of pressure", "center of pressure", "nose pitches", "power causes")) return { concept: "cg-cp", title: "CG, CENTRE OF PRESSURE & PITCHING MOMENT", note: "In a conventional light aircraft the CG is normally ahead of the centre of pressure, so the force couples create pitching moments." }
    return { concept: "four-forces", title: "FOUR FORCES IN LEVEL FLIGHT", note: "In steady straight-and-level flight at constant speed, lift equals weight and thrust equals drag." }
  }

  if (topic === "Stability") {
    if (has(q, "dihedral", "sideslip", "lower wing")) return { concept: "dihedral", title: "DIHEDRAL & LATERAL STABILITY", note: "In a sideslip, dihedral gives the lower wing a greater effective angle of attack, creating a restoring roll." }
    if (has(q, "vertical fin", "directional stability", "yawing plane", "keel surface")) return { concept: "directional-stability", title: "DIRECTIONAL STABILITY", note: "The vertical fin and other side area aft of the CG produce a weathercock restoring moment after a yaw disturbance." }
    if (has(q, "longitudinal dihedral", "tailplane", "pitching plane")) return { concept: "longitudinal-dihedral", title: "LONGITUDINAL DIHEDRAL", note: "The incidence relationship between wing and tailplane contributes to pitch stability." }
    if (has(q, "centre of gravity", "center of gravity", "forward cg", "aft cg", "forward limit", "aft limit")) return { concept: "cg-stability", title: "CENTRE OF GRAVITY & STABILITY", note: "Forward CG generally increases longitudinal stability and control force; aft CG reduces the stability margin." }
    return { concept: "stability", title: "STATIC & DYNAMIC STABILITY", note: "Static stability describes the initial tendency after disturbance; dynamic stability describes how the motion changes with time." }
  }

  if (topic === "Trim & Balance Tabs") {
    if (has(q, "anti-balance", "anti-servo")) return { concept: "anti-balance-tab", title: "ANTI-BALANCE / ANTI-SERVO TAB", note: "An anti-balance tab moves in the same direction as the main surface, increasing control force and feel." }
    if (has(q, "mass balance")) return { concept: "mass-balance", title: "MASS BALANCE", note: "A mass balance places mass ahead of the hinge line to reduce the tendency of a control surface to flutter." }
    if (has(q, "flutter")) return { concept: "flutter", title: "CONTROL FLUTTER", note: "Flutter is a self-excited aeroelastic oscillation. Correct mass balance and structural condition are critical to preventing it." }
    if (has(q, "horn balance", "hinge set back", "aerodynamically balanced")) return { concept: "horn-balance", title: "AERODYNAMIC / HORN BALANCE", note: "Area ahead of the hinge line reduces hinge moment and therefore pilot control force." }
    if (has(q, "balance tab")) return { concept: "balance-tab", title: "BALANCE TAB MOVEMENT", note: "A balance tab moves opposite to the main control surface so its aerodynamic force assists control movement." }
    return { concept: "trim-tab", title: "TRIM TAB PRINCIPLE", note: "A trim tab removes sustained pilot force by holding the main control surface at the required trimmed position." }
  }

  if (topic === "Flaps & Glide") {
    if (has(q, "fowler")) return { concept: "fowler-flap", title: "FOWLER FLAP", note: "A Fowler flap moves aft and then down, increasing wing area and camber." }
    if (has(q, "slot", "leading-edge")) return { concept: "slat", title: "LEADING-EDGE SLOT", note: "A leading-edge slot re-energises upper-surface airflow, delaying separation at high angle of attack." }
    if (has(q, "headwind", "tailwind", "ground glide")) return { concept: "glide-wind", title: "WIND EFFECT ON GLIDE", note: "Wind changes the glide path over the ground by changing groundspeed, not the rate of descent through the air mass at the same airspeed/configuration." }
    if (has(q, "glide", "l/d", "lift/drag", "rate of descent", "gliding angle")) return { concept: "glide-flap", title: "GLIDE PATH & FLAP EFFECT", note: "Flap extension normally reduces best L/D, steepens the glide path and increases rate of descent." }
    return { concept: "flap-effects", title: "TRAILING-EDGE FLAP EFFECTS", note: "Trailing-edge flaps increase camber and CLmax, increase drag, and reduce the angle of attack required for a given lift." }
  }

  if (topic === "Climb Performance") {
    if (has(q, "best angle", "best rate", "vx", "vy", "shortest distance", "shortest time")) return { concept: "vx-vy", title: "VX & VY", note: "VX gives greatest height gain per horizontal distance; VY gives greatest height gain per unit time." }
    return { concept: "climb-forces", title: "FORCES IN A STEADY CLIMB", note: "In a steady climb, thrust exceeds drag while lift is less than weight because part of weight acts along the flight path." }
  }

  if (topic === "Descent Performance") return { concept: "descent-power", title: "POWER & RATE OF DESCENT", note: "At constant airspeed, increasing power reduces rate of descent; reducing power increases it." }

  if (topic === "Turns & Load Factor") {
    if (has(q, "ball", "slipping", "skidding", "slip indicator")) return { concept: "slip-skid", title: "BALANCED, SLIPPING & SKIDDING TURNS", note: "Ball centred indicates a coordinated turn. In a left turn, ball left indicates a slip and ball right indicates a skid." }
    if (has(q, "stall speed", "stalls at", "square root", "wing loading", "minimum speed")) return { concept: "stall-speed-load", title: "STALL SPEED & LOAD FACTOR", note: "Stall speed varies with the square root of load factor: Vs₂ = Vs₁√n." }
    if (has(q, "60", "load factor", "bank angle", "gross weight", "structure support", "2.5 g", "3.8 g")) return { concept: "bank-load-factor", title: "BANK ANGLE & LOAD FACTOR", note: "In a coordinated level turn, n = 1/cosφ. Load rises rapidly beyond 45° of bank and is 2 G at 60°." }
    return { concept: "turn-forces", title: "LIFT COMPONENTS IN A LEVEL TURN", note: "The vertical lift component balances weight while the horizontal component provides centripetal force." }
  }

  if (topic === "Stalls") {
    if (has(q, "warning", "buffeting", "control effectiveness")) return { concept: "stall-warning", title: "STALL APPROACH & WARNING", note: "As critical angle is approached, controls become less effective and buffet or the installed warning system should warn before the full stall." }
    if (has(q, "washout", "wingtip", "root")) return { concept: "stall-progression", title: "ROOT-FIRST STALL PROGRESSION", note: "Washout reduces incidence toward the tip so the root stalls first, preserving aileron effectiveness longer." }
    if (has(q, "stall speed", "wing loading", "weight", "turn", "flap", "power")) return { concept: "stall-speed-load", title: "FACTORS AFFECTING STALL SPEED", note: "Critical angle remains essentially fixed for a given configuration, but the IAS at which it is reached changes with load factor, weight, flap and power." }
    return { concept: "critical-aoa", title: "CRITICAL ANGLE OF ATTACK", note: "A wing stalls because the critical angle of attack is exceeded, not because it reaches one particular airspeed." }
  }

  if (topic === "Spins") {
    if (has(q, "recovery", "rudder is applied", "rudder before")) return { concept: "spin-recovery", title: "SPIN RECOVERY PRINCIPLE", note: "Use the aircraft's approved procedure. Aerodynamically, stop the yaw and reduce angle of attack to unstall the wings." }
    return { concept: "spin", title: "SPIN AUTOROTATION", note: "A spin requires a stall plus yaw. The inner wing is more deeply stalled than the outer wing, sustaining autorotation." }
  }

  if (topic === "Airspeed") return { concept: "airspeed-chain", title: "IAS → CAS/RAS → TAS", note: "CAS/RAS corrects IAS for instrument and position error. TAS then corrects for the actual density/temperature-altitude condition." }

  if (topic === "Airspeed Limitations") {
    if (has(q, "manoeuvring", "maneuvering", "va")) return { concept: "va", title: "DESIGN MANOEUVRING SPEED VA", note: "At or below VA, a full abrupt single-axis input is intended to stall the wing before the positive limit load is exceeded. VA decreases with weight." }
    if (has(q, "vx", "vy", "best angle", "best rate")) return { concept: "vx-vy", title: "VX & VY", note: "VX is best angle of climb; VY is best rate of climb." }
    return { concept: "v-speeds", title: "V-SPEEDS & OPERATING LIMITS", note: "V-speeds identify approved limitations or performance reference speeds. Exact values are aircraft-specific." }
  }

  if (topic === "ISA & Air Density") {
    if (has(q, "humidity", "humid")) return { concept: "humidity-density", title: "HUMIDITY & AIR DENSITY", note: "At the same pressure and temperature, humid air is less dense than dry air." }
    if (has(q, "pressure", "temperature", "density") && !has(q, "sea-level density", "sea level density")) return { concept: "pressure-temp-density", title: "PRESSURE, TEMPERATURE & DENSITY", note: "Density increases with pressure and decreases as absolute temperature increases." }
    return { concept: "isa", title: "INTERNATIONAL STANDARD ATMOSPHERE", note: "ISA uses MSL temperature 15°C, pressure 1013.25 hPa and a tropospheric lapse rate of about 1.98°C per 1000 ft." }
  }

  if (topic === "Weight & Balance") return { concept: "weight-cg", title: "CENTRE OF GRAVITY", note: "The centre of gravity is the point through which the aircraft's total weight is considered to act." }
  return { concept: "four-forces", title: "PRINCIPLES OF FLIGHT", note: "Use the force directions and aerodynamic relationships shown together with the exact wording of the question." }
}

function Arrow({ x1, y1, x2, y2, color = C.gold, width = 4 }: { x1: number; y1: number; x2: number; y2: number; color?: string; width?: number }) {
  const a = Math.atan2(y2 - y1, x2 - x1)
  const h = 12
  const p1 = `${x2},${y2}`
  const p2 = `${x2 - h * Math.cos(a - Math.PI / 6)},${y2 - h * Math.sin(a - Math.PI / 6)}`
  const p3 = `${x2 - h * Math.cos(a + Math.PI / 6)},${y2 - h * Math.sin(a + Math.PI / 6)}`
  return <g><line x1={x1} y1={y1} x2={x2} y2={y2} stroke={color} strokeWidth={width} strokeLinecap="round"/><polygon points={`${p1} ${p2} ${p3}`} fill={color}/></g>
}

function Canvas({ children }: { children: ReactNode }) { return <div className="relative aspect-[16/7] w-full overflow-hidden bg-white"><svg viewBox="0 0 800 350" preserveAspectRatio="xMidYMid meet" className="absolute inset-0 h-full w-full" aria-hidden="true">{children}</svg></div> }

function Tag({ x, y, children, align = "center", tone = "navy", width }: { x: number; y: number; children: ReactNode; align?: "left" | "center" | "right"; tone?: "navy" | "gold" | "blue" | "grey" | "red" | "green"; width?: number }) {
  const color = tone === "gold" ? C.gold : tone === "blue" ? C.blue : tone === "grey" ? C.grey : tone === "red" ? C.red : tone === "green" ? C.green : C.navy
  const transform = align === "left" ? "translate(0,-50%)" : align === "right" ? "translate(-100%,-50%)" : "translate(-50%,-50%)"
  return <div className="pointer-events-none absolute z-10 rounded-sm bg-white/95 px-2 py-1 text-[9px] font-bold leading-tight shadow-[0_0_0_1px_rgba(226,232,240,.75)] sm:text-[11px]" style={{ left: `${x}%`, top: `${y}%`, transform, color, maxWidth: width ? `${width}%` : "30%", textAlign: align === "left" ? "left" : align === "right" ? "right" : "center" }}>{children}</div>
}

function TwoCard({ leftTitle, leftText, rightTitle, rightText }: { leftTitle: string; leftText: string; rightTitle: string; rightText: string }) {
  return <div className="grid min-h-[210px] grid-cols-2 gap-3 p-4 sm:gap-6 sm:p-8"><div className="flex flex-col justify-center border border-slate-200 bg-white p-4 text-center"><div className="text-xs font-extrabold text-[#06111f] sm:text-base">{leftTitle}</div><div className="mt-2 text-[10px] leading-relaxed text-slate-600 sm:text-sm">{leftText}</div></div><div className="flex flex-col justify-center border border-slate-200 bg-white p-4 text-center"><div className="text-xs font-extrabold text-[#06111f] sm:text-base">{rightTitle}</div><div className="mt-2 text-[10px] leading-relaxed text-slate-600 sm:text-sm">{rightText}</div></div></div>
}

function TechnicalDiagram({ concept }: { concept: Concept }) {
  switch (concept) {
    case "angle-of-attack": return <div className="relative"><Canvas><line x1="115" y1="270" x2="675" y2="270" stroke={C.blue} strokeWidth="4"/><polygon points="115,270 132,260 132,280" fill={C.blue}/><path d="M235 235 Q385 118 650 205 Q430 258 235 235Z" fill={C.pale} stroke={C.navy} strokeWidth="4"/><line x1="235" y1="235" x2="650" y2="205" stroke={C.gold} strokeWidth="3"/><path d="M250 265 A78 78 0 0 1 270 232" fill="none" stroke={C.gold} strokeWidth="6"/><line x1="305" y1="128" x2="330" y2="166" stroke={C.grey} strokeWidth="2"/><line x1="525" y1="95" x2="505" y2="190" stroke={C.grey} strokeWidth="2"/><line x1="535" y1="315" x2="525" y2="234" stroke={C.grey} strokeWidth="2"/><line x1="645" y1="315" x2="650" y2="205" stroke={C.grey} strokeWidth="2"/></Canvas><Tag x={39} y={31}>LEADING EDGE</Tag><Tag x={66} y={19}>CHORD LINE</Tag><Tag x={80} y={30}>UPPER CAMBER</Tag><Tag x={64} y={89}>LOWER CAMBER</Tag><Tag x={82} y={89}>TRAILING EDGE</Tag><Tag x={33} y={68} tone="gold" width={22}>α · ANGLE OF ATTACK</Tag><Tag x={36} y={79} tone="blue" width={28}>RELATIVE AIRFLOW ←</Tag></div>
    case "aerofoil": return <div className="relative"><Canvas><path d="M125 205 Q335 80 680 195 Q390 250 125 205Z" fill={C.pale} stroke={C.navy} strokeWidth="4"/><line x1="125" y1="205" x2="680" y2="195" stroke={C.blue} strokeWidth="2" strokeDasharray="8 6"/><line x1="395" y1="112" x2="395" y2="226" stroke={C.gold} strokeWidth="3"/></Canvas><Tag x={19} y={49}>LEADING EDGE</Tag><Tag x={84} y={48}>TRAILING EDGE</Tag><Tag x={51} y={70} tone="blue">CHORD LINE</Tag><Tag x={50} y={25} tone="gold">MAXIMUM THICKNESS</Tag><Tag x={59} y={38}>UPPER CAMBER</Tag><Tag x={59} y={62}>LOWER CAMBER</Tag></div>
    case "lift-pressure": return <div className="relative"><Canvas><path d="M145 205 Q350 90 665 195 Q390 250 145 205Z" fill={C.pale} stroke={C.navy} strokeWidth="4"/><Arrow x1={120} y1={292} x2={680} y2={292} color={C.blue}/><Arrow x1={405} y1={188} x2={405} y2={65}/><path d="M190 155 Q400 95 620 155" fill="none" stroke={C.blue} strokeWidth="2" strokeDasharray="7 6"/><path d="M190 240 Q400 285 620 235" fill="none" stroke={C.gold} strokeWidth="2" strokeDasharray="7 6"/></Canvas><Tag x={50} y={13} tone="blue">LOWER PRESSURE ABOVE</Tag><Tag x={50} y={76} tone="gold">HIGHER PRESSURE BELOW</Tag><Tag x={55} y={10}>LIFT</Tag><Tag x={50} y={88} tone="blue">RELATIVE AIRFLOW →</Tag></div>
    case "centre-pressure": return <div className="relative"><Canvas><path d="M145 205 Q350 90 665 195 Q390 250 145 205Z" fill={C.pale} stroke={C.navy} strokeWidth="4"/><circle cx="430" cy="198" r="10" fill={C.gold}/><Arrow x1={430} y1={185} x2={430} y2={70}/><Arrow x1={550} y1={290} x2={360} y2={290} color={C.blue}/></Canvas><Tag x={54} y={14}>RESULTANT AERODYNAMIC FORCE</Tag><Tag x={54} y={61} tone="gold">CENTRE OF PRESSURE</Tag><Tag x={72} y={84} tone="blue">INCREASING AoA → CP GENERALLY MOVES FORWARD</Tag></div>
    case "boundary-layer": return <div className="relative"><Canvas><path d="M100 245 Q360 125 700 220" fill="none" stroke={C.navy} strokeWidth="5"/><path d="M108 225 Q225 180 350 170" fill="none" stroke={C.blue} strokeWidth="2"/><path d="M108 205 Q230 150 350 150" fill="none" stroke={C.blue} strokeWidth="2"/><path d="M355 150 Q455 128 535 170" fill="none" stroke={C.gold} strokeWidth="3" strokeDasharray="7 5"/><path d="M545 178 Q620 140 700 170" fill="none" stroke={C.red} strokeWidth="3"/><Arrow x1={120} y1={300} x2={690} y2={300} color={C.grey}/></Canvas><Tag x={26} y={29}>LAMINAR REGION</Tag><Tag x={53} y={23} tone="gold">TRANSITION</Tag><Tag x={79} y={28} tone="red">SEPARATION</Tag><Tag x={50} y={88} tone="grey">FLOW DIRECTION →</Tag></div>
    case "wing-polar": return <div className="relative"><Canvas><line x1="115" y1="285" x2="700" y2="285" stroke={C.navy} strokeWidth="3"/><line x1="115" y1="285" x2="115" y2="55" stroke={C.navy} strokeWidth="3"/><path d="M140 272 C220 215 300 160 385 118 C475 75 555 70 650 108" fill="none" stroke={C.blue} strokeWidth="5"/><circle cx="550" cy="80" r="8" fill={C.gold}/><circle cx="315" cy="150" r="8" fill={C.gold}/></Canvas><Tag x={69} y={16} tone="gold">CLmax / CRITICAL AoA</Tag><Tag x={40} y={35} tone="gold">BEST L/D REGION</Tag><Tag x={50} y={90}>ANGLE OF ATTACK →</Tag><Tag x={8} y={50}>CL</Tag></div>
    case "lift-speed": return <div className="relative"><Canvas><line x1="115" y1="285" x2="700" y2="285" stroke={C.navy} strokeWidth="3"/><line x1="115" y1="285" x2="115" y2="55" stroke={C.navy} strokeWidth="3"/><path d="M135 270 Q310 240 440 175 Q570 108 670 68" fill="none" stroke={C.gold} strokeWidth="5"/></Canvas><Tag x={52} y={24} tone="gold">L ∝ V²</Tag><Tag x={51} y={91}>TRUE AIRSPEED V →</Tag><Tag x={8} y={50}>LIFT</Tag></div>
    case "newton-laws": return <div className="grid min-h-[220px] grid-cols-3 gap-2 p-3 sm:gap-5 sm:p-8"><div className="border border-slate-200 p-3 text-center"><b>1st LAW</b><div className="mt-2 text-xs text-slate-600">Inertia / equilibrium: motion remains unchanged unless a net force acts.</div></div><div className="border border-slate-200 p-3 text-center"><b>2nd LAW</b><div className="mt-2 text-xs text-slate-600">Force produces acceleration: F = m × a.</div></div><div className="border border-slate-200 p-3 text-center"><b>3rd LAW</b><div className="mt-2 text-xs text-slate-600">Every action has an equal and opposite reaction.</div></div></div>
    case "bernoulli": return <div className="relative"><Canvas><path d="M80 115 L300 115 L385 165 L300 215 L80 215Z" fill={C.pale} stroke={C.navy} strokeWidth="3"/><path d="M720 115 L500 115 L415 165 L500 215 L720 215Z" fill={C.pale} stroke={C.navy} strokeWidth="3"/><Arrow x1={110} y1={165} x2={690} y2={165} color={C.blue}/></Canvas><Tag x={23} y={78}>WIDE SECTION<br/>LOWER V · HIGHER STATIC P</Tag><Tag x={50} y={19} tone="gold">THROAT<br/>HIGHER V · LOWER STATIC P</Tag><Tag x={77} y={78}>WIDE SECTION<br/>PRESSURE RECOVERS</Tag></div>
    case "dynamic-pressure": return <div className="px-4 py-6 sm:px-8"><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-3"><div className="border border-slate-200 p-4 text-center"><div className="font-bold">STATIC PRESSURE</div><div className="mt-1 text-xs text-slate-500">ambient pressure</div></div><div className="text-xl font-black text-[#f4b400]">+</div><div className="border border-slate-200 p-4 text-center"><div className="font-bold">DYNAMIC PRESSURE</div><div className="mt-1 text-xs text-slate-500">q = ½ρV²</div></div></div><div className="mt-5 text-center text-sm font-bold text-[#1f4e79]">TOTAL PRESSURE = STATIC + DYNAMIC</div></div>
    case "drag-curves": return <div className="relative"><Canvas><line x1="110" y1="285" x2="700" y2="285" stroke={C.navy} strokeWidth="3"/><line x1="110" y1="285" x2="110" y2="55" stroke={C.navy} strokeWidth="3"/><path d="M130 75 Q250 175 390 255 Q500 280 680 280" fill="none" stroke={C.blue} strokeWidth="4"/><path d="M130 280 Q360 278 500 195 Q605 130 680 75" fill="none" stroke={C.gold} strokeWidth="4"/><path d="M130 105 Q330 260 470 220 Q585 180 680 110" fill="none" stroke={C.navy} strokeWidth="5"/></Canvas><Tag x={26} y={24} tone="blue">INDUCED DRAG</Tag><Tag x={78} y={24} tone="gold">PARASITE DRAG</Tag><Tag x={63} y={50}>TOTAL DRAG</Tag><Tag x={51} y={91}>AIRSPEED →</Tag><Tag x={8} y={50}>DRAG</Tag></div>
    case "skin-friction": return <div className="relative"><Canvas><line x1="95" y1="220" x2="705" y2="220" stroke={C.navy} strokeWidth="6"/><path d="M110 208 C250 195 390 194 520 188 C610 184 660 174 700 160" fill="none" stroke={C.blue} strokeWidth="3"/><path d="M110 183 C255 160 410 160 540 150 C620 145 670 132 700 120" fill="none" stroke={C.blue} strokeWidth="2"/><Arrow x1={115} y1={95} x2={690} y2={95} color={C.grey}/></Canvas><Tag x={50} y={19} tone="grey">FREE-STREAM AIRFLOW</Tag><Tag x={31} y={72}>VELOCITY APPROACHES ZERO AT THE SURFACE</Tag><Tag x={75} y={72} tone="gold">SKIN FRICTION</Tag></div>
    case "induced-drag": return <div className="relative"><Canvas><line x1="155" y1="170" x2="645" y2="170" stroke={C.navy} strokeWidth="10"/><path d="M155 185 C110 205 110 275 165 292 C215 305 235 250 198 218" fill="none" stroke={C.blue} strokeWidth="4"/><path d="M645 185 C690 205 690 275 635 292 C585 305 565 250 602 218" fill="none" stroke={C.blue} strokeWidth="4"/></Canvas><Tag x={50} y={22} tone="blue">LOW PRESSURE ABOVE</Tag><Tag x={50} y={62} tone="gold">HIGH PRESSURE BELOW</Tag><Tag x={50} y={88}>SPANWISE FLOW → WINGTIP VORTICES → INDUCED DRAG</Tag></div>
    case "aspect-ratio": return <div className="grid min-h-[220px] grid-cols-2 gap-4 p-4 sm:gap-8 sm:p-8"><div className="flex flex-col items-center justify-center"><div className="h-12 w-[85%] border-2 border-[#06111f] bg-slate-50"/><div className="mt-4 text-center text-xs font-extrabold sm:text-sm">HIGH ASPECT RATIO</div><div className="mt-1 text-center text-[10px] text-slate-600 sm:text-xs">Long span / narrow chord · less induced drag</div></div><div className="flex flex-col items-center justify-center"><div className="h-24 w-[42%] border-2 border-[#06111f] bg-slate-50"/><div className="mt-4 text-center text-xs font-extrabold sm:text-sm">LOW ASPECT RATIO</div><div className="mt-1 text-center text-[10px] text-slate-600 sm:text-xs">Shorter span / wider chord · more induced drag</div></div></div>
    case "incidence-washout": return <div className="relative"><Canvas><line x1="85" y1="275" x2="715" y2="275" stroke={C.light} strokeWidth="2"/><line x1="130" y1="225" x2="370" y2="180" stroke={C.navy} strokeWidth="6"/><path d="M170 270 A70 70 0 0 1 195 215" fill="none" stroke={C.gold} strokeWidth="5"/><line x1="475" y1="175" x2="700" y2="210" stroke={C.navy} strokeWidth="7"/><line x1="475" y1="175" x2="475" y2="125" stroke={C.grey} strokeWidth="2"/><line x1="700" y1="210" x2="700" y2="165" stroke={C.grey} strokeWidth="2"/></Canvas><Tag x={30} y={34} tone="gold">ANGLE OF INCIDENCE</Tag><Tag x={72} y={29}>WASHOUT: INCIDENCE DECREASES TOWARD TIP</Tag><Tag x={50} y={89} tone="grey">ANHEDRAL = WING SLOPES DOWNWARD FROM ROOT TO TIP</Tag></div>
    case "axes-controls": return <div className="relative"><Canvas><path d="M330 85 L470 85 L485 150 L675 185 L485 220 L470 285 L330 285 L315 220 L125 185 L315 150Z" fill={C.pale} stroke={C.navy} strokeWidth="3"/><circle cx="400" cy="185" r="8" fill={C.gold}/><Arrow x1={130} y1={185} x2={670} y2={185} color={C.blue}/><Arrow x1={400} y1={315} x2={400} y2={55} color={C.blue}/><Arrow x1={250} y1={300} x2={550} y2={70} color={C.grey}/></Canvas><Tag x={50} y={50} tone="gold">CG</Tag><Tag x={78} y={41} tone="blue">LONGITUDINAL AXIS · ROLL · AILERONS</Tag><Tag x={62} y={18} tone="blue">VERTICAL AXIS · YAW · RUDDER</Tag><Tag x={26} y={83} tone="grey">LATERAL AXIS · PITCH · ELEVATOR</Tag></div>
    case "control-effects": return <div className="grid min-h-[220px] grid-cols-3 gap-2 p-3 sm:gap-5 sm:p-8"><div className="border border-slate-200 p-3 text-center"><b>AILERON</b><div className="mt-2 text-xs text-slate-600">Roll first<br/>then yaw coupling</div></div><div className="border border-slate-200 p-3 text-center"><b>RUDDER</b><div className="mt-2 text-xs text-slate-600">Yaw first<br/>then roll coupling</div></div><div className="border border-slate-200 p-3 text-center"><b>ELEVATOR</b><div className="mt-2 text-xs text-slate-600">Pitch about<br/>lateral axis</div></div><div className="col-span-3 text-center text-xs font-bold text-[#64748b]">If coupled motion is left uncorrected, a spiral tendency can develop.</div></div>
    case "adverse-yaw": return <div className="relative"><Canvas><line x1="110" y1="170" x2="690" y2="170" stroke={C.navy} strokeWidth="10"/><line x1="110" y1="170" x2="205" y2="118" stroke={C.gold} strokeWidth="10"/><line x1="595" y1="170" x2="690" y2="200" stroke={C.gold} strokeWidth="10"/><Arrow x1={485} y1={285} x2={315} y2={285} color={C.red}/></Canvas><Tag x={20} y={26}>UP AILERON<br/>LESS LIFT / DRAG</Tag><Tag x={80} y={69}>DOWN AILERON<br/>MORE LIFT / INDUCED DRAG</Tag><Tag x={60} y={84} tone="red">YAW OPPOSITE THE INTENDED ROLL</Tag></div>
    case "stability": return <div className="relative"><Canvas><line x1="85" y1="205" x2="715" y2="205" stroke={C.light} strokeWidth="2"/><path d="M100 205 C170 95 230 95 295 205 C360 270 420 245 480 205 C535 173 590 188 655 205" fill="none" stroke={C.blue} strokeWidth="4"/></Canvas><Tag x={22} y={22} tone="gold">INITIAL RESTORING TENDENCY</Tag><Tag x={72} y={69} tone="blue">OSCILLATIONS DECAY</Tag><Tag x={50} y={88}>POSITIVE STATIC + POSITIVE DYNAMIC STABILITY</Tag></div>
    case "dihedral": return <div className="relative"><Canvas><line x1="400" y1="200" x2="225" y2="130" stroke={C.navy} strokeWidth="8"/><line x1="400" y1="200" x2="575" y2="130" stroke={C.navy} strokeWidth="8"/><Arrow x1={100} y1={255} x2={250} y2={190} color={C.blue}/><Arrow x1={250} y1={170} x2={250} y2={82}/><Arrow x1={550} y1={170} x2={550} y2={120} color={C.grey}/><path d="M330 270 Q400 310 470 270" fill="none" stroke={C.gold} strokeWidth="5"/></Canvas><Tag x={18} y={76} tone="blue">SIDESLIP</Tag><Tag x={31} y={18}>MORE LIFT</Tag><Tag x={69} y={28} tone="grey">LESS LIFT</Tag><Tag x={50} y={88} tone="gold">RESTORING ROLL</Tag></div>
    case "directional-stability": return <div className="relative"><Canvas><path d="M170 190 L520 190 L610 210 L520 230 L170 230 L110 210Z" fill={C.pale} stroke={C.navy} strokeWidth="3"/><path d="M515 190 L555 90 L590 98 L580 195Z" fill="white" stroke={C.navy} strokeWidth="3"/><circle cx="335" cy="210" r="8" fill={C.gold}/><Arrow x1={680} y1={115} x2={595} y2={165} color={C.blue}/><path d="M365 290 A100 100 0 0 0 485 260" fill="none" stroke={C.gold} strokeWidth="5"/></Canvas><Tag x={42} y={52} tone="gold">CG</Tag><Tag x={83} y={23} tone="blue">SIDE GUST</Tag><Tag x={65} y={84} tone="gold">WEATHERCOCK RESTORING MOMENT</Tag></div>
    case "longitudinal-dihedral": return <div className="relative"><Canvas><line x1="165" y1="170" x2="495" y2="150" stroke={C.navy} strokeWidth="8"/><line x1="545" y1="220" x2="695" y2="235" stroke={C.blue} strokeWidth="7"/><line x1="105" y1="260" x2="710" y2="260" stroke={C.light} strokeWidth="2"/><Arrow x1={620} y1={205} x2={620} y2={140}/></Canvas><Tag x={40} y={30}>MAINPLANE INCIDENCE</Tag><Tag x={77} y={77} tone="blue">TAILPLANE INCIDENCE</Tag><Tag x={77} y={30} tone="gold">TAIL FORCE CHANGE</Tag></div>
    case "cg-stability": return <div className="relative"><Canvas><line x1="120" y1="190" x2="680" y2="190" stroke={C.navy} strokeWidth="5"/><circle cx="305" cy="190" r="10" fill={C.gold}/><circle cx="455" cy="190" r="10" fill={C.blue}/><Arrow x1={305} y1={120} x2={305} y2={70} color={C.blue}/><Arrow x1={455} y1={260} x2={455} y2={315} color={C.grey}/></Canvas><Tag x={38} y={43} tone="gold">FORWARD CG</Tag><Tag x={57} y={58} tone="blue">AFT CG</Tag><Tag x={29} y={14} tone="blue">MORE STABILITY / MORE CONTROL FORCE</Tag><Tag x={70} y={89} tone="grey">LESS STABILITY MARGIN</Tag></div>
    case "cg-cp": return <div className="relative"><Canvas><path d="M170 190 Q380 130 635 185 Q400 235 170 190Z" fill={C.pale} stroke={C.navy} strokeWidth="3"/><circle cx="335" cy="190" r="9" fill={C.gold}/><circle cx="455" cy="185" r="9" fill={C.blue}/><Arrow x1={455} y1={175} x2={455} y2={75}/><Arrow x1={335} y1={200} x2={335} y2={300} color={C.grey}/></Canvas><Tag x={42} y={46} tone="gold">CG</Tag><Tag x={57} y={45} tone="blue">CP</Tag><Tag x={61} y={13}>LIFT</Tag><Tag x={36} y={88} tone="grey">WEIGHT</Tag><Tag x={50} y={91}>CONVENTIONAL ARRANGEMENT: CG NORMALLY AHEAD OF CP</Tag></div>
    case "four-forces": return <div className="relative"><Canvas><path d="M280 175 L515 175 L570 190 L515 205 L280 205 L225 190Z" fill={C.pale} stroke={C.navy} strokeWidth="3"/><Arrow x1={400} y1={175} x2={400} y2={65}/><Arrow x1={400} y1={205} x2={400} y2={315} color={C.blue}/><Arrow x1={515} y1={190} x2={700} y2={190}/><Arrow x1={280} y1={190} x2={95} y2={190} color={C.blue}/></Canvas><Tag x={50} y={12}>LIFT</Tag><Tag x={50} y={90} tone="blue">WEIGHT</Tag><Tag x={81} y={47}>THRUST</Tag><Tag x={19} y={47} tone="blue">DRAG</Tag></div>
    case "climb-forces": return <div className="relative"><Canvas><line x1="180" y1="260" x2="620" y2="115" stroke={C.grey} strokeWidth="3" strokeDasharray="8 6"/><path d="M315 210 L500 150" stroke={C.navy} strokeWidth="8"/><Arrow x1={455} y1={165} x2={625} y2={108}/><Arrow x1={355} y1={195} x2={215} y2={240} color={C.blue}/><Arrow x1={405} y1={180} x2={405} y2={70}/><Arrow x1={405} y1={200} x2={405} y2={320} color={C.grey}/></Canvas><Tag x={82} y={20}>THRUST</Tag><Tag x={23} y={76} tone="blue">DRAG</Tag><Tag x={50} y={14}>LIFT</Tag><Tag x={50} y={91} tone="grey">WEIGHT</Tag></div>
    case "descent-power": return <div className="relative"><Canvas><line x1="100" y1="95" x2="700" y2="285" stroke={C.light} strokeWidth="3"/><path d="M205 135 L390 195" stroke={C.navy} strokeWidth="8"/><Arrow x1={390} y1={195} x2={550} y2={245}/></Canvas><Tag x={73} y={77}>FLIGHT PATH</Tag><Tag x={29} y={84} tone="blue">POWER ↓ → RATE OF DESCENT ↑</Tag><Tag x={69} y={28} tone="gold">POWER ↑ → RATE OF DESCENT ↓</Tag></div>
    case "flap-effects": return <div className="relative"><Canvas><path d="M90 150 Q210 105 345 145 Q220 185 90 150Z" fill={C.pale} stroke={C.navy} strokeWidth="3"/><path d="M455 150 Q575 105 685 145 Q580 187 455 150Z" fill={C.pale} stroke={C.navy} strokeWidth="3"/><line x1="615" y1="150" x2="690" y2="205" stroke={C.gold} strokeWidth="10"/></Canvas><Tag x={27} y={18}>CLEAN WING</Tag><Tag x={73} y={18} tone="gold">FLAP EXTENDED</Tag><Tag x={72} y={75} tone="gold">CAMBER ↑ · CLmax ↑ · DRAG ↑</Tag><Tag x={27} y={75}>BEST L/D HIGHER WHEN CLEAN</Tag></div>
    case "fowler-flap": return <div className="relative"><Canvas><path d="M115 180 Q325 105 570 170 Q360 210 115 180Z" fill={C.pale} stroke={C.navy} strokeWidth="3"/><path d="M520 172 L655 210" fill="none" stroke={C.gold} strokeWidth="12" strokeLinecap="round"/><Arrow x1={525} y1={250} x2={635} y2={250} color={C.blue}/></Canvas><Tag x={50} y={20}>WING AREA + CAMBER INCREASE</Tag><Tag x={72} y={79} tone="blue">FLAP MOVES AFT, THEN DOWN</Tag></div>
    case "slat": return <div className="relative"><Canvas><path d="M185 205 Q370 95 655 185 Q405 235 185 205Z" fill={C.pale} stroke={C.navy} strokeWidth="3"/><path d="M145 198 Q165 150 215 150" fill="none" stroke={C.gold} strokeWidth="11" strokeLinecap="round"/><Arrow x1={80} y1={145} x2={215} y2={170} color={C.blue}/><Arrow x1={220} y1={170} x2={390} y2={125} color={C.blue}/></Canvas><Tag x={30} y={22} tone="blue">ENERGISED AIR THROUGH SLOT</Tag><Tag x={65} y={76}>SEPARATION DELAYED TO HIGHER AoA</Tag></div>
    case "glide-flap": return <div className="relative"><Canvas><line x1="105" y1="100" x2="690" y2="300" stroke={C.light} strokeWidth="2"/><line x1="120" y1="105" x2="680" y2="230" stroke={C.blue} strokeWidth="4"/><line x1="120" y1="105" x2="585" y2="285" stroke={C.gold} strokeWidth="5"/></Canvas><Tag x={73} y={58} tone="blue">CLEAN: SHALLOWER GLIDE</Tag><Tag x={63} y={84} tone="gold">FLAP: STEEPER GLIDE</Tag><Tag x={50} y={14}>FLAP EXTENSION REDUCES BEST L/D</Tag></div>
    case "glide-wind": return <div className="relative"><Canvas><line x1="105" y1="285" x2="695" y2="285" stroke={C.navy} strokeWidth="3"/><path d="M140 85 L410 260" fill="none" stroke={C.gold} strokeWidth="4"/><path d="M140 85 L635 260" fill="none" stroke={C.blue} strokeWidth="4"/><Arrow x1={300} y1={60} x2={170} y2={60} color={C.grey}/></Canvas><Tag x={25} y={13} tone="grey">HEADWIND ←</Tag><Tag x={47} y={72} tone="gold">STEEPER PATH OVER GROUND</Tag><Tag x={75} y={72} tone="blue">TAILWIND: SHALLOWER OVER GROUND</Tag></div>
    case "trim-tab": return <div className="relative"><Canvas><line x1="125" y1="175" x2="610" y2="175" stroke={C.navy} strokeWidth="12"/><line x1="545" y1="175" x2="670" y2="205" stroke={C.gold} strokeWidth="9"/></Canvas><Tag x={42} y={35}>MAIN CONTROL SURFACE</Tag><Tag x={80} y={66} tone="gold">TRIM TAB</Tag><Tag x={50} y={87} tone="grey">TAB FORCE HOLDS THE SURFACE AT THE TRIMMED POSITION</Tag></div>
    case "balance-tab": return <div className="relative"><Canvas><line x1="120" y1="175" x2="610" y2="205" stroke={C.navy} strokeWidth="12"/><line x1="545" y1="200" x2="675" y2="150" stroke={C.gold} strokeWidth="9"/><Arrow x1={300} y1={115} x2={300} y2={165} color={C.blue}/><Arrow x1={630} y1={230} x2={630} y2={170}/></Canvas><Tag x={37} y={23} tone="blue">MAIN SURFACE DOWN</Tag><Tag x={79} y={73} tone="gold">BALANCE TAB MOVES OPPOSITE</Tag></div>
    case "anti-balance-tab": return <div className="relative"><Canvas><line x1="120" y1="175" x2="610" y2="205" stroke={C.navy} strokeWidth="12"/><line x1="545" y1="200" x2="675" y2="230" stroke={C.gold} strokeWidth="9"/><Arrow x1={300} y1={115} x2={300} y2={165} color={C.blue}/><Arrow x1={630} y1={165} x2={630} y2={220}/></Canvas><Tag x={37} y={23} tone="blue">MAIN SURFACE DOWN</Tag><Tag x={79} y={77} tone="gold">ANTI-BALANCE TAB MOVES SAME DIRECTION</Tag></div>
    case "mass-balance": return <div className="relative"><Canvas><line x1="170" y1="180" x2="650" y2="180" stroke={C.navy} strokeWidth="12"/><line x1="335" y1="105" x2="335" y2="255" stroke={C.blue} strokeWidth="3"/><circle cx="270" cy="180" r="25" fill={C.gold}/></Canvas><Tag x={42} y={22} tone="blue">HINGE LINE</Tag><Tag x={29} y={70} tone="gold">MASS AHEAD OF HINGE</Tag><Tag x={68} y={70}>REDUCES FLUTTER TENDENCY</Tag></div>
    case "horn-balance": return <div className="relative"><Canvas><line x1="245" y1="110" x2="245" y2="290" stroke={C.blue} strokeWidth="3"/><path d="M245 135 L650 175 L650 235 L245 215Z" fill={C.pale} stroke={C.navy} strokeWidth="3"/><path d="M190 120 L275 135 L260 190 L195 175Z" fill="white" stroke={C.gold} strokeWidth="4"/></Canvas><Tag x={31} y={22} tone="blue">HINGE LINE</Tag><Tag x={21} y={65} tone="gold">AREA AHEAD OF HINGE</Tag><Tag x={65} y={83}>REDUCES PILOT CONTROL FORCE</Tag></div>
    case "flutter": return <div className="relative"><Canvas><line x1="120" y1="185" x2="680" y2="185" stroke={C.navy} strokeWidth="9"/><path d="M470 185 C500 95 530 270 560 115 C590 265 620 100 660 180" fill="none" stroke={C.red} strokeWidth="4"/><Arrow x1={170} y1={270} x2={310} y2={270} color={C.blue}/></Canvas><Tag x={72} y={22} tone="red">OSCILLATION AMPLITUDE GROWS</Tag><Tag x={30} y={79} tone="blue">AIRFLOW / ENERGY</Tag><Tag x={50} y={12} tone="grey">AEROELASTIC COUPLING CAN BECOME SELF-EXCITING</Tag></div>
    case "bank-load-factor": return <div className="relative"><Canvas><line x1="110" y1="285" x2="690" y2="285" stroke={C.navy} strokeWidth="3"/><line x1="110" y1="285" x2="110" y2="55" stroke={C.navy} strokeWidth="3"/><path d="M125 275 C350 270 470 240 555 175 C610 130 650 85 675 55" fill="none" stroke={C.gold} strokeWidth="5"/><line x1="555" y1="175" x2="555" y2="285" stroke={C.blue} strokeWidth="2" strokeDasharray="6 5"/></Canvas><Tag x={69} y={40} tone="gold">60° BANK = 2 G</Tag><Tag x={32} y={20} tone="blue">n = 1 / cos φ</Tag><Tag x={51} y={91}>BANK ANGLE φ →</Tag><Tag x={8} y={50}>LOAD n</Tag></div>
    case "turn-forces": return <div className="relative"><Canvas><circle cx="390" cy="200" r="7" fill={C.navy}/><Arrow x1={390} y1={200} x2={525} y2={75}/><Arrow x1={390} y1={200} x2={390} y2={75} color={C.blue}/><Arrow x1={390} y1={200} x2={525} y2={200}/><Arrow x1={390} y1={200} x2={390} y2={315} color={C.grey}/></Canvas><Tag x={73} y={14}>TOTAL LIFT</Tag><Tag x={36} y={14} tone="blue">VERTICAL COMPONENT</Tag><Tag x={74} y={55}>CENTRIPETAL COMPONENT</Tag><Tag x={50} y={91} tone="grey">WEIGHT</Tag></div>
    case "slip-skid": return <div className="grid min-h-[220px] grid-cols-3 gap-2 p-3 sm:gap-5 sm:p-8">{[["BALANCED",50],["SLIP",25],["SKID",75]].map(([name,pos]) => <div key={String(name)} className="flex flex-col items-center justify-center border border-slate-200 p-2"><div className="relative h-24 w-full max-w-[150px] border-b-2 border-slate-400"><div className="absolute bottom-[-9px] h-4 w-4 rounded-full bg-[#f4b400]" style={{ left: `${Number(pos)}%`, transform:"translateX(-50%)" }}/></div><div className="mt-5 text-xs font-extrabold">{name}</div></div>)}</div>
    case "stall-speed-load": return <div className="relative"><Canvas><line x1="120" y1="285" x2="690" y2="285" stroke={C.navy} strokeWidth="3"/><line x1="120" y1="285" x2="120" y2="55" stroke={C.navy} strokeWidth="3"/><path d="M140 260 Q315 225 450 165 Q575 110 665 75" fill="none" stroke={C.gold} strokeWidth="5"/></Canvas><Tag x={63} y={25} tone="gold">Vs ∝ √n</Tag><Tag x={51} y={91}>LOAD FACTOR n →</Tag><Tag x={8} y={50}>STALL SPEED</Tag></div>
    case "critical-aoa": return <div className="relative"><Canvas><line x1="150" y1="270" x2="670" y2="270" stroke={C.blue} strokeWidth="4"/><line x1="205" y1="245" x2="630" y2="145" stroke={C.navy} strokeWidth="5"/><path d="M270 263 A75 75 0 0 1 291 226" fill="none" stroke={C.gold} strokeWidth="5"/><path d="M350 135 Q470 70 625 130" fill="none" stroke={C.red} strokeWidth="3" strokeDasharray="7 5"/></Canvas><Tag x={39} y={58} tone="gold">CRITICAL AoA</Tag><Tag x={65} y={19} tone="red">SEPARATION INCREASES</Tag><Tag x={50} y={90}>STALL OCCURS WHEN CRITICAL AoA IS EXCEEDED</Tag></div>
    case "stall-warning": return <div className="relative"><Canvas><path d="M145 210 Q350 110 660 195 Q390 245 145 210Z" fill={C.pale} stroke={C.navy} strokeWidth="3"/><path d="M420 135 Q520 95 650 145" fill="none" stroke={C.red} strokeWidth="3" strokeDasharray="7 5"/><Arrow x1={150} y1={285} x2={665} y2={285} color={C.blue}/></Canvas><Tag x={66} y={23} tone="red">BUFFET / FLOW SEPARATION</Tag><Tag x={30} y={20}>APPROACHING STALL<br/>CONTROL EFFECTIVENESS REDUCES</Tag><Tag x={50} y={90}>WARNING SHOULD OCCUR BEFORE THE FULL STALL</Tag></div>
    case "stall-progression": return <div className="relative"><Canvas><path d="M115 185 L685 185 L625 235 L175 235Z" fill={C.pale} stroke={C.navy} strokeWidth="3"/><rect x="330" y="175" width="140" height="70" fill="#fee2e2" stroke={C.red} strokeWidth="2"/></Canvas><Tag x={50} y={37} tone="red">ROOT STALLS FIRST</Tag><Tag x={23} y={75}>TIP STILL FLYING</Tag><Tag x={77} y={75}>AILERON EFFECT RETAINED</Tag><Tag x={50} y={90}>WASHOUT REDUCES INCIDENCE TOWARD THE TIP</Tag></div>
    case "spin": return <div className="relative"><Canvas><circle cx="400" cy="190" r="100" fill="none" stroke={C.light} strokeWidth="3" strokeDasharray="7 5"/><path d="M315 170 L485 215" stroke={C.navy} strokeWidth="10"/><Arrow x1={480} y1={95} x2={540} y2={145} color={C.gold}/><Arrow x1={530} y1={240} x2={470} y2={290} color={C.gold}/></Canvas><Tag x={31} y={27} tone="red">INNER WING<br/>MORE DEEPLY STALLED</Tag><Tag x={72} y={82} tone="gold">AUTOROTATION</Tag><Tag x={50} y={90}>STALL + YAW = SPIN</Tag></div>
    case "spin-recovery": return <div className="grid min-h-[210px] grid-cols-3 gap-2 p-3 sm:gap-5 sm:p-8"><div className="border border-slate-200 p-3 text-center"><b>1 · POWER</b><div className="mt-2 text-xs text-slate-600">As specified by the approved procedure</div></div><div className="border border-slate-200 p-3 text-center"><b>2 · OPPOSITE RUDDER</b><div className="mt-2 text-xs text-slate-600">Stop the yaw / rotation</div></div><div className="border border-slate-200 p-3 text-center"><b>3 · REDUCE AoA</b><div className="mt-2 text-xs text-slate-600">Unstall the wings, then recover smoothly</div></div></div>
    case "airspeed-chain": return <div className="grid min-h-[210px] grid-cols-[1fr_auto_1fr_auto_1fr] items-center gap-2 p-3 sm:gap-4 sm:p-8"><div className="border border-slate-200 p-3 text-center"><b>IAS</b><div className="mt-1 text-[10px] text-slate-500">instrument reading</div></div><div className="font-black text-[#f4b400]">→</div><div className="border border-slate-200 p-3 text-center"><b>CAS / RAS</b><div className="mt-1 text-[10px] text-slate-500">instrument + position corrected</div></div><div className="font-black text-[#f4b400]">→</div><div className="border border-slate-200 p-3 text-center"><b>TAS</b><div className="mt-1 text-[10px] text-slate-500">density / temp-alt corrected</div></div></div>
    case "v-speeds": return <div className="relative"><Canvas><line x1="100" y1="185" x2="700" y2="185" stroke={C.navy} strokeWidth="8"/><line x1="180" y1="155" x2="180" y2="215" stroke={C.blue} strokeWidth="6"/><line x1="350" y1="155" x2="350" y2="215" stroke={C.green} strokeWidth="6"/><line x1="525" y1="155" x2="525" y2="215" stroke={C.gold} strokeWidth="6"/><line x1="650" y1="145" x2="650" y2="225" stroke={C.red} strokeWidth="7"/></Canvas><Tag x={23} y={31} tone="blue">VFE</Tag><Tag x={44} y={31} tone="green">VNO</Tag><Tag x={66} y={31} tone="gold">VLO</Tag><Tag x={81} y={27} tone="red">VNE</Tag><Tag x={50} y={78}>EXACT VALUES AND COLOUR ARCS ARE AIRCRAFT-SPECIFIC</Tag></div>
    case "va": return <div className="relative"><Canvas><line x1="120" y1="285" x2="690" y2="285" stroke={C.navy} strokeWidth="3"/><line x1="120" y1="285" x2="120" y2="55" stroke={C.navy} strokeWidth="3"/><path d="M150 270 Q310 210 470 135" fill="none" stroke={C.blue} strokeWidth="4"/><line x1="470" y1="135" x2="630" y2="135" stroke={C.red} strokeWidth="4"/></Canvas><Tag x={59} y={27} tone="gold">VA INTERSECTION</Tag><Tag x={72} y={42} tone="red">LIMIT LOAD</Tag><Tag x={38} y={18}>LOWER WEIGHT → LOWER VA</Tag><Tag x={51} y={91}>AIRSPEED →</Tag></div>
    case "vx-vy": return <div className="relative"><Canvas><line x1="105" y1="285" x2="695" y2="285" stroke={C.navy} strokeWidth="3"/><rect x="570" y="105" width="20" height="180" fill={C.grey}/><path d="M125 270 Q275 260 370 220 Q470 175 555 115" fill="none" stroke={C.gold} strokeWidth="5"/><path d="M125 270 Q290 225 455 120" fill="none" stroke={C.blue} strokeWidth="5"/></Canvas><Tag x={60} y={23} tone="blue">VY · BEST RATE</Tag><Tag x={66} y={43} tone="gold">VX · BEST ANGLE</Tag><Tag x={73} y={22} tone="grey">OBSTACLE</Tag><Tag x={50} y={90}>VX = HEIGHT / DISTANCE · VY = HEIGHT / TIME</Tag></div>
    case "isa": return <div className="relative"><Canvas><line x1="400" y1="300" x2="400" y2="65" stroke={C.navy} strokeWidth="4"/><line x1="210" y1="275" x2="590" y2="105" stroke={C.gold} strokeWidth="5"/></Canvas><Tag x={26} y={86} tone="gold">MSL TEMP 15°C</Tag><Tag x={75} y={22} tone="gold">−1.98°C / 1000 ft</Tag><Tag x={76} y={72}>MSL PRESSURE 1013.25 hPa</Tag><Tag x={24} y={27}>MSL DENSITY 1.225 kg/m³</Tag></div>
    case "humidity-density": return <TwoCard leftTitle="DRY AIR" leftText="At the same temperature and pressure, dry air is more dense." rightTitle="HUMID AIR" rightText="Water vapour displaces heavier nitrogen/oxygen molecules, so humid air is less dense." />
    case "pressure-temp-density": return <TwoCard leftTitle="PRESSURE ↑" leftText="Density increases if temperature is held constant." rightTitle="TEMPERATURE ↑" rightText="Density decreases if pressure is held constant." />
    case "propeller-effects": return <div className="relative"><Canvas><circle cx="400" cy="180" r="82" fill="none" stroke={C.navy} strokeWidth="4"/><line x1="400" y1="75" x2="400" y2="285" stroke={C.gold} strokeWidth="14" strokeLinecap="round"/><Arrow x1={510} y1={92} x2={580} y2={135} color={C.blue}/><Arrow x1={290} y1={270} x2={220} y2={225} color={C.red}/></Canvas><Tag x={78} y={24} tone="blue">PROP ROTATION</Tag><Tag x={20} y={82} tone="red">TORQUE REACTION</Tag><Tag x={50} y={90}>HIGH POWER + HIGH AoA CAN ALSO PRODUCE ASYMMETRIC BLADE EFFECT</Tag></div>
    case "weight-cg": return <div className="relative"><Canvas><path d="M180 180 L620 180 L670 200 L620 220 L180 220 L130 200Z" fill={C.pale} stroke={C.navy} strokeWidth="3"/><circle cx="400" cy="200" r="10" fill={C.gold}/><Arrow x1={400} y1={210} x2={400} y2={315} color={C.blue}/></Canvas><Tag x={50} y={43} tone="gold">CENTRE OF GRAVITY</Tag><Tag x={57} y={90} tone="blue">TOTAL WEIGHT ACTS THROUGH CG</Tag></div>
  }
}

export function PrinciplesOfFlightVisualV3({ question }: { question: Question }) {
  const spec = getSpec(question)
  return <figure className="mt-5 overflow-hidden border border-slate-200 bg-white"><div className="bg-[#06111f] px-4 py-4 text-center sm:px-6 sm:py-5"><div className="text-[11px] font-extrabold tracking-[0.24em] text-[#f4b400] sm:text-xs">PILOTVAULT PRINCIPLES OF FLIGHT</div><div className="mt-1 text-lg font-extrabold uppercase tracking-[0.025em] text-white sm:text-2xl">{spec.title}</div></div><div className="bg-[#f8fafc] p-3 sm:p-5"><div className="mx-auto max-w-4xl border border-slate-200 bg-white px-2 py-3 sm:px-4 sm:py-4"><TechnicalDiagram concept={spec.concept} /><div className="mx-auto mt-3 max-w-3xl border-t border-slate-200 px-3 pt-3 text-center text-sm leading-relaxed text-slate-700">{spec.note}</div></div></div></figure>
}
